{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedDeviceTypes"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier","text":"DeviceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"},{"text":"> { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See also "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypesByNumber","type":"reference"},{"type":"text","text":" for use in Objective-C"}]}]}],"type":"unorderedList"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypes-4f98s"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"]]},"kind":"symbol","abstract":[{"text":"Set of device types supported by the current license. Available in Swift only.","type":"text"}],"metadata":{"externalID":"s:15NixUniversalSDK14LicenseManagerC18allowedDeviceTypesShyAA0G4TypeOGvpZ","symbolKind":"property","modules":[{"name":"NixUniversalSDK"}],"title":"allowedDeviceTypes","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedDeviceTypes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType","kind":"typeIdentifier"},{"kind":"text","text":">"}],"roleHeading":"Type Property"},"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype","title":"DeviceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"url":"\/documentation\/nixuniversalsdk\/licensemanager","title":"LicenseManager","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManager"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allowedDeviceTypes-4f98s":{"abstract":[{"type":"text","text":"Set of device types supported by the current license. Available in Swift only."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","title":"allowedDeviceTypes","url":"\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypes-4f98s","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedDeviceTypes"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allowedDeviceTypesByNumber":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypesbynumber","title":"allowedDeviceTypesByNumber","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypesByNumber","navigatorTitle":[{"text":"allowedDeviceTypes","kind":"identifier"}],"abstract":[{"text":"Set of ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" containing the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true,"type":"reference"},{"type":"text","text":" values enabled by the current license."}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedDeviceTypesByNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":">","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","op":"replace","value":"DeviceType"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceType"}],"op":"replace"},{"value":"LicenseManager","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","op":"replace"},{"value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments"},{"value":[{"kind":"identifier","text":"LicenseManager"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","op":"replace"},{"value":"allowedDeviceTypes","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allowedDeviceTypesByNumber\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allowedDeviceTypesByNumber\/fragments","value":[{"text":"allowedDeviceTypes","kind":"identifier"}],"op":"replace"}]}]}