{"abstract":[{"text":"Provides an interpolated reflectance value at a specified wavelength value using natural cubic spines. The cubic splines are evaluated at the points specified by ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value","type":"reference","isActive":true},{"text":". Interpolated values are evaluated using natural cubic splines.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interpolate(lT:)"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/interpolate(lt:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/interpolate(lt:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(interpolateAtLt:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Wavelength (nm) at which to query the interpolated reflectance","type":"text"}],"type":"paragraph"}],"name":"lT"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"Interpolated reflectance value at lT","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lT","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"modules":[{"name":"NixUniversalSDK"}],"title":"interpolate(lT:)","required":true,"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"interpolateAtLt:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(im)interpolateAtLt:","symbolKind":"method"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"role":"symbol","kind":"symbol","title":"ISpectralData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISpectralData"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/ispectraldata"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/lambda":{"required":true,"kind":"symbol","abstract":[{"text":"Wavelength values. Each entry ","type":"text"},{"type":"codeVoice","code":"i"},{"text":" in this array corresponds to a spectral value in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value"},{"text":" at the same index.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lambda"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"lambda","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/lambda","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","title":"lambda","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/value":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/value","abstract":[{"type":"text","text":"Spectral reflectance values. Each entry "},{"type":"codeVoice","code":"i"},{"type":"text","text":" in this array corresponds to a wavelength value in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda"},{"type":"text","text":" at the same index."}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value","kind":"symbol","required":true,"title":"value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/interpolate(lT:)":{"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interpolateAtLt:"}],"required":true,"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/interpolate(lt:)","kind":"symbol","title":"interpolate(lT:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Provides an interpolated reflectance value at a specified wavelength value using natural cubic spines. The cubic splines are evaluated at the points specified by "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value","type":"reference","isActive":true},{"type":"text","text":". Interpolated values are evaluated using natural cubic splines."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interpolate(lT:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"interpolateAtLt:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interpolateAtLt:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"text":"interpolateAtLt:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"lT","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Wavelength (nm) at which to query the interpolated reflectance"}],"type":"paragraph"}],"name":"lT"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Interpolated reflectance value at lT"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","value":[{"text":"ISpectralData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ISpectralData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"value":"lambda","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1lambda\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1lambda\/fragments","value":[{"kind":"identifier","text":"lambda"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1value\/title","value":"value","op":"replace"},{"value":[{"kind":"identifier","text":"value"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1value\/fragments"},{"value":"interpolateAtLt:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1interpolate(lT:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interpolateAtLt:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1interpolate(lT:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}