{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/mode"},"metadata":{"required":true,"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"title":"mode","externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(py)mode","symbolKind":"property","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"mode"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","text":"ScanMode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"abstract":[{"text":"Scan mode for this measurement.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/mode"]},{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/mode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"title":"ScanMode","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","url":"\/documentation\/nixuniversalsdk\/scanmode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/mode":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"kind":"text","text":": "},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/mode","kind":"symbol","abstract":[{"type":"text","text":"Scan mode for this measurement."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/mode","role":"symbol","required":true,"title":"mode","navigatorTitle":[{"text":"mode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","title":"ISpectralData","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISpectralData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mode","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","text":"ScanMode"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","value":"ScanMode"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"kind":"identifier","text":"ScanMode"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1mode\/title","value":"mode"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1mode\/fragments","op":"replace","value":[{"kind":"identifier","text":"mode"}]},{"op":"replace","value":"ISpectralData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle","op":"replace"}]}]}