{"metadata":{"role":"symbol","title":"Dictionary","extendedModule":"Swift","externalID":"s:e:s:SD15NixUniversalSDKSo8NSNumberCRszAA16IMeasurementData_pRs_rlE11scanModeMapSDyAA04ScanH0OAaD_pGvp","modules":[{"relatedModules":["Swift"],"name":"NixUniversalSDK"}],"roleHeading":"Extended Structure","fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"kind":"identifier","text":"["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","text":"IMeasurementData","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"symbolKind":"extension","navigatorTitle":[{"kind":"identifier","text":"Dictionary"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/swift\/dictionary"]}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary\/scanModeMap"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"}]}]}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift/Dictionary/scanModeMap":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary\/scanModeMap","title":"scanModeMap","type":"topic","abstract":[{"type":"text","text":"Dictionary with "},{"code":"NSNumber","type":"codeVoice"},{"text":" keys unwrapped into ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"text":" keys","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"scanModeMap","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"},{"text":" : ","kind":"text"},{"text":"IMeasurementData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/swift\/dictionary\/scanmodemap","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Key"},{"type":"text","text":" is "},{"type":"codeVoice","code":"NSNumber"},{"text":" and ","type":"text"},{"code":"Value","type":"codeVoice"},{"type":"text","text":" is "},{"code":"any IMeasurementData","type":"codeVoice"},{"type":"text","text":"."}]}},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift/Dictionary":{"title":"Dictionary","type":"topic","url":"\/documentation\/nixuniversalsdk\/swift\/dictionary","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary","kind":"symbol","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"[","kind":"identifier"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" : ","kind":"text"},{"text":"IMeasurementData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"Dictionary"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"}],"url":"\/documentation\/nixuniversalsdk\/scanmode","role":"symbol","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"title":"ScanMode"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift":{"type":"topic","title":"Swift","url":"\/documentation\/nixuniversalsdk\/swift","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","value":"ScanMode"},{"value":[{"kind":"identifier","text":"ScanMode"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments"},{"value":[{"text":"ScanMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}