{"metadata":{"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@InterfaceType@InterfaceTypeUNDEFINED","title":"InterfaceType.UNDEFINED","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UNDEFINED"}],"navigatorTitle":[{"text":"InterfaceTypeUNDEFINED","kind":"identifier"}],"role":"symbol","symbolKind":"case","roleHeading":"Case"},"kind":"symbol","abstract":[{"text":"Device does not have a defined connection type.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/UNDEFINED"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/undefined"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/undefined"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNDEFINED"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/UNDEFINED":{"kind":"symbol","abstract":[{"text":"Device does not have a defined connection type.","type":"text"}],"role":"symbol","title":"InterfaceType.UNDEFINED","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UNDEFINED"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/interfacetype\/undefined","navigatorTitle":[{"kind":"identifier","text":"InterfaceTypeUNDEFINED"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/UNDEFINED"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType":{"abstract":[{"text":"Enum describing the supported connection interface types for Nix devices.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","navigatorTitle":[{"text":"InterfaceType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"InterfaceType","kind":"identifier"}],"type":"topic","title":"InterfaceType","url":"\/documentation\/nixuniversalsdk\/interfacetype","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"InterfaceTypeUNDEFINED"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"InterfaceTypeUNDEFINED","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"InterfaceTypeUNDEFINED","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1UNDEFINED\/title","value":"InterfaceTypeUNDEFINED","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1UNDEFINED\/fragments","value":[{"text":"InterfaceTypeUNDEFINED","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/title","op":"replace","value":"InterfaceType"},{"op":"replace","value":[{"text":"InterfaceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/fragments"},{"value":[{"kind":"identifier","text":"InterfaceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}