{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(startWithClosure:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"closure","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"DeviceFoundCallback","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback"},{"text":") -> ","kind":"text"},{"text":"DeviceScannerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState"}]}]},{"kind":"parameters","parameters":[{"name":"closure","content":[{"inlineContent":[{"type":"text","text":"Closure invoked when a device is found. Invoked with a "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" result when a search times out and device was not found."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See also: "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(scanPeriodMs:closure:)","type":"reference"}]}]}],"type":"unorderedList"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/idevicescanner\/start(closure:)"]},{"paths":["\/documentation\/nixuniversalsdk\/idevicescanner\/start(closure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Starts a search for nearby Nix devices using Bluetooth for time interval of ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(closure:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"]]},"metadata":{"role":"symbol","title":"start(closure:)","symbolKind":"method","required":true,"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IDeviceScanner(im)startWithClosure:","roleHeading":"Instance Method","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeviceFoundCallback","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DeviceScannerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner/start(closure:)":{"role":"symbol","title":"start(closure:)","abstract":[{"text":"Starts a search for nearby Nix devices using Bluetooth for time interval of ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(closure:)","url":"\/documentation\/nixuniversalsdk\/idevicescanner\/start(closure:)","required":true,"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"closure","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DeviceFoundCallback","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"DeviceScannerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceFoundCallback":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback","url":"\/documentation\/nixuniversalsdk\/devicefoundcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceFoundCallback","kind":"identifier"}],"title":"DeviceFoundCallback","role":"symbol","navigatorTitle":[{"text":"DeviceFoundCallback","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Definition for a closure invoked when an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true,"type":"reference"},{"type":"text","text":" has discovered a supported Nix device"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"role":"symbol","title":"IDeviceScanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","abstract":[{"type":"text","text":"Protocol implemented by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/idevicescanner","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner/DEFAULT_GENERAL_SCAN_PERIOD_MS":{"role":"symbol","abstract":[{"type":"text","text":"Scan period in milliseconds (20000) used when no time period is provided to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(scanPeriodMs:closure:)"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS","title":"DEFAULT_GENERAL_SCAN_PERIOD_MS","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_GENERAL_SCAN_PERIOD_MS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner\/default_general_scan_period_ms"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner/start(scanPeriodMs:closure:)":{"role":"symbol","title":"start(scanPeriodMs:closure:)","abstract":[{"text":"Starts a search for nearby Nix devices using Bluetooth for a selected time interval. If no timeout interval is specified, the search will run for ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(scanPeriodMs:closure:)","url":"\/documentation\/nixuniversalsdk\/idevicescanner\/start(scanperiodms:closure:)","required":true,"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"startForPeriodMs:withClosure:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"scanPeriodMs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"closure","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","text":"DeviceFoundCallback"},{"kind":"text","text":") -> "},{"text":"DeviceScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate","abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"navigatorTitle":[{"text":"DeviceScannerState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","type":"topic","title":"DeviceScannerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"startWithClosure:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState"},{"text":") ","kind":"text"},{"kind":"identifier","text":"startWithClosure:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"id<IDeviceCompat>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceCompat"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"closure","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Closure invoked when a device is found. Invoked with a ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" result when a search times out and device was not found.","type":"text"}],"type":"paragraph"}],"name":"closure"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"kind":"identifier","text":"DeviceScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"op":"replace","value":"startWithClosure:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1start(closure:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1start(closure:)\/fragments"},{"op":"replace","value":"IDeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IDeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments"},{"op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle"},{"op":"replace","value":"startForPeriodMs:withClosure:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1start(scanPeriodMs:closure:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1start(scanPeriodMs:closure:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startForPeriodMs:withClosure:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title","value":"DeviceScannerState"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","value":[{"kind":"identifier","text":"DeviceScannerState"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScannerState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}