{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"]]},"kind":"symbol","metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isDeviceTypeSupported","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isDeviceTypeSupported:","kind":"identifier"}],"symbolKind":"method","title":"isDeviceTypeSupported(_:)","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)LicenseManager(cm)isDeviceTypeSupported:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanager\/isdevicetypesupported(_:)"]},{"paths":["\/documentation\/nixuniversalsdk\/licensemanager\/isdevicetypesupported(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Helper to check if a particular ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"type":"text","text":" is supported by the current license."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(isDeviceTypeSupported:) "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDeviceTypeSupported"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"DeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isDeviceTypeSupported(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","type":"topic","title":"isDeviceTypeSupported(_:)","url":"\/documentation\/nixuniversalsdk\/licensemanager\/isdevicetypesupported(_:)","abstract":[{"text":"Helper to check if a particular ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"text":" is supported by the current license.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDeviceTypeSupported","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"isDeviceTypeSupported:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseManager"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","role":"symbol","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"}],"title":"LicenseManager"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"navigatorTitle":[{"text":"DeviceType","kind":"identifier"}],"type":"topic","title":"DeviceType","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceType"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"url":"\/documentation\/nixuniversalsdk\/devicetype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"isDeviceTypeSupported:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isDeviceTypeSupported:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"isDeviceTypeSupported:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"isDeviceTypeSupported:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isDeviceTypeSupported:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseManager"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments"},{"op":"replace","value":[{"text":"LicenseManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle"},{"value":"DeviceType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceType"}]}]}]}