{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromInt(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","role":"symbol","title":"fromInt(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromInt"},{"kind":"text","text":"("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"}],"modules":[{"name":"NixUniversalSDK"}],"externalID":"s:15NixUniversalSDK8ScanModeO7fromIntyACSiFZ","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"]]},"abstract":[{"text":"Helper to find a ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true,"type":"reference"},{"text":" enum from an integer value, or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","type":"reference"},{"type":"text","text":" for invalid input."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromInt"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"int","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode\/fromint(_:)"]}],"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","url":"\/documentation\/nixuniversalsdk\/scanmode","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}],"navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"title":"ScanMode","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/NA":{"kind":"symbol","type":"topic","title":"ScanMode.NA","abstract":[{"text":"Unknown \/ undefined conditions","type":"text"}],"navigatorTitle":[{"text":"ScanModeNA","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NA"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/na"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromInt(_:)":{"kind":"symbol","abstract":[{"text":"Helper to find a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"type":"text","text":" enum from an integer value, or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA"},{"text":" for invalid input.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/fromint(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromInt(_:)","title":"fromInt(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromInt","kind":"identifier"},{"kind":"text","text":"("},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"ScanMode","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title"},{"value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","value":[{"text":"ScanMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/title","value":"ScanModeNA","op":"replace"},{"value":[{"kind":"identifier","text":"ScanModeNA"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}