{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromAdvertisingName"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","roleHeading":"Type Method","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromAdvertisingName"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"}],"title":"fromAdvertisingName(_:)","externalID":"s:15NixUniversalSDK10DeviceTypeO19fromAdvertisingNameyACSSSgFZ"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicetype\/fromadvertisingname(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromAdvertisingName(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Helper method to find the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"text":" enum that corresponds to the name found during device advertisement. If an unknown name is provided, ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","type":"reference","isActive":true},{"text":" is returned.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/UNKNOWN":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","role":"symbol","navigatorTitle":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"title":"DeviceType.UNKNOWN","abstract":[{"text":"Unknown \/ other device type","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNKNOWN"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/unknown"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype","title":"DeviceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fromAdvertisingName(_:)":{"url":"\/documentation\/nixuniversalsdk\/devicetype\/fromadvertisingname(_:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromAdvertisingName"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType"}],"abstract":[{"text":"Helper method to find the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","type":"reference","isActive":true},{"text":" enum that corresponds to the name found during device advertisement. If an unknown name is provided, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","isActive":true},{"text":" is returned.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromAdvertisingName(_:)","title":"fromAdvertisingName(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DeviceTypeUNKNOWN","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/fragments","op":"replace","value":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}]},{"op":"replace","value":"DeviceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceType"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}