{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicetype\/fromuint8(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fromUint8","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"byte","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier","text":"DeviceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"}]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromUint8(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"fromUint8(_:)","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fromUint8","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType","kind":"typeIdentifier"}],"externalID":"s:15NixUniversalSDK10DeviceTypeO9fromUint8yACs5UInt8VFZ","role":"symbol"},"abstract":[{"type":"text","text":"Helper method to find the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"},{"text":" enum that corresponds to a byte value. If an unknown byte value is provided ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","isActive":true},{"type":"text","text":" is returned."}],"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"title":"DeviceType","url":"\/documentation\/nixuniversalsdk\/devicetype","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/UNKNOWN":{"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeUNKNOWN"}],"role":"symbol","type":"topic","title":"DeviceType.UNKNOWN","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UNKNOWN","kind":"identifier"}],"abstract":[{"type":"text","text":"Unknown \/ other device type"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/unknown"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fromUint8(_:)":{"abstract":[{"type":"text","text":"Helper method to find the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"type":"text","text":" enum that corresponds to a byte value. If an unknown byte value is provided "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN"},{"type":"text","text":" is returned."}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/fromuint8(_:)","title":"fromUint8(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromUint8(_:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromUint8","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","op":"replace","value":"DeviceType"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceType"}]},{"op":"replace","value":"DeviceTypeUNKNOWN","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/title"},{"op":"replace","value":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/fragments"}]}]}