{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromVid(_:pid:)","interfaceLanguage":"swift"},"abstract":[{"text":"Helper method to find the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"text":" enum that corresponds to a given USB vendor ID and product ID. If an unknown combination is provided ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","isActive":true,"type":"reference"},{"type":"text","text":" is returned."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/fromvid(_:pid:)"]}],"metadata":{"externalID":"s:15NixUniversalSDK10DeviceTypeO7fromVid_3pidACs6UInt16VSg_AHtFZ","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Type Method","title":"fromVid(_:pid:)","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromVid"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","kind":"typeIdentifier","text":"UInt16"},{"kind":"text","text":"?) -> "},{"text":"DeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromVid"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"vid","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"},{"text":"?, ","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","kind":"typeIdentifier","text":"DeviceType"}],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/UNKNOWN":{"kind":"symbol","abstract":[{"type":"text","text":"Unknown \/ other device type"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","type":"topic","title":"DeviceType.UNKNOWN","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UNKNOWN","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/unknown"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fromVid(_:pid:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromVid(_:pid:)","abstract":[{"type":"text","text":"Helper method to find the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","type":"reference"},{"type":"text","text":" enum that corresponds to a given USB vendor ID and product ID. If an unknown combination is provided "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","type":"reference"},{"type":"text","text":" is returned."}],"title":"fromVid(_:pid:)","url":"\/documentation\/nixuniversalsdk\/devicetype\/fromvid(_:pid:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromVid"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pid","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"url":"\/documentation\/nixuniversalsdk\/devicetype","title":"DeviceType","navigatorTitle":[{"text":"DeviceType","kind":"identifier"}],"abstract":[{"text":"Enum to describe the supported Nix device types","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DeviceTypeUNKNOWN","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/title"},{"op":"replace","value":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","value":"DeviceType","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DeviceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle"}]}]}