{"abstract":[{"text":"Unknown \/ other device type","type":"text"}],"kind":"symbol","metadata":{"externalID":"c:@M@NixUniversalSDK@E@DeviceType@DeviceTypeUNKNOWN","role":"symbol","symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"UNKNOWN","kind":"identifier"}],"title":"DeviceType.UNKNOWN"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"UNKNOWN","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/unknown"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/UNKNOWN":{"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeUNKNOWN"}],"role":"symbol","type":"topic","title":"DeviceType.UNKNOWN","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UNKNOWN","kind":"identifier"}],"abstract":[{"type":"text","text":"Unknown \/ other device type"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/unknown"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"title":"DeviceType","url":"\/documentation\/nixuniversalsdk\/devicetype","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"DeviceTypeUNKNOWN","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/title","op":"replace","value":"DeviceTypeUNKNOWN"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceTypeUNKNOWN"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/fragments"},{"value":"DeviceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}