{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"NA","kind":"identifier"}],"platforms":["macOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"NA","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@ScanMode@ScanModeNA","role":"symbol","navigatorTitle":[{"text":"ScanModeNA","kind":"identifier"}],"title":"ScanMode.NA","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}]},"sections":[],"abstract":[{"type":"text","text":"Unknown \/ undefined conditions"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode\/na"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode\/na"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/NA":{"abstract":[{"text":"Unknown \/ undefined conditions","type":"text"}],"title":"ScanMode.NA","navigatorTitle":[{"text":"ScanModeNA","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/na","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NA"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"title":"ScanMode","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","url":"\/documentation\/nixuniversalsdk\/scanmode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ScanModeNA"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ScanModeNA","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ScanModeNA","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/title","value":"ScanModeNA"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/fragments","value":[{"kind":"identifier","text":"ScanModeNA"}]},{"op":"replace","value":"ScanMode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"text":"ScanMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ScanMode"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle"}]}]}