{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"]]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onBatteryStateChanged(_:newState:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the Nix device has updated its battery level measurement."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onBatteryStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","kind":"typeIdentifier","text":"IDeviceCompat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"Device instance that has invoked this call","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New battery level (0 to 100)"}]}],"name":"newState"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestatedelegate\/onbatterystatechanged(_:newstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestatedelegate\/onbatterystatechanged(_:newstate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"onBatteryStateChanged(_:newState:)","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)DeviceStateDelegate(im)onBatteryStateChanged:newState:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onBatteryStateChanged"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"newState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":")","kind":"text"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onBatteryStateChanged:newState:"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescanner","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onBatteryStateChanged(_:newState:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Called when the Nix device has updated its battery level measurement."}],"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/onbatterystatechanged(_:newstate:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onBatteryStateChanged:newState:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onBatteryStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"newState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":")","kind":"text"}],"required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onBatteryStateChanged(_:newState:)","title":"onBatteryStateChanged(_:newState:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":".","type":"text"}],"title":"IDeviceCompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"abstract":[{"type":"text","text":"Definition for a callback from an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","title":"DeviceStateDelegate","navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStateDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"onBatteryStateChanged:newState:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onBatteryStateChanged:newState:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onBatteryStateChanged:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<IDeviceCompat>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceCompat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":" "},{"kind":"identifier","text":"newState:"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"newState","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"sender","content":[{"inlineContent":[{"type":"text","text":"Device instance that has invoked this call"}],"type":"paragraph"}]},{"name":"newState","content":[{"type":"paragraph","inlineContent":[{"text":"New battery level (0 to 100)","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onBatteryStateChanged(_:newState:)\/title","value":"onBatteryStateChanged:newState:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onBatteryStateChanged(_:newState:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onBatteryStateChanged:newState:","kind":"identifier"}]},{"value":"IDeviceCompat","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","value":"DeviceStateDelegate"},{"op":"replace","value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceStateDelegate"}]}]}]}