{"abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if an invalid white point is specified.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(reference:type:)"]},{"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(reference:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"},{"text":" = .D50_2, ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"kind":"text","text":" = .CIEXYZ) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Selected reference white (defaults to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","isActive":true},{"type":"text","text":")"}],"type":"paragraph"}],"name":"reference"},{"name":"type","content":[{"inlineContent":[{"text":"Output color type (defaults to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ"},{"text":")","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See also: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)"}]}]}]}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","interfaceLanguage":"swift"},"metadata":{"title":"toColorData(reference:type:)","externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(im)toColorDataForReference:andType:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"toColorDataForReference:andType:"}],"modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","title":"IColorData","navigatorTitle":[{"kind":"identifier","text":"IColorData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"navigatorTitle":[{"text":"SpectralData","kind":"identifier"}],"abstract":[{"type":"text","text":"Class describing spectral data"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SpectralData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","type":"topic","kind":"symbol","title":"SpectralData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","url":"\/documentation\/nixuniversalsdk\/referencewhite","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"kind":"symbol","title":"ReferenceWhite","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","url":"\/documentation\/nixuniversalsdk\/colortype","kind":"symbol","title":"ColorType","role":"symbol","navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorType"}],"abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","type":"reference"},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","navigatorTitle":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CIEXYZ","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Report color value as CIEXYZ value on unity scale.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","title":"ColorType.CIEXYZ"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toColorData(illuminant:observer:type:)":{"url":"\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(illuminant:observer:type:)","navigatorTitle":[{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toColorData"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if an invalid white point is specified."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)","title":"toColorData(illuminant:observer:type:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toColorData(reference:type:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if an invalid white point is specified."}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(reference:type:)","title":"toColorData(reference:type:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"toColorDataForReference:andType:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_2":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D50_2","kind":"identifier"}],"abstract":[{"type":"text","text":"White point using Illuminant D50 and 2 degree observer."}],"role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_2","type":"topic","title":"ReferenceWhite.D50_2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"toColorDataForReference:andType:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toColorDataForReference:andType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","text":"id<IColorData>"},{"kind":"text","text":") "},{"kind":"identifier","text":"toColorDataForReference:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reference"},{"kind":"text","text":" "},{"kind":"identifier","text":"andType:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData","op":"replace"},{"value":[{"kind":"identifier","text":"IColorData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"IColorData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"},{"value":"SpectralData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","op":"replace"},{"value":[{"text":"SpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SpectralData"}]},{"op":"replace","value":"ReferenceWhite","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","op":"replace","value":"ColorType"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"text":"ColorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"kind":"identifier","text":"ColorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title","op":"replace","value":"ColorTypeCIEXYZ"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments","value":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}]},{"op":"replace","value":"toColorDataForIlluminant:andObserver:andType:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(illuminant:observer:type:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(illuminant:observer:type:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}]},{"value":"toColorDataForReference:andType:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(reference:type:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(reference:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toColorDataForReference:andType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/title","value":"ReferenceWhiteD50_2"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/fragments"}]}]}