{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toDensityData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier"},{"kind":"text","text":" = .T) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","text":"IDensityData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"Density status (defaults to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","type":"reference"},{"text":")","type":"text"}]}]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.0.2"}]}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toDensityData(status:)","interfaceLanguage":"swift"},"abstract":[{"text":"Provides absolute density values for this measurement for the specified density status evaluated as per ISO 5-3:2009.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/todensitydata(status:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/todensitydata(status:)"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"metadata":{"title":"toDensityData(status:)","roleHeading":"Instance Method","externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(im)toDensityDataForStatus:","navigatorTitle":[{"text":"toDensityDataForStatus:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toDensityData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IDensityData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData"},{"text":"?","kind":"text"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol"},"sections":[],"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SpectralData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"abstract":[{"type":"text","text":"Class describing spectral data"}],"type":"topic","kind":"symbol","title":"SpectralData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDensityData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"IDensityData","kind":"identifier"}],"title":"IDensityData","type":"topic","abstract":[{"type":"text","text":"Protocol describing density data"}],"url":"\/documentation\/nixuniversalsdk\/idensitydata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/T":{"url":"\/documentation\/nixuniversalsdk\/densitystatus\/t","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"T","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","title":"DensityStatus.T","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DensityStatusT"}],"abstract":[{"text":"Status T (ISO 5-3:2009)","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"abstract":[{"type":"text","text":"Enum to describe the available options for density status"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","title":"DensityStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DensityStatus","kind":"identifier"}],"navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/densitystatus"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toDensityData(status:)":{"title":"toDensityData(status:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toDensityData(status:)","navigatorTitle":[{"text":"toDensityDataForStatus:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toDensityData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData","text":"IDensityData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Provides absolute density values for this measurement for the specified density status evaluated as per ISO 5-3:2009.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/todensitydata(status:)","role":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"toDensityDataForStatus:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toDensityDataForStatus:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<IDensityData>","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDensityData","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"toDensityDataForStatus:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","text":"DensityStatus","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"},{"kind":"text","text":") "},{"text":"status","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","value":"SpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","value":[{"kind":"identifier","text":"SpectralData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","value":[{"kind":"identifier","text":"SpectralData"}],"op":"replace"},{"value":"IDensityData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments","value":[{"text":"IDensityData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle","value":[{"kind":"identifier","text":"IDensityData"}],"op":"replace"},{"value":"DensityStatusT","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/fragments","op":"replace","value":[{"text":"DensityStatusT","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","value":"DensityStatus","op":"replace"},{"value":[{"kind":"identifier","text":"DensityStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments"},{"op":"replace","value":[{"text":"DensityStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toDensityData(status:)\/title","op":"replace","value":"toDensityDataForStatus:"},{"value":[{"text":"- ","kind":"text"},{"text":"toDensityDataForStatus:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toDensityData(status:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}