{"sections":[],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"roleHeading":"Instance Method","externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(im)toRgbValueForIlluminant:andObserver:","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"title":"toRgbValue(illuminant:observer:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)"},"kind":"symbol","abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(illuminant:observer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(illuminant:observer:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","kind":"typeIdentifier","text":"Illuminant"},{"kind":"text","text":" = .D50, "},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":" = .CIE1931) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"illuminant","content":[{"type":"paragraph","inlineContent":[{"text":"Selected illuminant reference for output (defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true},{"text":")","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Selected observer reference for output (defaults to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"reference"},{"type":"text","text":")"}],"type":"paragraph"}],"name":"observer"}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"See also: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"title":"Illuminant","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Illuminant"}],"abstract":[{"text":"Enum to describe the available options for reference illuminant","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","url":"\/documentation\/nixuniversalsdk\/illuminant","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toRgbValue(reference:)":{"url":"\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(reference:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)","abstract":[{"type":"text","text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is "},{"code":"nil","type":"codeVoice"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}],"title":"toRgbValue(reference:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":">?","kind":"text"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toRgbValue(illuminant:observer:)":{"url":"\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(illuminant:observer:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)","abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"navigatorTitle":[{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"title":"toRgbValue(illuminant:observer:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Observer"}],"title":"Observer","role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Observer","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CIE1931","kind":"identifier"}],"navigatorTitle":[{"text":"ObserverCIE1931","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","role":"symbol","abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"kind":"symbol","title":"Observer.CIE1931","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SpectralData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"abstract":[{"type":"text","text":"Class describing spectral data"}],"type":"topic","kind":"symbol","title":"SpectralData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50"}],"navigatorTitle":[{"text":"IlluminantD50","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/d50","title":"Illuminant.D50","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"toRgbValueForIlluminant:andObserver:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"toRgbValueForIlluminant:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":") "},{"kind":"internalParam","text":"illuminant"},{"text":" ","kind":"text"},{"text":"andObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Illuminant","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","op":"replace","value":[{"kind":"identifier","text":"Illuminant"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toRgbValueForReference:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(reference:)\/fragments"},{"value":"toRgbValueForIlluminant:andObserver:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(illuminant:observer:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(illuminant:observer:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","op":"replace","value":"Observer"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"text":"Observer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","value":[{"text":"Observer","kind":"identifier"}],"op":"replace"},{"value":"ObserverCIE1931","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title"},{"value":[{"kind":"identifier","text":"ObserverCIE1931"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","value":"SpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","value":[{"kind":"identifier","text":"SpectralData"}]},{"op":"replace","value":[{"kind":"identifier","text":"SpectralData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","value":"IlluminantD50"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments","value":[{"text":"IlluminantD50","kind":"identifier"}],"op":"replace"}]}]}