{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toDensityData(status:)"},"metadata":{"navigatorTitle":[{"text":"toDensityDataForStatus:","kind":"identifier"}],"title":"toDensityData(status:)","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toDensityData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","text":"DensityStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData","text":"IDensityData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(im)toDensityDataForStatus:","roleHeading":"Instance Method","modules":[{"name":"NixUniversalSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(toDensityDataForStatus:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toDensityData","kind":"identifier"},{"kind":"text","text":"("},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"},{"text":") -> ","kind":"text"},{"text":"IDensityData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"status","content":[{"inlineContent":[{"type":"text","text":"Density status (defaults to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","isActive":true},{"text":")","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.0.2"}]}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/todensitydata(status:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/todensitydata(status:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"abstract":[{"text":"Provides absolute density values for this measurement for the specified density status evaluated as per ISO 5-3:2009.","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toDensityData(status:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toDensityData"},{"kind":"text","text":"("},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","text":"DensityStatus"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData","text":"IDensityData"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"toDensityDataForStatus:"}],"abstract":[{"text":"Provides absolute density values for this measurement for the specified density status evaluated as per ISO 5-3:2009.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toDensityData(status:)","title":"toDensityData(status:)","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/todensitydata(status:)","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","url":"\/documentation\/nixuniversalsdk\/densitystatus","type":"topic","abstract":[{"text":"Enum to describe the available options for density status","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DensityStatus"}],"title":"DensityStatus","navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","title":"ISpectralData","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISpectralData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/T":{"role":"symbol","abstract":[{"text":"Status T (ISO 5-3:2009)","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"T","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/densitystatus\/t","kind":"symbol","navigatorTitle":[{"text":"DensityStatusT","kind":"identifier"}],"title":"DensityStatus.T","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"title":"IDensityData","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDensityData"}],"abstract":[{"type":"text","text":"Protocol describing density data"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idensitydata","navigatorTitle":[{"text":"IDensityData","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"toDensityDataForStatus:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"toDensityDataForStatus:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<IDensityData>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDensityData"},{"text":") ","kind":"text"},{"kind":"identifier","text":"toDensityDataForStatus:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"status"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Density status (defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","isActive":true},{"text":")","type":"text"}]}],"name":"status"}]},"op":"replace"},{"value":"toDensityDataForStatus:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toDensityData(status:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"toDensityDataForStatus:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toDensityData(status:)\/fragments","op":"replace"},{"value":"DensityStatus","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DensityStatus"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","value":[{"kind":"identifier","text":"DensityStatus"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","value":[{"text":"ISpectralData","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ISpectralData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/title","op":"replace","value":"DensityStatusT"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/fragments","value":[{"text":"DensityStatusT","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title","value":"IDensityData","op":"replace"},{"value":[{"text":"IDensityData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle","value":[{"kind":"identifier","text":"IDensityData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}