{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"abstract":[{"text":"White point using Illuminant C and 10 degree observer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C_10","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"ReferenceWhiteC_10","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteC_10","symbolKind":"case","title":"ReferenceWhite.C_10","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C_10","kind":"identifier"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_10","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/c_10"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/c_10"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ReferenceWhite","kind":"identifier"}],"title":"ReferenceWhite","type":"topic","navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","kind":"article","title":"Handling Measurement Data","role":"article","type":"topic","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/C_10":{"abstract":[{"type":"text","text":"White point using Illuminant C and 10 degree observer."}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/c_10","navigatorTitle":[{"text":"ReferenceWhiteC_10","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_10","type":"topic","title":"ReferenceWhite.C_10","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C_10","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ReferenceWhiteC_10"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteC_10"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"ReferenceWhiteC_10","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1C_10\/title","value":"ReferenceWhiteC_10"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1C_10\/fragments","value":[{"text":"ReferenceWhiteC_10","kind":"identifier"}]}]}]}