{"abstract":[{"type":"text","text":"White point using Illuminant F11 and 10 degree observer."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_10","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"F11_10"}]}]}],"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"F11_10"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"ReferenceWhiteF11_10","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteF11_10","modules":[{"name":"NixUniversalSDK"}],"title":"ReferenceWhite.F11_10"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f11_10"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f11_10"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"role":"symbol","title":"ReferenceWhite","navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F11_10":{"abstract":[{"type":"text","text":"White point using Illuminant F11 and 10 degree observer."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"F11_10"}],"title":"ReferenceWhite.F11_10","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/f11_10","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_10","navigatorTitle":[{"text":"ReferenceWhiteF11_10","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ReferenceWhiteF11_10","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ReferenceWhiteF11_10"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ReferenceWhiteF11_10"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhite"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle"},{"value":"ReferenceWhiteF11_10","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F11_10\/title"},{"op":"replace","value":[{"text":"ReferenceWhiteF11_10","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F11_10\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}