{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/observer","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"},{"text":" for the selected reference white","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"metadata":{"symbolKind":"property","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"}],"title":"observer","externalID":"s:15NixUniversalSDK14ReferenceWhiteO8observerAA8ObserverOvp","role":"symbol","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/observer"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"observer"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"url":"\/documentation\/nixuniversalsdk\/referencewhite","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"type":"topic","title":"ReferenceWhite","kind":"symbol","navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Observer"}],"title":"Observer","role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Observer","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/observer":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"observer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"role":"symbol","title":"observer","url":"\/documentation\/nixuniversalsdk\/referencewhite\/observer","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/observer","abstract":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"reference","isActive":true},{"type":"text","text":" for the selected reference white"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"Observer","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title"},{"value":[{"kind":"identifier","text":"Observer"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Observer"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle"}]}]}