{"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/unwrapSet(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/unwrapset(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unwrapSet","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"},{"text":">","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"NixUniversalSDK"}],"externalID":"s:15NixUniversalSDK14ReferenceWhiteO9unwrapSetyShyACGShySo8NSNumberCGSgFZ","title":"unwrapSet(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unwrapSet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"list"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":">?) -> ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":">","kind":"text"}],"platforms":["macOS"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/unwrapSet(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/unwrapSet(_:)","url":"\/documentation\/nixuniversalsdk\/referencewhite\/unwrapset(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unwrapSet","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":">?) -> ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":">","kind":"text"}],"title":"unwrapSet(_:)","role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ReferenceWhite","kind":"identifier"}],"title":"ReferenceWhite","type":"topic","navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ReferenceWhite","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title"},{"op":"replace","value":[{"text":"ReferenceWhite","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhite"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}