{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/activating-license"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/activating-license"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"anchor":"Getting-Started","generated":true,"title":"Getting Started"}],"kind":"article","metadata":{"modules":[{"name":"NixUniversalSDK"}],"role":"article","roleHeading":"Article","title":"Activating the SDK License"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An activation code is required to use the Nix Universal SDK. The license determines:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Which device types are available for discovery and connection."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Which features and data types are available for connected devices."}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"By default, all Nix device operations are disabled. It is necessary to activate the license before these are made available to the host application.","type":"text"}],"type":"paragraph"},{"type":"heading","level":3,"text":"Obtaining a license key","anchor":"Obtaining-a-license-key"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Free evaluation codes are available for non-commercial use. To obtain an activation code, visit to the "},{"identifier":"https:\/\/www.nixsensor.com\/nix-sdk-license","isActive":true,"type":"reference"},{"type":"text","text":" page."}]},{"type":"heading","level":3,"text":"Using the License Manager","anchor":"Using-the-License-Manager"},{"type":"paragraph","inlineContent":[{"type":"text","text":"License operations are handled via a static instance of the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"text":". A license is activated by calling ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","isActive":true,"type":"reference"},{"type":"text","text":". This method takes the license options and signature strings as arguments and returns the activation result as a "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","isActive":true,"type":"reference"},{"text":" value.","type":"text"}]},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"License activations remain valid within a single session, but do not persist across different application launches. Therefore, it is required to call "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","type":"reference"},{"type":"text","text":" at least once per session."}]}]},{"type":"heading","anchor":"Swift-example","level":4,"text":"Swift example"},{"type":"codeListing","syntax":"swift","code":["\/\/ Update these string values to match your provided license","let options: String = \"REPLACE_WITH_LICENSE_OPTIONS\"","let signature: String = \"REPLACE_WITH_LICENSE_SIGNATURE\"","","let activationState = LicenseManager.Activate(","    options: options, ","    signature: signature)"]},{"text":"Objective-C example","level":4,"type":"heading","anchor":"Objective-C-example"},{"type":"codeListing","code":["\/\/ Update these string values to match your provided license","NSString* options = @\"REPLACE_WITH_LICENSE_OPTIONS\";","NSString* signature = @\"REPLACE_WITH_LICENSE_SIGNATURE\";","","enum LicenseManagerState activationState = ","    [LicenseManager activateWithOptions:optionsString","                           andSignature:signatureString];"],"syntax":"objc"},{"type":"aside","name":"Tip","style":"tip","content":[{"type":"paragraph","inlineContent":[{"text":"The license manager state can also be checked at any time via ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","isActive":true},{"type":"text","text":"."}]}]},{"inlineContent":[{"type":"text","text":"Device operations are only available if the resulting state is equal to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","isActive":true,"type":"reference"},{"type":"text","text":". All other values indicate an error state. Refer to the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","type":"reference","isActive":true},{"text":" API documentation for further details.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"You can switch licenses by calling "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","type":"reference","isActive":true},{"type":"text","text":" repeated times within a single session. Doing so will invalidate any open device connections. Any connected Nix devices will need to be disconnected and discovered again using a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"text":" after switching licenses.","type":"text"}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"},{"level":3,"anchor":"Other-license-properties","text":"Other license properties","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional license properties can be queried on the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"text":". Note that some properties may be blank or empty depending on your license capabilities.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UUID"}]},{"items":[{"content":[{"inlineContent":[{"text":"Unique ID for your SDK license.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Refer to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/uuid","type":"reference","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Expiry date","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Indicates when the current license ceases to be valid."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Refer to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/expiry","type":"reference","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Allocation codes","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of pre-authorized device allocation codes, used when accessing private labelled Nix devices."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"May be empty for general use cases."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allocations"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Allowed device types","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"List of Nix ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"type":"text","text":" values that are supported by the current license."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Refer to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","isActive":true},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"Enabled features"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"List of SDK ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"reference"},{"type":"text","text":" values enabled by the current license."}]}]},{"content":[{"inlineContent":[{"text":"Refer to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/features-3nk3h","type":"reference","isActive":true},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SDK version"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Indicates the current version of the Nix Universal SDK."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Refer to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/libraryVersion","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"type":"heading","text":"Next Steps","anchor":"Next-Steps","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","type":"reference"}]}]}],"type":"unorderedList"}]}],"references":{"https://www.nixsensor.com/nix-sdk-license":{"type":"link","title":"SDK license","titleInlineContent":[{"text":"SDK license","type":"text"}],"url":"https:\/\/www.nixsensor.com\/nix-sdk-license","identifier":"https:\/\/www.nixsensor.com\/nix-sdk-license"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"kind":"article","abstract":[{"text":"Review the changes made in this version of the library","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","url":"\/documentation\/nixuniversalsdk\/release-notes","title":"Release Notes","type":"topic","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","abstract":[{"type":"text","text":"The license has activated successfully and Nix Universal SDK functions are available."}],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active","role":"symbol","title":"LicenseManagerState.ACTIVE","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ACTIVE","kind":"identifier"}],"navigatorTitle":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","abstract":[{"text":"Use the device scanner to discover Nix devices and open a connection","type":"text"}],"kind":"article","title":"Discovering and Connecting to Nix Devices","type":"topic","role":"article","url":"\/documentation\/nixuniversalsdk\/discovering-connecting"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allowedDeviceTypes-4f98s":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedDeviceTypes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"},{"kind":"text","text":">"}],"title":"allowedDeviceTypes","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Set of device types supported by the current license. Available in Swift only."}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypes-4f98s"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","url":"\/documentation\/nixuniversalsdk\/device-operations","kind":"article","type":"topic","role":"article","abstract":[{"text":"Take measurements, set device options, and query device properties","type":"text"}],"title":"Device Operations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"navigatorTitle":[{"text":"DeviceType","kind":"identifier"}],"type":"topic","title":"DeviceType","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceType"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"url":"\/documentation\/nixuniversalsdk\/devicetype"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"abstract":[{"text":"Review an example project which provides a C\/C++ interface for macOS applications","type":"text"}],"type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/wrapper","title":"Wrapper for Usage in C\/C++","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"kind":"article","role":"article","type":"topic","abstract":[{"text":"Query measurement values including colorimetry, spectral reflectance, and density","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/handling-measurements","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","title":"Handling Measurement Data"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isDeviceTypeSupported(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","type":"topic","title":"isDeviceTypeSupported(_:)","url":"\/documentation\/nixuniversalsdk\/licensemanager\/isdevicetypesupported(_:)","abstract":[{"text":"Helper to check if a particular ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true},{"text":" is supported by the current license.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDeviceTypeSupported","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"isDeviceTypeSupported:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","abstract":[{"text":"Add the library bundle to your project and declare peripheral uses","type":"text"}],"kind":"article","title":"Adding to Your Xcode Project","type":"topic","role":"article","url":"\/documentation\/nixuniversalsdk\/add-to-xcode"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","abstract":[{"type":"text","text":"Helper to check if a particular "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","isActive":true,"type":"reference"},{"type":"text","text":" is enabled by the current license."}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","title":"isFeatureEnabled(_:)","navigatorTitle":[{"kind":"identifier","text":"isFeatureEnabled:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isFeatureEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LicenseFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","role":"symbol","title":"LicenseManagerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LicenseManagerState","kind":"identifier"}],"navigatorTitle":[{"text":"LicenseManagerState","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseFeature"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","title":"LicenseFeature","abstract":[{"type":"text","text":"Enum describing the optional features that can be enabled by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"text":". Feature availability can be queried using ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/nixuniversalsdk\/licensefeature","role":"symbol","navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/expiry":{"navigatorTitle":[{"text":"expiry","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/expiry","abstract":[{"text":"Expiry date for the current license.","type":"text"}],"title":"expiry","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/expiry","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiry"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allocations":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allocations"}],"abstract":[{"type":"text","text":"List of Nix device allocation codes associated with the current license."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allocations","url":"\/documentation\/nixuniversalsdk\/licensemanager\/allocations","title":"allocations","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allocations","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/features-3nk3h":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/features-3nk3h","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/features-3nk3h","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"features","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"LicenseFeature","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature","kind":"typeIdentifier"},{"kind":"text","text":">"}],"title":"features","abstract":[{"type":"text","text":"Set of features enabled by the current license. Available in Swift only."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/state":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","title":"state","abstract":[{"type":"text","text":"Describes the current state of the  "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true},{"text":". Nix Universal SDK functions are available only if license is active (i.e. - the state is ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","type":"reference","isActive":true},{"type":"text","text":")"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/state","role":"symbol","navigatorTitle":[{"text":"state","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/libraryVersion":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/libraryversion","navigatorTitle":[{"text":"libraryVersion","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraryVersion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","abstract":[{"type":"text","text":"Current version of the Nix Universal SDK."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/libraryVersion","title":"libraryVersion"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseManager"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","role":"symbol","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"}],"title":"LicenseManager"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/uuid":{"abstract":[{"type":"text","text":"Vendor identifier for the current license."}],"title":"uuid","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/uuid","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/uuid","navigatorTitle":[{"text":"uuid","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uuid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","role":"article","title":"Example Applications","abstract":[{"text":"Explore source code for demo iOS and macOS applications","type":"text"}],"type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/example-apps"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/activate(options:signature:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"kind":"text","text":"("},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"signature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/activate(options:signature:)","kind":"symbol","abstract":[{"type":"text","text":"Activates a license. The options and signature parameters must exactly match the values provided in the SDK license. Calling this function invalidates any currently active license."}],"role":"symbol","title":"activate(options:signature:)","navigatorTitle":[{"kind":"identifier","text":"activateWithOptions:andSignature:"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceScanner","kind":"identifier"}],"kind":"symbol","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","navigatorTitle":[{"text":"DeviceScanner","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"replace","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"generated":true,"anchor":"Getting-Started"}],"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title","value":"LicenseManagerStateACTIVE","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments","value":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","value":"DeviceType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceType"}]},{"op":"replace","value":"isDeviceTypeSupported:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isDeviceTypeSupported:"}]},{"value":"isFeatureEnabled:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"isFeatureEnabled:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title","op":"replace","value":"LicenseManagerState"},{"op":"replace","value":[{"text":"LicenseManagerState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments"},{"value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle"},{"value":"LicenseFeature","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseFeature"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle","value":[{"text":"LicenseFeature","kind":"identifier"}]},{"value":"expiry","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1expiry\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1expiry\/fragments","value":[{"kind":"identifier","text":"expiry"}]},{"value":"allocations","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allocations\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allocations\/fragments","value":[{"text":"allocations","kind":"identifier"}],"op":"replace"},{"value":"state","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/title","op":"replace"},{"value":[{"text":"state","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1libraryVersion\/title","value":"libraryVersion","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1libraryVersion\/fragments","value":[{"text":"libraryVersion","kind":"identifier"}]},{"value":"LicenseManager","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","value":[{"kind":"identifier","text":"LicenseManager"}]},{"value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle"},{"value":"uuid","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1uuid\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1uuid\/fragments","op":"replace","value":[{"kind":"identifier","text":"uuid"}]},{"value":"activateWithOptions:andSignature:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"activateWithOptions:andSignature:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","op":"replace","value":"DeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"text":"DeviceScanner","kind":"identifier"}]}]}]}