{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"abstract":[{"text":"Enum describing the available color difference (delta E) equations.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype"]},{"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorDifferenceType"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@NixUniversalSDK@E@ColorDifferenceType","navigatorTitle":[{"text":"ColorDifferenceType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorDifferenceType"}],"title":"ColorDifferenceType","role":"symbol"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE2000","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE76","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94G","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94T","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC1_1","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC2_1"],"generated":true,"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/name"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE94T":{"role":"symbol","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94t","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIE94T","kind":"identifier"}],"title":"ColorDifferenceType.CIE94T","abstract":[{"type":"text","text":"Color difference using CIE1994 equation using constants recommended for textiles."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94T","type":"topic","navigatorTitle":[{"text":"ColorDifferenceTypeCIE94T","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE94G":{"title":"ColorDifferenceType.CIE94G","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIE94G","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94G"}],"abstract":[{"text":"Color difference using CIE1994 equation using constants recommended for graphic design.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94G","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94g"},"doc://com.nixsensor.universalsdk/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","type":"unresolvable"},"doc://com.nixsensor.universalsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/name":{"title":"name","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/name","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/name","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"String representation of this "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","type":"reference","isActive":true}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CMC1_1":{"title":"ColorDifferenceType.CMC1_1","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CMC1_1","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCMC1_1"}],"abstract":[{"text":"Color difference using CMC(l:c) equation with l = 1, and c = 1 (‘threshold of imperceptibility’)","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC1_1","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cmc1_1"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CMC2_1":{"title":"ColorDifferenceType.CMC2_1","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCMC2_1"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"CMC2_1","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Color difference using CMC(l:c) equation with l = 2, and c = 1 (‘threshold of acceptability’)"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC2_1","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cmc2_1"},"doc://com.nixsensor.universalsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/Equatable-Implementations":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/equatable-implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE76":{"title":"ColorDifferenceType.CIE76","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIE76"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie76","abstract":[{"type":"text","text":"Color difference using CIE1976 equation."}],"navigatorTitle":[{"text":"ColorDifferenceTypeCIE76","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE76","role":"symbol","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"role":"symbol","abstract":[{"type":"text","text":"Enum describing the available color difference (delta E) equations."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorDifferenceType","kind":"identifier"}],"navigatorTitle":[{"text":"ColorDifferenceType","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype","title":"ColorDifferenceType","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE2000":{"navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCIE2000"}],"title":"ColorDifferenceType.CIE2000","abstract":[{"type":"text","text":"Color difference using CIE2000 equation using default constants."}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie2000","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE2000","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIE2000","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/RawRepresentable-Implementations","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"ColorDifferenceType","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"ColorDifferenceType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ColorDifferenceType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE2000","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE76","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94G","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94T","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC1_1","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC2_1"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorDifferenceType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94T\/title","value":"ColorDifferenceTypeCIE94T"},{"value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94T"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94T\/fragments","op":"replace"},{"value":"ColorDifferenceTypeCIE94G","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94G\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94G\/fragments","value":[{"text":"ColorDifferenceTypeCIE94G","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CMC1_1\/title","value":"ColorDifferenceTypeCMC1_1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CMC1_1\/fragments","value":[{"text":"ColorDifferenceTypeCMC1_1","kind":"identifier"}]},{"value":"ColorDifferenceTypeCMC2_1","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CMC2_1\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CMC2_1\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceTypeCMC2_1"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE76\/title","value":"ColorDifferenceTypeCIE76","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE76\/fragments","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE76"}]},{"value":"ColorDifferenceType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}]},{"value":[{"kind":"identifier","text":"ColorDifferenceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle"},{"value":"ColorDifferenceTypeCIE2000","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE2000\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE2000\/fragments","value":[{"text":"ColorDifferenceTypeCIE2000","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}