{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","interfaceLanguage":"swift"},"abstract":[{"text":"Color math utility functions","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/adaptXyz(xyzIn:refIn:refOut:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/clipXyz(xyz:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE00(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE00(lab1:lab2:kL:kC:kH:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE76(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94(lab1:lab2:kL:k1:k2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94G(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94T(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaECmc(lab1:lab2:l:c:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToLch(labIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToXyz(lab:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/lchToLab(lchIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/lchToLuv(lchIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToLch(luvIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToXyz(luvIn:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/sRgbToXyz(sRgb:refOut:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToDensity(lambda:reflectance:status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToXyz(lambda:reflectance:illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLab(xyz:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLuv(xyzIn:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToSrgb(xyzIn:refIn:)"],"anchor":"Type-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorUtils"}],"platforms":["macOS"]}]}],"metadata":{"navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorUtils"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","title":"ColorUtils","roleHeading":"Class","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils","symbolKind":"class"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils"]}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaECmc(lab1:lab2:l:c:)":{"abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CMC(l:c) formula. Depends on model parameters l and c; common values used are CMC(2:1) for acceptability and CMC(1:1) for perceptibility. Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE"}],"navigatorTitle":[{"text":"deltaECmcWithLab1:lab2:l:c:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/deltaecmc(lab1:lab2:l:c:)","title":"deltaECmc(lab1:lab2:l:c:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deltaECmc","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lab1","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"lab2"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"l","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"c","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaECmc(lab1:lab2:l:c:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToLuv(xyzIn:xyzRef:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLuv(xyzIn:xyzRef:)","abstract":[{"text":"Takes CIEXYZ value and its reference white to calculate CIELUV value","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToLuv","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"xyzRef","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"xyzToLuvWithXyzIn:xyzRef:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztoluv(xyzin:xyzref:)","title":"xyzToLuv(xyzIn:xyzRef:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/spectral10ToXyz(lambda:reflectance:illuminant:observer:)":{"abstract":[{"text":"Takes reflectance data on 10 nm intervals and calculates a CIEXYZ value according to ASTM E308. Data must be provided on 10 nm intervals corresponding to the nearest 10 nanometer. CIEXYZ values are calculated across the range 360 - 780 nm. If the provided data spans a shorter range (eg - 400 - 700 nm), the values at the boundaries are repeated.","type":"text"}],"navigatorTitle":[{"text":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/spectral10toxyz(lambda:reflectance:illuminant:observer:)","title":"spectral10ToXyz(lambda:reflectance:illuminant:observer:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spectral10ToXyz","kind":"identifier"},{"kind":"text","text":"("},{"text":"lambda","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"reflectance"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"observer"},{"text":": ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToXyz(lambda:reflectance:illuminant:observer:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/spectral10ToDensity(lambda:reflectance:status:)":{"abstract":[{"text":"Takes reflectance data on 10 nm intervals and calculates CMYK densities according to ISO 5-3:2009. Data must be provided on 10 nm intervals corresponding to the nearest 10 nanometer. Density values are calculated across the range 340 - 770 nm. If the provided data spans a shorter range (eg - 400 - 700 nm), the values at the boundaries are repeated.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"spectral10ToDensity"},{"text":"(","kind":"text"},{"text":"lambda","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":">, ","kind":"text"},{"text":"reflectance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":">, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">"}],"title":"spectral10ToDensity(lambda:reflectance:status:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToDensity(lambda:reflectance:status:)","role":"symbol","navigatorTitle":[{"text":"spectral10ToDensityWithLambda:reflectance:status:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/spectral10todensity(lambda:reflectance:status:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/lchToLuv(lchIn:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lchToLuv","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lchIn"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/lchToLuv(lchIn:)","type":"topic","title":"lchToLuv(lchIn:)","abstract":[{"text":"Takes LCHuv value and converts to CIELUV","type":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/lchtoluv(lchin:)","navigatorTitle":[{"kind":"identifier","text":"lchToLuvWithLchIn:"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE94T(lab1:lab2:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94T(lab1:lab2:)","title":"deltaE94T(lab1:lab2:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae94t(lab1:lab2:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"deltaE94TWithLab1:lab2:","kind":"identifier"}],"abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula for the textiles application ("},{"type":"codeVoice","code":"kL"},{"type":"text","text":" = 2, "},{"code":"k1","type":"codeVoice"},{"type":"text","text":" = 0.048, "},{"type":"codeVoice","code":"k2"},{"text":" = 0.014). Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deltaE94T"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lab1"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">) -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/luvToXyz(luvIn:xyzRef:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToXyz(luvIn:xyzRef:)","type":"topic","title":"luvToXyz(luvIn:xyzRef:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/luvtoxyz(luvin:xyzref:)","abstract":[{"type":"text","text":"Takes CIELUV value and its reference white to calculate CIEXYZ value"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"luvToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"luvIn","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"luvToXyzWithLuvIn:xyzRef:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)":{"type":"topic","title":"xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","navigatorTitle":[{"kind":"identifier","text":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztorgb(xyzin:refin:rchrom:gchrom:bchrom:wchrom:)","kind":"symbol","abstract":[{"type":"text","text":"Calculates linear RGB from XYZ given chromaticity coordinates of RGB working space primaries and reference whites of RGB and XYZ value"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"xyzToRgb","kind":"identifier"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"text":"refIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"rChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"gChrom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"bChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"wChrom"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">) -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToCmyk(xyzIn:xyzRef:bpc:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xyzToCmyk"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"text":"xyzRef","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"bpc"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:)","kind":"symbol","abstract":[{"text":"Calculates CMYK value from XYZ input using built in lookup tables","type":"text"}],"role":"symbol","title":"xyzToCmyk(xyzIn:xyzRef:bpc:)","navigatorTitle":[{"kind":"identifier","text":"xyzToCmykWithXyzIn:xyzRef:bpc:"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE00(lab1:lab2:)":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae00(lab1:lab2:)","title":"deltaE00(lab1:lab2:)","type":"topic","abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE2000 formula using default model parameters (kL = kC = kH = 1.0). Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE00(lab1:lab2:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deltaE00"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lab1"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"lab2"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">) -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"deltaE00WithLab1:lab2:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/s7CVarArgP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/rgbtoxyz(rgbin:rchrom:gchrom:bchrom:wchrom:refout:)","title":"rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","type":"topic","abstract":[{"text":"Calculates XYZ from linear RGB given chromaticity coordinates of RGB working space primaries and reference whites of RGB and XYZ value.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rgbToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rgbIn"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"rChrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"gChrom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"bChrom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"wChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToLab(xyz:xyzRef:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLab(xyz:xyzRef:)","role":"symbol","abstract":[{"text":"Takes CIEXYZ value and its reference white to calculate CIELAB value. ","type":"text"},{"type":"codeVoice","code":"xyz"},{"type":"text","text":" and "},{"type":"codeVoice","code":"xyzRef"},{"text":" can be either unity (0 - 1) or scaled (0 - 100) input, but both vectors must be the same scale; if ","type":"text"},{"type":"codeVoice","code":"xyz"},{"type":"text","text":" is unity scale, "},{"code":"xyzRef","type":"codeVoice"},{"text":" must also be unity scale","type":"text"}],"type":"topic","title":"xyzToLab(xyz:xyzRef:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"xyzToLab","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyz","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"xyzRef"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztolab(xyz:xyzref:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"xyzToLabWithXyz:xyzRef:"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)":{"title":"cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cmykToXyz","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cmykIn"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"refOut","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"m"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"input"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"]], "},{"text":"clut","kind":"externalParam"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"]], ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": [[","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"]]) -> [","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:m:input:clut:output:)","navigatorTitle":[{"text":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","kind":"identifier"}],"abstract":[{"type":"text","text":"Calculates XYZ value from CMYK input using lookup tables provided as input arguments"}]},"doc://com.nixsensor.universalsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/luvToLch(luvIn:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToLch(luvIn:)","type":"topic","abstract":[{"type":"text","text":"Takes CIELUV value and converts to polar coordinates (LCH)"}],"role":"symbol","title":"luvToLch(luvIn:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"luvToLch"},{"kind":"text","text":"("},{"text":"luvIn","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/luvtolch(luvin:)","kind":"symbol","navigatorTitle":[{"text":"luvToLchWithLuvIn:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE94(lab1:lab2:kL:k1:k2:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94(lab1:lab2:kL:k1:k2:)","role":"symbol","abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula. Requires weighting factors kL, k1, and k2 which are dependent on application. Use the "},{"type":"codeVoice","code":"deltaE94G"},{"type":"text","text":" method for graphic design applications and the "},{"code":"deltaE94T","type":"codeVoice"},{"text":" for textile applications. Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE.","type":"text"}],"type":"topic","title":"deltaE94(lab1:lab2:kL:k1:k2:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deltaE94"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lab1"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"lab2"},{"kind":"text","text":": "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"kL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"k1"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"k2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae94(lab1:lab2:kl:k1:k2:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"deltaE94WithLab1:lab2:kL:k1:k2:"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE00(lab1:lab2:kL:kC:kH:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE00(lab1:lab2:kL:kC:kH:)","role":"symbol","abstract":[{"text":"Takes two CIELAB values and calculates color difference (dE) using CIE2000 formula. Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE.","type":"text"}],"type":"topic","title":"deltaE00(lab1:lab2:kL:kC:kH:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deltaE00","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lab1"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"lab2"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"kL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"text":"kC","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"kH","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae00(lab1:lab2:kl:kc:kh:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"deltaE00WithLab1:lab2:kL:kC:kH:"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)":{"abstract":[{"type":"text","text":"Calculates CMYK value from XYZ using lookup tables provided as "},{"type":"codeVoice","code":"inputCurves"},{"type":"text","text":" arguments"}],"title":"xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","kind":"symbol","navigatorTitle":[{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:m:inputcurves:clut:outputcurves:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToCmyk","kind":"identifier"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"text":"xyzRef","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"m","kind":"externalParam"},{"text":": [[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"]], "},{"text":"inputCurves","kind":"externalParam"},{"text":": [[","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"]], "},{"text":"clut","kind":"externalParam"},{"text":": [[","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]], ","kind":"text"},{"text":"outputCurves","kind":"externalParam"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]]) -> [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","role":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/labToLch(labIn:)":{"abstract":[{"text":"Takes CIELAB value and converts to polar coordinates (LCH)","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/labtolch(labin:)","title":"labToLch(labIn:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToLch(labIn:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labToLch"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"labIn"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"labToLchWithLabIn:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/cmykToXyz(cmykIn:refOut:bpc:)":{"role":"symbol","navigatorTitle":[{"text":"cmykToXyzWithCmykIn:refOut:bpc:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:)","type":"topic","title":"cmykToXyz(cmykIn:refOut:bpc:)","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmykToXyz"},{"kind":"text","text":"("},{"text":"cmykIn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"], ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"]","kind":"text"}],"abstract":[{"text":"Calculates XYZ value from CMYK input using built-in lookup tables","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","url":"\/documentation\/nixuniversalsdk\/colorutils","type":"topic","kind":"symbol","title":"ColorUtils","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorUtils","kind":"identifier"}],"abstract":[{"text":"Color math utility functions","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}]},"doc://com.nixsensor.universalsdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/adaptXyz(xyzIn:refIn:refOut:)":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/adaptxyz(xyzin:refin:refout:)","title":"adaptXyz(xyzIn:refIn:refOut:)","type":"topic","abstract":[{"text":"Adapts colour in XYZ from one reference white to another using Bradford adaptation method. NOTE: ","type":"text"},{"type":"codeVoice","code":"refIn"},{"type":"text","text":", "},{"type":"codeVoice","code":"refOut"},{"text":", ","type":"text"},{"code":"xyzIn","type":"codeVoice"},{"text":" must all be on the same scale.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/adaptXyz(xyzIn:refIn:refOut:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adaptXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"text":"refIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refOut"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"adaptXyzWithXyzIn:refIn:refOut:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/labToXyz(lab:xyzRef:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"labToXyzWithLab:xyzRef:"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/labtoxyz(lab:xyzref:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToXyz(lab:xyzRef:)","title":"labToXyz(lab:xyzRef:)","role":"symbol","abstract":[{"text":"Takes CIELAB value and its reference white to calculate CIEXYZ value","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lab","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"xyzRef","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE76(lab1:lab2:)":{"navigatorTitle":[{"kind":"identifier","text":"deltaE76WithLab1:lab2:"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae76(lab1:lab2:)","title":"deltaE76(lab1:lab2:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE1976 formula. Both CIELAB values must share the same reference white. If they do not, convert to XYZ, adapt, convert back to CIELAB before calculating dE"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE76(lab1:lab2:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deltaE76","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lab1"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"lab2"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/sRgbToXyz(sRgb:refOut:)":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/srgbtoxyz(srgb:refout:)","title":"sRgbToXyz(sRgb:refOut:)","type":"topic","abstract":[{"text":"Calculates XYZ from sRGB value.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/sRgbToXyz(sRgb:refOut:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sRgbToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sRgb"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refOut"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"sRgbToXyzWithSRgb:refOut:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/clipXyz(xyz:xyzRef:)":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/clipxyz(xyz:xyzref:)","title":"clipXyz(xyz:xyzRef:)","type":"topic","abstract":[{"type":"text","text":"Clips CIEXYZ values in between 0 and the value of the reference white to ensure X,Y,Z are in the proper range."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/clipXyz(xyz:xyzRef:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clipXyz"},{"text":"(","kind":"text"},{"text":"xyz","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"xyzRef","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"clipXyzWithXyz:xyzRef:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/init":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/init","title":"init","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE94G(lab1:lab2:)":{"url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae94g(lab1:lab2:)","title":"deltaE94G(lab1:lab2:)","type":"topic","abstract":[{"text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula for the graphic design application (","type":"text"},{"code":"kL","type":"codeVoice"},{"text":" = 1, ","type":"text"},{"code":"k1","type":"codeVoice"},{"type":"text","text":" = 0.045, "},{"type":"codeVoice","code":"k2"},{"type":"text","text":" = 0.015). Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94G(lab1:lab2:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deltaE94G"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lab1"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"lab2"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"text":"deltaE94GWithLab1:lab2:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/lchToLab(lchIn:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/lchToLab(lchIn:)","role":"symbol","navigatorTitle":[{"text":"lchToLabWithLchIn:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lchToLab"},{"text":"(","kind":"text"},{"text":"lchIn","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Takes LCHab value and converts to CIELAB"}],"title":"lchToLab(lchIn:)","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/lchtolab(lchin:)"},"doc://com.nixsensor.universalsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToSrgb(xyzIn:refIn:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToSrgb(xyzIn:refIn:)","role":"symbol","navigatorTitle":[{"text":"xyzToSrgbWithXyzIn:refIn:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"xyzToSrgb","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"text":"refIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"type":"topic","abstract":[{"text":"Calculates companded sRGB value from XYZ given reference white of XYZ value","type":"text"}],"title":"xyzToSrgb(xyzIn:refIn:)","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztosrgb(xyzin:refin:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ColorUtils","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/init"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/adaptXyz(xyzIn:refIn:refOut:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/clipXyz(xyz:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE00(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE00(lab1:lab2:kL:kC:kH:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE76(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94(lab1:lab2:kL:k1:k2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94G(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94T(lab1:lab2:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaECmc(lab1:lab2:l:c:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToLch(labIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToXyz(lab:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/lchToLab(lchIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/lchToLuv(lchIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToLch(luvIn:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToXyz(luvIn:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/sRgbToXyz(sRgb:refOut:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToDensity(lambda:reflectance:status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToXyz(lambda:reflectance:illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLab(xyz:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLuv(xyzIn:xyzRef:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToSrgb(xyzIn:refIn:)"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorUtils"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"deltaECmcWithLab1:lab2:l:c:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaECmc(lab1:lab2:l:c:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaECmc(lab1:lab2:l:c:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deltaECmcWithLab1:lab2:l:c:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToLuv(xyzIn:xyzRef:)\/title","value":"xyzToLuvWithXyzIn:xyzRef:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"xyzToLuvWithXyzIn:xyzRef:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToLuv(xyzIn:xyzRef:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToXyz(lambda:reflectance:illuminant:observer:)\/title","op":"replace","value":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToXyz(lambda:reflectance:illuminant:observer:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:"}]},{"op":"replace","value":"spectral10ToDensityWithLambda:reflectance:status:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToDensity(lambda:reflectance:status:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"spectral10ToDensityWithLambda:reflectance:status:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToDensity(lambda:reflectance:status:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1lchToLuv(lchIn:)\/title","value":"lchToLuvWithLchIn:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"lchToLuvWithLchIn:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1lchToLuv(lchIn:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94T(lab1:lab2:)\/title","value":"deltaE94TWithLab1:lab2:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94T(lab1:lab2:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"deltaE94TWithLab1:lab2:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToXyz(luvIn:xyzRef:)\/title","value":"luvToXyzWithLuvIn:xyzRef:"},{"value":[{"text":"+ ","kind":"text"},{"text":"luvToXyzWithLuvIn:xyzRef:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToXyz(luvIn:xyzRef:)\/fragments"},{"value":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)\/fragments","op":"replace"},{"op":"replace","value":"xyzToCmykWithXyzIn:xyzRef:bpc:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE00(lab1:lab2:)\/title","value":"deltaE00WithLab1:lab2:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE00(lab1:lab2:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deltaE00WithLab1:lab2:"}]},{"value":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToLab(xyz:xyzRef:)\/title","value":"xyzToLabWithXyz:xyzRef:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"xyzToLabWithXyz:xyzRef:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToLab(xyz:xyzRef:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)\/title","value":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)\/fragments","op":"replace"},{"value":"luvToLchWithLuvIn:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToLch(luvIn:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToLch(luvIn:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"luvToLchWithLuvIn:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94(lab1:lab2:kL:k1:k2:)\/title","op":"replace","value":"deltaE94WithLab1:lab2:kL:k1:k2:"},{"value":[{"kind":"text","text":"+ "},{"text":"deltaE94WithLab1:lab2:kL:k1:k2:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94(lab1:lab2:kL:k1:k2:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE00(lab1:lab2:kL:kC:kH:)\/title","value":"deltaE00WithLab1:lab2:kL:kC:kH:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE00(lab1:lab2:kL:kC:kH:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"deltaE00WithLab1:lab2:kL:kC:kH:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)\/title","value":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1labToLch(labIn:)\/title","op":"replace","value":"labToLchWithLabIn:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"labToLchWithLabIn:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1labToLch(labIn:)\/fragments"},{"op":"replace","value":"cmykToXyzWithCmykIn:refOut:bpc:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"cmykToXyzWithCmykIn:refOut:bpc:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils"},{"value":[{"text":"ColorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","op":"replace"},{"value":[{"text":"ColorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1adaptXyz(xyzIn:refIn:refOut:)\/title","value":"adaptXyzWithXyzIn:refIn:refOut:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1adaptXyz(xyzIn:refIn:refOut:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adaptXyzWithXyzIn:refIn:refOut:"}],"op":"replace"},{"op":"replace","value":"labToXyzWithLab:xyzRef:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1labToXyz(lab:xyzRef:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1labToXyz(lab:xyzRef:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"labToXyzWithLab:xyzRef:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE76(lab1:lab2:)\/title","op":"replace","value":"deltaE76WithLab1:lab2:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE76(lab1:lab2:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"deltaE76WithLab1:lab2:","kind":"identifier"}]},{"op":"replace","value":"sRgbToXyzWithSRgb:refOut:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1sRgbToXyz(sRgb:refOut:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sRgbToXyzWithSRgb:refOut:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1sRgbToXyz(sRgb:refOut:)\/fragments","op":"replace"},{"value":"clipXyzWithXyz:xyzRef:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1clipXyz(xyz:xyzRef:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1clipXyz(xyz:xyzRef:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"clipXyzWithXyz:xyzRef:","kind":"identifier"}],"op":"replace"},{"value":"deltaE94GWithLab1:lab2:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94G(lab1:lab2:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deltaE94GWithLab1:lab2:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94G(lab1:lab2:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1lchToLab(lchIn:)\/title","op":"replace","value":"lchToLabWithLchIn:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"lchToLabWithLchIn:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1lchToLab(lchIn:)\/fragments"},{"value":"xyzToSrgbWithXyzIn:refIn:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToSrgb(xyzIn:refIn:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToSrgb(xyzIn:refIn:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"xyzToSrgbWithXyzIn:refIn:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}