{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colordatanullable"]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDataNullable"},"sections":[],"metadata":{"externalID":"c:TypeAliases.h@T@ColorDataNullable","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","roleHeading":"Type Alias","symbolKind":"typealias","title":"ColorDataNullable","fragments":[{"text":"ColorDataNullable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ColorDataNullable"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","text":"id<IColorData>"},{"kind":"text","text":" "},{"text":"ColorDataNullable","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}],"abstract":[{"type":"text","text":"Nullable instance of an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true,"type":"reference"},{"type":"text","text":" object"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDataNullable":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDataNullable","title":"ColorDataNullable","type":"topic","role":"symbol","abstract":[{"text":"Nullable instance of an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"type":"text","text":" object"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colordatanullable","fragments":[{"kind":"identifier","text":"ColorDataNullable"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"role":"symbol","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IColorData"}],"type":"topic","title":"IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","navigatorTitle":[{"text":"IColorData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","op":"replace","value":[{"text":"IColorData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"IColorData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"}]}]}