{"abstract":[{"text":"Non-null instance of an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},{"text":" object","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDensityData","text":"id<IDensityData>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DensityDataNonnull"},{"text":";","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNonnull"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/densitydatanonnull"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"DensityDataNonnull"}],"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DensityDataNonnull"}],"roleHeading":"Type Alias","symbolKind":"typealias","role":"symbol","title":"DensityDataNonnull","externalID":"c:TypeAliases.h@T@DensityDataNonnull"},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityDataNonnull":{"type":"topic","fragments":[{"kind":"identifier","text":"DensityDataNonnull"}],"url":"\/documentation\/nixuniversalsdk\/densitydatanonnull","abstract":[{"type":"text","text":"Non-null instance of an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},{"text":" object","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNonnull","title":"DensityDataNonnull","role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDensityData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"IDensityData","kind":"identifier"}],"title":"IDensityData","type":"topic","abstract":[{"type":"text","text":"Protocol describing density data"}],"url":"\/documentation\/nixuniversalsdk\/idensitydata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title","op":"replace","value":"IDensityData"},{"value":[{"kind":"identifier","text":"IDensityData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle","value":[{"kind":"identifier","text":"IDensityData"}],"op":"replace"}]}]}