{"abstract":[{"text":"Nullable instance of an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","type":"reference","isActive":true},{"type":"text","text":" object"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNullable","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/densitydatanullable"]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDensityData","text":"id<IDensityData>"},{"kind":"text","text":" "},{"kind":"identifier","text":"DensityDataNullable"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"externalID":"c:TypeAliases.h@T@DensityDataNullable","roleHeading":"Type Alias","symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"DensityDataNullable"}],"role":"symbol","title":"DensityDataNullable","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"identifier","text":"DensityDataNullable"}]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"role":"symbol","title":"IDensityData","abstract":[{"text":"Protocol describing density data","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","url":"\/documentation\/nixuniversalsdk\/idensitydata","navigatorTitle":[{"kind":"identifier","text":"IDensityData"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDensityData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityDataNullable":{"abstract":[{"type":"text","text":"Nullable instance of an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNullable","url":"\/documentation\/nixuniversalsdk\/densitydatanullable","fragments":[{"kind":"identifier","text":"DensityDataNullable"}],"title":"DensityDataNullable","type":"topic","role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title","value":"IDensityData","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments","value":[{"kind":"identifier","text":"IDensityData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle","value":[{"text":"IDensityData","kind":"identifier"}],"op":"replace"}]}]}