{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/device-operations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/device-operations"]}],"kind":"article","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"NixUniversalSDK"}],"role":"article","roleHeading":"Article","title":"Device Operations"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"level":3,"type":"heading","anchor":"Taking-measurements","text":"Taking measurements"},{"type":"paragraph","inlineContent":[{"text":"Once the device is connected and in an idle state, it is possible to take measurements:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)"},{"text":" to take measurements in all modes supported by the device. This is the recommended option.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","type":"reference","isActive":true},{"type":"text","text":" to take measurement in only the specified scan modes. In most cases, this will not speed up the measurement cycle time, so this is not recommended."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The measurement operation is asynchronous and will return immediately. While the measurement is in progress, no other commands can be sent to the Nix device","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Results of the measurement operation are provided in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true,"type":"reference"},{"text":" closure specified when starting the measurement. This closure provides two arguments:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus"},{"type":"text","text":" status code, which will be "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/SUCCESS","isActive":true,"type":"reference"},{"type":"text","text":" for a successful operation."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary containing the measurement values as ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"text":" objects. The keys of this dictionary correspond to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"reference"},{"text":" for each measurement value.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"isActive":true,"identifier":"#handling-measurement-data","type":"reference"},{"type":"text","text":" below for notes on interpreting the measurement data."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The supported scan modes for a particular device are provided in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes","isActive":true},{"text":" list, or can be checked by calling ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isModeSupported(_:)"},{"type":"text","text":". The expected results by device are shown below:"}]}]}],"type":"unorderedList"}]}]},{"rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device Type"}]}],[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M1","isActive":true,"type":"reference"}]}],[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2","isActive":true}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"Mini","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}]],[[{"inlineContent":[{"type":"text","text":"Mini 2"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Mini 3","type":"text"}]}],[{"inlineContent":[{"text":"☐","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"Pro"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}]],[[{"inlineContent":[{"text":"Pro 2","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}]],[[{"inlineContent":[{"text":"QC","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"inlineContent":[{"type":"text","text":"☑"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"text":"Spectro 2 (F1.0.0)","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"inlineContent":[{"type":"text","text":"☑"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Spectro 2 (F2.0.0)"}]}],[{"inlineContent":[{"type":"text","text":"☑"}],"type":"paragraph"}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"☑"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"Spectro L","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}]]],"alignments":["left","center","center","center"],"type":"table","header":"row"},{"level":4,"text":"Swift example","anchor":"Swift-example","type":"heading"},{"type":"codeListing","code":["\/\/ Device instance","let device: IDeviceCompat","","\/\/ Callback for measurement","let callback: DeviceResultCallback = { status, measurements in","    switch status {","    case .SUCCESS:","        \/\/ Successful operation","        \/\/ Handle measurement data here","        \/\/ ...","        break","    case .ERROR_NOT_READY:","        \/\/ Did not complete because the device was busy","        \/\/ ...","        break","    case .ERROR_NOT_SUPPORTED:","        \/\/ Did not complete because an unsupported scan mode was","        \/\/ specified","        \/\/ ...","        break","    case .ERROR_LOW_POWER:","        \/\/ Did not complete because the battery level is too low","        \/\/ ...","        break","    case .ERROR_TIMEOUT:","        \/\/ Timeout when waiting for result","        \/\/ ...","        break","    case .ERROR_AMBIENT_LIGHT:","        \/\/ Did not complete because of ambient light leakage","        \/\/ ...","        break","    case .ERROR_LICENSE:","        \/\/ Scan did not complete because of a license issue","        \/\/ Check LicenseManager.state","        \/\/ ...","        break","    default:","        break","    }","}","","\/\/ Run measurement","device.measure(completion: callback)"],"syntax":"swift"},{"text":"Objective-C example","level":4,"type":"heading","anchor":"Objective-C-example"},{"code":["\/\/ Device instance","id<IDeviceCompat> _Nonnull device;","","\/\/ Define block to run on completion","void(^completion)(enum CommandStatus, MeasurementDictionary) =","^(enum CommandStatus status, MeasurementDictionary measurements) {","    switch (status) {","        case CommandStatusSUCCESS:","            \/\/ Successful operation","            \/\/ Handle measurement data here","            \/\/ ...","            break;","        case CommandStatusERROR_NOT_READY:","            \/\/ Did not complete because the device was busy","            \/\/ ...","            break;","        case CommandStatusERROR_NOT_SUPPORTED:","            \/\/ Did not complete because an unsupported scan mode was","            \/\/ specified","            \/\/ ...","            break;","        case CommandStatusERROR_LOW_POWER:","            \/\/ Did not complete because the battery level is too low","            \/\/ ...","            break;","        case CommandStatusERROR_TIMEOUT:","            \/\/ Timeout when waiting for result","            \/\/ ...","            break;","        case CommandStatusERROR_AMBIENT_LIGHT:","            \/\/ Did not complete because of ambient light leakage","            \/\/ ...","            break;","        case CommandStatusERROR_LICENSE:","            \/\/ Scan did not complete because of a license issue","            \/\/ Check LicenseManager.state","            \/\/ ...","            break;","        default:","            \/\/ Did not complete because of other internal error","            \/\/ ...","            break;","    }        ","};","","\/\/ Run measurement","[device measure:completion];"],"type":"codeListing","syntax":"objc"},{"level":3,"anchor":"Performing-in-field-profiling--calibration-with-reference-tile","type":"heading","text":"Performing in-field profiling \/ calibration with reference tile"},{"inlineContent":[{"type":"text","text":"Certain device types support in-field profiling or calibration using a provided reference tile. This process requires first decoding a string from the QR code attached to the reference tile and then directing the user to measure the same tile. Any necessary adjustments\/corrections are performed internally by the SDK and\/or the Nix device firmware itself."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The in-field calibration procedure may be performed as often or seldom as desired by the user. However, the property ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue"},{"type":"text","text":" flag indicates whether or not in-field calibration is recommended for the connected device."}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"This flag is updated after each regular measurement"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This flag is determined automatically by both elapsed time and ambient temperature change"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The property ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration"},{"type":"text","text":" indicates whether or not a connected device supports this feature. The expected result by device are shown below:"}]}]}],"type":"unorderedList"},{"rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device Type"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Supported"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Mini"}]}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}]],[[{"inlineContent":[{"type":"text","text":"Mini 2"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Mini 3","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}]],[[{"inlineContent":[{"type":"text","text":"Pro"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"Pro 2","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"QC","type":"text"}]}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"Spectro 2","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Spectro L"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}]]],"type":"table","alignments":["left","center"],"header":"row"},{"items":[{"content":[{"inlineContent":[{"text":"Decode the QR code printed on the device reference tile and interpret as a string. Do not parse this data further.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check if the parsed data is valid using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isTileStringValid(_:)"},{"type":"text","text":". If valid, continue to the next step."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Instruct the user to place the device on the reference tile.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Using the decoded tile string, run the in-field calibration routine using ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","type":"reference","isActive":true},{"type":"text","text":" and wait for closure \/ callback."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"This operation is asynchronous and returns immediately. While the operation is in progress, no other commands can be sent to the Nix device (wait for the callback)","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Every call to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","type":"reference","isActive":true},{"type":"text","text":" will result in a closure with either a success or error code."}],"type":"paragraph"}]}]}]}],"type":"orderedList"},{"type":"heading","text":"Swift example","level":4,"anchor":"Swift-example"},{"code":["\/\/ Device instance","var device: IDeviceCompat","","\/\/ String decoded from the reference tile","let tileString: String","","\/\/ Callback for field calibration","let callback: DeviceResultCallback = { status, measurements in","    switch status {","    case .SUCCESS:","        \/\/ Successful operation","        \/\/ ...","        break","    case .WARNING_TEMPERATURE:","        \/\/ Completed successfully, but ambient temperature is outside","        \/\/ of the recommended range","        \/\/ ...","        break","    case .ERROR_SCAN_DELTA:","        \/\/ Operation failed because the measured value of the reference","        \/\/ tile is too far from the expected value (high delta E)","        \/\/ ...","        break","    case .ERROR_NOT_READY:","        \/\/ Scan did not complete because the device was busy","        break","    case .ERROR_NOT_SUPPORTED:","        \/\/ Scan did not complete because this device does not support","        \/\/ this command","        \/\/ ...","        break","    case .ERROR_INVALID_ARGUMENT:","        \/\/ Scan did not complete because the tileString is invalid","        \/\/ ...","        break","    case .ERROR_LOW_POWER:","        \/\/ Scan did not complete because the battery level is too low","        \/\/ ...","        break","    case .ERROR_TIMEOUT:","        \/\/ Timeout when waiting for result","        \/\/ ...","        break","    case .ERROR_AMBIENT_LIGHT:","        \/\/ Scan did not complete because of ambient light leakage","        \/\/ ...","        break","    case .ERROR_LICENSE:","        \/\/ Scan did not complete because of a license issue","        \/\/ Check LicenseManager.state","        \/\/ ...","        break","    default:","        \/\/ Scan did not complete because of other internal error","        \/\/ ...","        break","    }","}","","\/\/ Run field calibration scan","device.runFieldCalibration(tileString: tileString, completion: callback)"],"type":"codeListing","syntax":"swift"},{"type":"heading","anchor":"Objective-C-example","text":"Objective-C example","level":4},{"type":"codeListing","code":["\/\/ Device instance","id<IDeviceCompat> _Nonnull device;","","\/\/ String decoded from the reference tile","NSString* tileString;","","\/\/ Define block to run on completion","void(^completion)(enum CommandStatus, MeasurementDictionary) =","^(enum CommandStatus status, MeasurementDictionary measurements) {","    switch (status) {","        case CommandStatusSUCCESS:","            \/\/ Successful operation","            \/\/ ...","            break;","        case CommandStatusWARNING_TEMPERATURE:","            \/\/ Completed successfully, but ambient temperature is","            \/\/ outside of the recommended range","            \/\/ ...","            break;","        case CommandStatusERROR_SCAN_DELTA:","            \/\/ Operation failed because the measured value of the","            \/\/ reference tile is too far from the expected value","            \/\/ (high delta E)","            \/\/ ...","            break;","        case CommandStatusERROR_NOT_READY:","            \/\/ Scan did not complete because the device was busy","            \/\/ ...","            break;","        case CommandStatusERROR_NOT_SUPPORTED:","            \/\/ Scan did not complete because this device does not","            \/\/ support this command","            \/\/ ...","            break;","        case CommandStatusERROR_INVALID_ARGUMENT:","            \/\/ Scan did not complete because the tileString is","            \/\/ invalid","            \/\/ ...","            break;","        case CommandStatusERROR_LOW_POWER:","            \/\/ Scan did not complete because the battery level is too","            \/\/ low","            \/\/ ...","            break;","        case CommandStatusERROR_TIMEOUT:","            \/\/ Timeout when waiting for result","            \/\/ ...","            break;","        case CommandStatusERROR_AMBIENT_LIGHT:","            \/\/ Scan did not complete because of ambient light leakage","            \/\/ ...","            break;","        case CommandStatusERROR_LICENSE:","            \/\/ Scan did not complete because of a license issue","            \/\/ Check LicenseManager.state","            \/\/ ...","            break;","        default:","            \/\/ Scan did not complete because of other internal error","            \/\/ ...","            break;","    }","};","","\/\/ Run field calibration scan","[device runFieldCalibration:tileString","                 completion:completion];"],"syntax":"objc"},{"anchor":"Other-device-options","text":"Other device options","type":"heading","level":3},{"inlineContent":[{"text":"Some Nix devices support certain ","type":"text"},{"type":"codeVoice","code":"boolean"},{"type":"text","text":" options. These options are set to be enabled by default (if supported) and do not usually need to be changed:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Applying temperature compensation"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current state: "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Is supported?: "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsTemperatureCompensation","type":"reference","isActive":true}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Applying in-field calibration","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Current state: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Is supported?: ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration","type":"reference"}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Using on-device haptic feedback"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current state: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Is supported?: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsHapticFeedback"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Using on-device RGB feedback","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Current state: "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Is supported?: ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsRgbFeedback","type":"reference"}]}]}]}]}]},{"type":"paragraph","inlineContent":[{"text":"A summary of device support is shown below, but can be checked at runtime (see notes above).","type":"text"}]},{"header":"row","rows":[[[{"inlineContent":[{"type":"text","text":"Device type"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Temp comp.","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Field cal.","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Haptic"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB"}]}]],[[{"inlineContent":[{"text":"Mini","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}]],[[{"inlineContent":[{"type":"text","text":"Mini 2"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Mini 3"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pro"}]}],[{"inlineContent":[{"type":"text","text":"☐"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}],[{"inlineContent":[{"text":"☐","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☐"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pro 2"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"inlineContent":[{"text":"☐","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}]],[[{"inlineContent":[{"text":"QC","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"☑"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"☐","type":"text"}]}]],[[{"inlineContent":[{"type":"text","text":"Spectro 2"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}],[{"type":"paragraph","inlineContent":[{"text":"☑","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Spectro L"}]}],[{"inlineContent":[{"type":"text","text":"☑"}],"type":"paragraph"}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"☑","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"☑"}]}]]],"alignments":["left","center","center","center","center"],"type":"table"},{"type":"paragraph","inlineContent":[{"text":"Changing any of these options may require communication with the device itself and is an asynchronous operation, with the status of the operation provided via a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true},{"type":"text","text":" closure."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"To enable or bypass temperature compensation, see "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setTemperatureCompensationEnabled(_:completion:)","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"To enable or bypass applying in-field calibration, see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setFieldCalibrationEnabled(_:completion:)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"To enable or disable haptic feedback, see "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setHapticFeedbackEnabled(_:completion:)","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"To enable or disable RGB feedback, see ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setRgbFeedbackEnabled(_:completion:)","type":"reference","isActive":true}]}]}]},{"text":"Other device properties","type":"heading","level":3,"anchor":"Other-device-properties"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" protocol defines other fixed properties that can be read once the device has connected and reached an idle state. These include, but are not limited to:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/extPowerState","isActive":true},{"type":"text","text":": status of external power connection \/ charging"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/batteryLevel","isActive":true,"type":"reference"},{"text":": current battery level, ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" otherwise","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/firmwareVersion","isActive":true,"type":"reference"},{"type":"text","text":": device firmware revision"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hardwareVersion"},{"text":": device hardware revision","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/softwareVersion"},{"type":"text","text":": device software revision"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","type":"reference","isActive":true},{"text":": device serial number","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/note"},{"text":": device allocation \/ production code","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesSpectral","isActive":true},{"text":": indicates whether or not this device provides spectral data","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesDensity"},{"type":"text","text":": indicates whether or not this device provides density data"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences","isActive":true},{"type":"text","text":": list of supported reference white values provided by the measurement data from this device"}]}]}],"type":"unorderedList"},{"name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesDensity","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesSpectral"},{"type":"text","text":" properties indicate whether or not the hardware device is capable of providing these data types. However, these measurements will only be available if these features are enabled by the current license. See "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license#Other-license-properties","type":"reference"},{"text":" for more details.","type":"text"}],"type":"paragraph"}],"type":"aside"},{"text":"Next Steps","anchor":"Next-Steps","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","isActive":true,"type":"reference"}]}]}]}]}],"seeAlsoSections":[{"anchor":"Getting-Started","title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"generated":true}],"abstract":[{"text":"Take measurements, set device options, and query device properties","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setHapticFeedbackEnabled(_:completion:)":{"abstract":[{"type":"text","text":"Set the value for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled"},{"type":"text","text":". This method is asynchronous and will return immediately."}],"required":true,"navigatorTitle":[{"text":"setHapticFeedbackEnabled:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHapticFeedbackEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"setHapticFeedbackEnabled(_:completion:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setHapticFeedbackEnabled(_:completion:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/sethapticfeedbackenabled(_:completion:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportedReferences":{"abstract":[{"text":"List of supported reference white points for the colorimetry data available from the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"type":"text","text":" results provided by this device (set of "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" containing "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","isActive":true},{"type":"text","text":" values)"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedReferences"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":">","kind":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportedreferences","title":"supportedReferences","required":true,"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences","navigatorTitle":[{"text":"supportedReferences","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","title":"Example Applications","url":"\/documentation\/nixuniversalsdk\/example-apps","kind":"article","type":"topic","abstract":[{"text":"Explore source code for demo iOS and macOS applications","type":"text"}],"role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M0":{"navigatorTitle":[{"text":"ScanModeM0","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"M0 conditions (ISO 13655)"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"M0","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/m0","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","role":"symbol","title":"ScanMode.M0"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/isTileStringValid(_:)":{"type":"topic","title":"isTileStringValid(_:)","navigatorTitle":[{"text":"isTileStringValid:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isTileStringValid","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isTileStringValid(_:)","required":true,"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/istilestringvalid(_:)","kind":"symbol","abstract":[{"type":"text","text":"Check if the formatting of the reference tile string data matches the expected format for this device, or "},{"code":"false","type":"codeVoice"},{"type":"text","text":" if the device does not support this feature."}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"abstract":[{"text":"Review the changes made in this version of the library","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/release-notes","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","type":"topic","role":"article","kind":"article","title":"Release Notes"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/hardwareVersion":{"kind":"symbol","type":"topic","abstract":[{"text":"Hardware version of this device. The value is valid only after a connection has successfully been opened.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardwareVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion","text":"DeviceVersion"}],"navigatorTitle":[{"text":"hardwareVersion","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/hardwareversion","title":"hardwareVersion","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hardwareVersion"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/softwareVersion":{"abstract":[{"type":"text","text":"Software version of this device. The value is valid only after a connection has successfully been opened."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"softwareVersion"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"softwareVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion","text":"DeviceVersion"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/softwareVersion","title":"softwareVersion","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/softwareversion","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/serialNumber":{"type":"topic","title":"serialNumber","navigatorTitle":[{"kind":"identifier","text":"serialNumber"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"serialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","required":true,"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/serialnumber","kind":"symbol","abstract":[{"type":"text","text":"Serial number for this device. The value is valid only after a connection has successfully been opened."}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license#Other-license-properties":{"title":"Other license properties","url":"\/documentation\/nixuniversalsdk\/activating-license#Other-license-properties","abstract":[],"type":"topic","kind":"section","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license#Other-license-properties"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/temperatureCompensationEnabled":{"abstract":[{"type":"text","text":"Flag to indicate if ambient temperature compensation \/ correction is applied ("},{"type":"codeVoice","code":"true"},{"type":"text","text":") or bypassed ("},{"type":"codeVoice","code":"false"},{"text":") when evaluating the final calibrated measurement. Value is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" by default if supported by the device. It is recommended to leave this set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if supported."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"temperatureCompensationEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/temperaturecompensationenabled","title":"temperatureCompensationEnabled","type":"topic","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"temperatureCompensationEnabled"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(completion:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Run a measurement for all supported scan modes. This method is asynchronous and will return immediately.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"measure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"measure:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(completion:)","title":"measure(completion:)","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsTemperatureCompensation":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportstemperaturecompensation","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"supportsTemperatureCompensation","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Flag to indicate if this device supports automatic temperature compensation to correct for small changes in ambient temperature.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsTemperatureCompensation","title":"supportsTemperatureCompensation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportsTemperatureCompensation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/fieldCalibrationDue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldCalibrationDue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"fieldCalibrationDue","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/fieldcalibrationdue","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fieldCalibrationDue"}],"kind":"symbol","abstract":[{"text":"Flag to indicate if in-field calibration is recommended for this device at this time (if supported). This value is only valid after opening a connection and is a function of both time and ambient temperature. This value also updates each time a measurement is completed.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(modes:completion:)-18cni":{"abstract":[{"type":"text","text":"Run a measurement in the specified scan modes. If any unsupported modes are selected, the measurement will fail with status code "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED"},{"type":"text","text":". This method is asynchronous and will return immediately."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"measureWithModes:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"measure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":">, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","title":"measure(modes:completion:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(modes:completion:)-18cni","role":"symbol","defaultImplementations":1},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus":{"title":"CommandStatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommandStatus"}],"navigatorTitle":[{"text":"CommandStatus","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/commandstatus","kind":"symbol","abstract":[{"text":"Enum describing the possible status of commands executed by the Nix device, as provided in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setTemperatureCompensationEnabled(_:completion:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setTemperatureCompensationEnabled(_:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTemperatureCompensationEnabled"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setTemperatureCompensationEnabled(_:completion:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/settemperaturecompensationenabled(_:completion:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTemperatureCompensationEnabled:completion:"}],"kind":"symbol","abstract":[{"text":"Set the value for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled","isActive":true},{"text":". This method is asynchronous and will return immediately.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/extPowerState":{"title":"extPowerState","role":"symbol","navigatorTitle":[{"text":"extPowerState","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/extpowerstate","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extPowerState"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/extPowerState","type":"topic","abstract":[{"type":"text","text":"External power connection state for this device. The value is valid only after a connection has successfully been opened."}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/rgbFeedbackEnabled":{"kind":"symbol","type":"topic","abstract":[{"text":"Flag to indicate if device RGB feedback is enabled.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgbFeedbackEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"rgbFeedbackEnabled","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/rgbfeedbackenabled","title":"rgbFeedbackEnabled","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","title":"Discovering and Connecting to Nix Devices","kind":"article","type":"topic","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","abstract":[{"text":"Use the device scanner to discover Nix devices and open a connection","type":"text"}],"role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsRgbFeedback":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsRgbFeedback","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supportsRgbFeedback","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"supportsRgbFeedback","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportsrgbfeedback","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsRgbFeedback"}],"kind":"symbol","abstract":[{"text":"Flag to indicate if the device supports built-in RGB feedback.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M2":{"navigatorTitle":[{"text":"ScanModeM2","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"M2 conditions (ISO 13655)"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"M2"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/m2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2","role":"symbol","title":"ScanMode.M2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/providesDensity":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/providesdensity","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"providesDensity","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Flag to indicate if this device type provides density information in its supplied ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference"},{"type":"text","text":" results."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesDensity","title":"providesDensity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providesDensity"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"abstract":[{"text":"Reconstructs a ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"code":"nil","type":"codeVoice"},{"text":" if the data is invalid.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fromRaw","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}],"url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","type":"topic","title":"fromRaw(_:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"role":"article","abstract":[{"text":"Query measurement values including colorimetry, spectral reflectance, and density","type":"text"}],"kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","type":"topic","title":"Handling Measurement Data","url":"\/documentation\/nixuniversalsdk\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportedModes":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportedmodes","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedModes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"supportedModes","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes","type":"topic","role":"symbol","title":"supportedModes","abstract":[{"type":"text","text":"List of scan modes that are supported by this device (set of "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" containing "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true,"type":"reference"},{"type":"text","text":" values). The list is valid only after a connection has successfully been opened."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/fieldCalibrationEnabled":{"abstract":[{"text":"Flag to indicate if in-field calibration results are applied (","type":"text"},{"type":"codeVoice","code":"true"},{"text":") or bypassed (","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":") when evaluating the final calibrated measurement result. Value is "},{"type":"codeVoice","code":"true"},{"type":"text","text":" by default if supported by the device. It is recommended to leave this set to "},{"type":"codeVoice","code":"true"},{"text":" if supported.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldCalibrationEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/fieldcalibrationenabled","title":"fieldCalibrationEnabled","required":true,"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled","navigatorTitle":[{"kind":"identifier","text":"fieldCalibrationEnabled"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescanner","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":".","type":"text"}],"title":"IDeviceCompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite","title":"ReferenceWhite","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","role":"symbol","kind":"symbol","abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"type":"topic","kind":"symbol","abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}],"navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","title":"IMeasurementData","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"abstract":[{"text":"Review an example project which provides a C\/C++ interface for macOS applications","type":"text"}],"kind":"article","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","title":"Wrapper for Usage in C\/C++","url":"\/documentation\/nixuniversalsdk\/wrapper","role":"article"},"#handling-measurement-data":{"url":"#handling-measurement-data","identifier":"#handling-measurement-data","title":"Handling measurement data","titleInlineContent":[{"text":"Handling measurement data","type":"text"}],"type":"link"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/providesSpectral":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"providesSpectral","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/providesspectral","navigatorTitle":[{"text":"providesSpectral","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Flag to indicate if this device type provides spectral information in its supplied ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","isActive":true,"type":"reference"},{"type":"text","text":" results."}],"required":true,"type":"topic","title":"providesSpectral","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesSpectral"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/note":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Factory note for this device, containing allocation code. The value is valid only after a connection has successfully been opened."}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"note"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"note"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/note","title":"note","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/note"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setRgbFeedbackEnabled(_:completion:)":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setRgbFeedbackEnabled:completion:"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/setrgbfeedbackenabled(_:completion:)","abstract":[{"type":"text","text":"Set the value for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled"},{"type":"text","text":". This method is asynchronous and will return immediately."}],"title":"setRgbFeedbackEnabled(_:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setRgbFeedbackEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setRgbFeedbackEnabled(_:completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M1":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M1","url":"\/documentation\/nixuniversalsdk\/scanmode\/m1","type":"topic","abstract":[{"type":"text","text":"M1 conditions (ISO 13655)"}],"navigatorTitle":[{"text":"ScanModeM1","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"M1","kind":"identifier"}],"title":"ScanMode.M1","kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setFieldCalibrationEnabled(_:completion:)":{"type":"topic","title":"setFieldCalibrationEnabled(_:completion:)","navigatorTitle":[{"text":"setFieldCalibrationEnabled:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFieldCalibrationEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setFieldCalibrationEnabled(_:completion:)","required":true,"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/setfieldcalibrationenabled(_:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Set the value for "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled","isActive":true},{"type":"text","text":". This method is asynchronous and will return immediately."}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus/ERROR_NOT_SUPPORTED":{"type":"topic","title":"CommandStatus.ERROR_NOT_SUPPORTED","navigatorTitle":[{"text":"CommandStatusERROR_NOT_SUPPORTED","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_NOT_SUPPORTED","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED","url":"\/documentation\/nixuniversalsdk\/commandstatus\/error_not_supported","kind":"symbol","abstract":[{"text":"Status code indicating that the command was aborted because the it was not supported by the Nix device instance.","type":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/runFieldCalibration(tileString:completion:)":{"abstract":[{"type":"text","text":"Start field calibration using provided reference tile, if supported. Upon executing this command, the scan of the reference tile will begin immediately. The user MUST be prompted to place the device onto the reference tile BEFORE this method is executed. This method is asynchronous and will return immediately."},{"type":"text","text":" "},{"text":"This command requires data from the reference tile QR code. As the format varies between different device types, the string data should be provided exactly as decoded from the QR code.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","navigatorTitle":[{"text":"runFieldCalibration:completion:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/runfieldcalibration(tilestring:completion:)","kind":"symbol","required":true,"title":"runFieldCalibration(tileString:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runFieldCalibration","kind":"identifier"},{"kind":"text","text":"("},{"text":"tileString","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/isModeSupported(_:)":{"abstract":[{"type":"text","text":"Helper to check if a particular scan mode is supported by this device (i.e. - checks if the mode is present in the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes","type":"reference"},{"type":"text","text":" list). This value is valid only after a connection has successfully been opened."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"isModeSupported:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isModeSupported"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","title":"isModeSupported(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isModeSupported(_:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/ismodesupported(_:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsFieldCalibration":{"abstract":[{"type":"text","text":"Flag to indicate if this device supports in-field calibration using the provided reference tile."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"supportsFieldCalibration"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"supportsFieldCalibration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration","title":"supportsFieldCalibration","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportsfieldcalibration","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsHapticFeedback":{"required":true,"role":"symbol","navigatorTitle":[{"text":"supportsHapticFeedback","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportsHapticFeedback","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[{"type":"text","text":"Flag to indicate if the device supports built-in haptic feedback."}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportshapticfeedback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsHapticFeedback","title":"supportsHapticFeedback"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/firmwareVersion":{"abstract":[{"text":"Firmware version of this device. The value is valid only after a connection has successfully been opened.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"firmwareVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DeviceVersion","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/firmwareversion","title":"firmwareVersion","required":true,"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/firmwareVersion","navigatorTitle":[{"text":"firmwareVersion","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus/SUCCESS":{"abstract":[{"type":"text","text":"Status code indicating that the command completed successfully."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/SUCCESS","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SUCCESS"}],"navigatorTitle":[{"kind":"identifier","text":"CommandStatusSUCCESS"}],"title":"CommandStatus.SUCCESS","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/commandstatus\/success"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"role":"article","abstract":[{"text":"Enable Nix device functions with your license code","type":"text"}],"kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","type":"topic","title":"Activating the SDK License","url":"\/documentation\/nixuniversalsdk\/activating-license"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"}],"title":"ScanMode","navigatorTitle":[{"kind":"identifier","text":"ScanMode"}],"url":"\/documentation\/nixuniversalsdk\/scanmode","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/batteryLevel":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/batterylevel","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"batteryLevel"}],"kind":"symbol","abstract":[{"type":"text","text":"Current battery level for this device (0 - 100), or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if not available. "},{"code":"NSNumber","type":"codeVoice"},{"text":" contains an integer value. The value is valid only after a connection has successfully been opened.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/batteryLevel","title":"batteryLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"batteryLevel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/hapticFeedbackEnabled":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/hapticfeedbackenabled","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"hapticFeedbackEnabled","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Flag to indicate if device haptic feedback is enabled.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled","title":"hapticFeedbackEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hapticFeedbackEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"title":"DeviceResultCallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"DeviceResultCallback","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"text":" instance.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"role":"article","abstract":[{"text":"Add the library bundle to your project and declare peripheral uses","type":"text"}],"kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","type":"topic","title":"Adding to Your Xcode Project","url":"\/documentation\/nixuniversalsdk\/add-to-xcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"generated":true,"anchor":"Getting-Started"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setHapticFeedbackEnabled(_:completion:)\/title","value":"setHapticFeedbackEnabled:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"setHapticFeedbackEnabled:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setHapticFeedbackEnabled(_:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedReferences\/title","value":"supportedReferences"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedReferences\/fragments","value":[{"text":"supportedReferences","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M0\/title","op":"replace","value":"ScanModeM0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M0\/fragments","op":"replace","value":[{"text":"ScanModeM0","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isTileStringValid(_:)\/title","value":"isTileStringValid:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isTileStringValid:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isTileStringValid(_:)\/fragments"},{"value":"hardwareVersion","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hardwareVersion\/title"},{"value":[{"kind":"identifier","text":"hardwareVersion"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hardwareVersion\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1softwareVersion\/title","value":"softwareVersion"},{"value":[{"text":"softwareVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1softwareVersion\/fragments","op":"replace"},{"op":"replace","value":"serialNumber","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1serialNumber\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1serialNumber\/fragments","value":[{"text":"serialNumber","kind":"identifier"}],"op":"replace"},{"value":"temperatureCompensationEnabled","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1temperatureCompensationEnabled\/title"},{"op":"replace","value":[{"text":"temperatureCompensationEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1temperatureCompensationEnabled\/fragments"},{"op":"replace","value":"measure:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(completion:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"measure:","kind":"identifier"}]},{"op":"replace","value":"supportsTemperatureCompensation","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsTemperatureCompensation\/title"},{"value":[{"kind":"identifier","text":"supportsTemperatureCompensation"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsTemperatureCompensation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationDue\/title","value":"fieldCalibrationDue","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationDue\/fragments","value":[{"kind":"identifier","text":"fieldCalibrationDue"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(modes:completion:)-18cni\/title","value":"measureWithModes:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"measureWithModes:completion:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(modes:completion:)-18cni\/fragments","op":"replace"},{"op":"replace","value":"CommandStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/title"},{"value":[{"kind":"identifier","text":"CommandStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/fragments"},{"value":[{"text":"CommandStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/navigatorTitle","op":"replace"},{"op":"replace","value":"setTemperatureCompensationEnabled:completion:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setTemperatureCompensationEnabled(_:completion:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setTemperatureCompensationEnabled(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTemperatureCompensationEnabled:completion:"}],"op":"replace"},{"op":"replace","value":"extPowerState","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1extPowerState\/title"},{"value":[{"text":"extPowerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1extPowerState\/fragments"},{"op":"replace","value":"rgbFeedbackEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rgbFeedbackEnabled\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rgbFeedbackEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"rgbFeedbackEnabled"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsRgbFeedback\/title","value":"supportsRgbFeedback","op":"replace"},{"op":"replace","value":[{"text":"supportsRgbFeedback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsRgbFeedback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M2\/title","value":"ScanModeM2"},{"op":"replace","value":[{"text":"ScanModeM2","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M2\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesDensity\/title","op":"replace","value":"providesDensity"},{"op":"replace","value":[{"kind":"identifier","text":"providesDensity"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesDensity\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedModes\/title","value":"supportedModes"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedModes\/fragments","value":[{"kind":"identifier","text":"supportedModes"}],"op":"replace"},{"op":"replace","value":"fieldCalibrationEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationEnabled\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationEnabled\/fragments","value":[{"kind":"identifier","text":"fieldCalibrationEnabled"}],"op":"replace"},{"value":"DeviceScanner","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title"},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle"},{"op":"replace","value":"IDeviceCompat","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"value":"ReferenceWhite","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","op":"replace","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"value":[{"text":"ReferenceWhite","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","value":"IMeasurementData","op":"replace"},{"value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments"},{"value":[{"kind":"identifier","text":"IMeasurementData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesSpectral\/title","value":"providesSpectral","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesSpectral\/fragments","value":[{"kind":"identifier","text":"providesSpectral"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1note\/title","value":"note","op":"replace"},{"op":"replace","value":[{"text":"note","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1note\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setRgbFeedbackEnabled(_:completion:)\/title","value":"setRgbFeedbackEnabled:completion:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setRgbFeedbackEnabled(_:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setRgbFeedbackEnabled:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M1\/title","value":"ScanModeM1"},{"value":[{"kind":"identifier","text":"ScanModeM1"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M1\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setFieldCalibrationEnabled(_:completion:)\/title","value":"setFieldCalibrationEnabled:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setFieldCalibrationEnabled(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFieldCalibrationEnabled:completion:","kind":"identifier"}]},{"value":"CommandStatusERROR_NOT_SUPPORTED","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_NOT_SUPPORTED\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_NOT_SUPPORTED\/fragments","op":"replace","value":[{"kind":"identifier","text":"CommandStatusERROR_NOT_SUPPORTED"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/title","value":"runFieldCalibration:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runFieldCalibration:completion:"}]},{"op":"replace","value":"isModeSupported:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isModeSupported(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isModeSupported:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isModeSupported(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsFieldCalibration\/title","op":"replace","value":"supportsFieldCalibration"},{"value":[{"kind":"identifier","text":"supportsFieldCalibration"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsFieldCalibration\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsHapticFeedback\/title","value":"supportsHapticFeedback","op":"replace"},{"value":[{"text":"supportsHapticFeedback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsHapticFeedback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1firmwareVersion\/title","value":"firmwareVersion","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1firmwareVersion\/fragments","value":[{"text":"firmwareVersion","kind":"identifier"}]},{"value":"CommandStatusSUCCESS","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1SUCCESS\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1SUCCESS\/fragments","op":"replace","value":[{"kind":"identifier","text":"CommandStatusSUCCESS"}]},{"value":"ScanMode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","op":"replace"},{"value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments"},{"op":"replace","value":[{"text":"ScanMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle"},{"value":"batteryLevel","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1batteryLevel\/title"},{"value":[{"kind":"identifier","text":"batteryLevel"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1batteryLevel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hapticFeedbackEnabled\/title","value":"hapticFeedbackEnabled"},{"value":[{"kind":"identifier","text":"hapticFeedbackEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hapticFeedbackEnabled\/fragments"}]}]}