{"metadata":{"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion","title":"DeviceVersion","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceVersion"}],"navigatorTitle":[{"text":"DeviceVersion","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/init(string:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/major","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/minor","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/patch","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/prefix","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/string"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"abstract":[{"text":"Class to describe Nix device revisions","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/deviceversion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/deviceversion"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceVersion"}],"platforms":["macOS"]}]}],"references":{"doc://com.nixsensor.universalsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion/major":{"type":"topic","role":"symbol","title":"major","abstract":[{"text":"Major revision number","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/major","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"major","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"major","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/deviceversion\/major"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion","abstract":[{"type":"text","text":"Class to describe Nix device revisions"}],"url":"\/documentation\/nixuniversalsdk\/deviceversion","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceVersion","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceVersion"}],"title":"DeviceVersion","kind":"symbol"},"doc://com.nixsensor.universalsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion/string":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/string","title":"string","abstract":[{"text":"String value for this version","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"string","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"text":"string","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/deviceversion\/string"},"doc://com.nixsensor.universalsdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion/prefix":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/prefix","title":"prefix","abstract":[{"text":"Single character prefix for this version. Expected values are ‘F’ for  firmware version, ‘H’ for hardware version, ‘S’ for software version.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefix"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"prefix","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/deviceversion\/prefix","kind":"symbol"},"doc://com.nixsensor.universalsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion/init(string:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constructs a "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion","isActive":true,"type":"reference"},{"text":" object from the string value received from the Nix device (for example, ‘H1.0.0’), parsing the major, minor, and patch versions to numeric values.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/init(string:)","url":"\/documentation\/nixuniversalsdk\/deviceversion\/init(string:)","kind":"symbol","title":"init(string:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion/patch":{"title":"patch","abstract":[{"text":"Patch revision number","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"patch","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/patch","kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/deviceversion\/patch","type":"topic"},"doc://com.nixsensor.universalsdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion/minor":{"url":"\/documentation\/nixuniversalsdk\/deviceversion\/minor","abstract":[{"type":"text","text":"Minor revision number"}],"role":"symbol","navigatorTitle":[{"text":"minor","kind":"identifier"}],"type":"topic","title":"minor","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/minor","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DeviceVersion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceVersion"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceVersion"}]},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/major","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/minor","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/patch","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/prefix","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion\/string"],"anchor":"Instance-Properties"}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceVersion","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1major\/title","value":"major","op":"replace"},{"value":[{"text":"major","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1major\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion\/title","value":"DeviceVersion"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion\/fragments","value":[{"kind":"identifier","text":"DeviceVersion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceVersion"}],"op":"replace"},{"value":"string","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1string\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1string\/fragments","value":[{"kind":"identifier","text":"string"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1prefix\/title","value":"prefix"},{"value":[{"text":"prefix","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1prefix\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1patch\/title","op":"replace","value":"patch"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1patch\/fragments","value":[{"kind":"identifier","text":"patch"}]},{"value":"minor","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1minor\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion~1minor\/fragments","value":[{"text":"minor","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}