{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/PRO","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/PRO2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/QC","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTROL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fullName","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/shortName"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/isFeatureSupported(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromAdvertisingName(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromUint8(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromVid(_:pid:)"]},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"},"metadata":{"title":"DeviceType","roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@NixUniversalSDK@E@DeviceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceType","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceType"}]}]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"kind":"relationships"}],"sections":[],"abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicetype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/QC":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/QC","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QC"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/qc","navigatorTitle":[{"text":"DeviceTypeQC","kind":"identifier"}],"abstract":[{"type":"text","text":"Type for Nix QC colorimeter"}],"title":"DeviceType.QC","type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fullName":{"abstract":[{"type":"text","text":"Full name for device type, as advertised on Bluetooth"}],"kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/fullname","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fullName","title":"fullName","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fromAdvertisingName(_:)":{"kind":"symbol","title":"fromAdvertisingName(_:)","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromAdvertisingName(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromAdvertisingName"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"text":"DeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicetype\/fromadvertisingname(_:)","abstract":[{"text":"Helper method to find the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true,"type":"reference"},{"type":"text","text":" enum that corresponds to the name found during device advertisement. If an unknown name is provided, "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","type":"reference","isActive":true},{"type":"text","text":" is returned."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI3":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"MINI3","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","abstract":[{"type":"text","text":"Type for Nix Mini 3 colorimeter"}],"title":"DeviceType.MINI3","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/mini3","navigatorTitle":[{"text":"DeviceTypeMINI3","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/PRO":{"navigatorTitle":[{"kind":"identifier","text":"DeviceTypePRO"}],"abstract":[{"type":"text","text":"Type for Nix Pro colorimeter"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PRO"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/pro","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/PRO","role":"symbol","title":"DeviceType.PRO"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"url":"\/documentation\/nixuniversalsdk\/devicetype","title":"DeviceType","navigatorTitle":[{"text":"DeviceType","kind":"identifier"}],"abstract":[{"text":"Enum to describe the supported Nix device types","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fromVid(_:pid:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromVid(_:pid:)","abstract":[{"type":"text","text":"Helper method to find the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","type":"reference"},{"type":"text","text":" enum that corresponds to a given USB vendor ID and product ID. If an unknown combination is provided "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","type":"reference"},{"type":"text","text":" is returned."}],"title":"fromVid(_:pid:)","url":"\/documentation\/nixuniversalsdk\/devicetype\/fromvid(_:pid:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromVid"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pid","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/mini","title":"DeviceType.MINI","abstract":[{"type":"text","text":"Type for Nix Mini colorimeter"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeMINI"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"MINI","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/SPECTRO2":{"kind":"symbol","abstract":[{"type":"text","text":"Type for Nix Spectro 2 spectrophotometer"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/spectro2","type":"topic","title":"DeviceType.SPECTRO2","navigatorTitle":[{"text":"DeviceTypeSPECTRO2","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SPECTRO2"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/PRO2":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PRO2"}],"type":"topic","kind":"symbol","abstract":[{"text":"Type for Nix Pro 2 colorimeter","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/PRO2","title":"DeviceType.PRO2","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/pro2","navigatorTitle":[{"text":"DeviceTypePRO2","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/RawRepresentable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/RawRepresentable-Implementations","url":"\/documentation\/nixuniversalsdk\/devicetype\/rawrepresentable-implementations","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/fromUint8(_:)":{"abstract":[{"text":"Helper method to find the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","type":"reference"},{"text":" enum that corresponds to a byte value. If an unknown byte value is provided ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN"},{"type":"text","text":" is returned."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/fromUint8(_:)","title":"fromUint8(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/fromuint8(_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromUint8"},{"text":"(","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier","text":"DeviceType"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/UNKNOWN":{"kind":"symbol","abstract":[{"type":"text","text":"Unknown \/ other device type"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN","type":"topic","title":"DeviceType.UNKNOWN","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UNKNOWN","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceTypeUNKNOWN","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicetype\/unknown"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/Equatable-Implementations":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/Equatable-Implementations","role":"collectionGroup","kind":"article","abstract":[],"url":"\/documentation\/nixuniversalsdk\/devicetype\/equatable-implementations","type":"topic","title":"Equatable Implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/init(rawValue:)":{"abstract":[],"url":"\/documentation\/nixuniversalsdk\/devicetype\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/init(rawValue:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/SPECTROL":{"url":"\/documentation\/nixuniversalsdk\/devicetype\/spectrol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"SPECTROL","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeSPECTROL"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTROL","type":"topic","role":"symbol","title":"DeviceType.SPECTROL","abstract":[{"type":"text","text":"Type for Nix Spectro L spectrophometer"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/shortName":{"url":"\/documentation\/nixuniversalsdk\/devicetype\/shortname","title":"shortName","type":"topic","abstract":[{"type":"text","text":"Short name for the device type"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/shortName","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shortName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI2":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI2","navigatorTitle":[{"kind":"identifier","text":"DeviceTypeMINI2"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"MINI2","kind":"identifier"}],"type":"topic","title":"DeviceType.MINI2","url":"\/documentation\/nixuniversalsdk\/devicetype\/mini2","role":"symbol","abstract":[{"text":"Type for Nix Mini 2 colorimeter","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/isFeatureSupported(_:)":{"url":"\/documentation\/nixuniversalsdk\/devicetype\/isfeaturesupported(_:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/isFeatureSupported(_:)","role":"symbol","abstract":[{"type":"text","text":"Defines if a particular feature is supported by a certain device type"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFeatureSupported"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"LicenseFeature","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"isFeatureSupported(_:)"},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DeviceType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeviceType"}]},{"value":[{"text":"DeviceType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/PRO","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/PRO2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/QC","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTROL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/UNKNOWN"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1QC\/title","value":"DeviceTypeQC"},{"op":"replace","value":[{"text":"DeviceTypeQC","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1QC\/fragments"},{"op":"replace","value":"DeviceTypeMINI3","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/fragments","value":[{"text":"DeviceTypeMINI3","kind":"identifier"}]},{"value":"DeviceTypePRO","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1PRO\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1PRO\/fragments","value":[{"text":"DeviceTypePRO","kind":"identifier"}],"op":"replace"},{"value":"DeviceType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","value":[{"text":"DeviceType","kind":"identifier"}]},{"op":"replace","value":"DeviceTypeMINI","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI\/fragments","value":[{"kind":"identifier","text":"DeviceTypeMINI"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/title","value":"DeviceTypeSPECTRO2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/fragments","value":[{"text":"DeviceTypeSPECTRO2","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1PRO2\/title","value":"DeviceTypePRO2"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceTypePRO2"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1PRO2\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/title","op":"replace","value":"DeviceTypeUNKNOWN"},{"value":[{"kind":"identifier","text":"DeviceTypeUNKNOWN"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1UNKNOWN\/fragments","op":"replace"},{"op":"replace","value":"DeviceTypeSPECTROL","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTROL\/title"},{"value":[{"text":"DeviceTypeSPECTROL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTROL\/fragments","op":"replace"},{"op":"replace","value":"DeviceTypeMINI2","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI2\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI2\/fragments","op":"replace","value":[{"text":"DeviceTypeMINI2","kind":"identifier"}]}]}]}