{"abstract":[{"type":"text","text":"Nullable instance of an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true,"type":"reference"},{"text":" object","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicescannernullable"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceScanner","text":"id<IDeviceScanner>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScannerNullable"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNullable"},"metadata":{"title":"DeviceScannerNullable","role":"symbol","fragments":[{"kind":"identifier","text":"DeviceScannerNullable"}],"navigatorTitle":[{"text":"DeviceScannerNullable","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Type Alias","externalID":"c:TypeAliases.h@T@DeviceScannerNullable","symbolKind":"typealias"},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"url":"\/documentation\/nixuniversalsdk\/idevicescanner","role":"symbol","abstract":[{"type":"text","text":"Protocol implemented by the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceScanner","kind":"identifier"}],"title":"IDeviceScanner","navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerNullable":{"title":"DeviceScannerNullable","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Nullable instance of an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"},{"text":" object","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/devicescannernullable","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNullable","fragments":[{"text":"DeviceScannerNullable","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"IDeviceScanner","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","value":[{"kind":"identifier","text":"IDeviceScanner"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","value":[{"text":"IDeviceScanner","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}