{"primaryContentSections":[{"content":[{"type":"heading","text":"Build errors and compatibility","anchor":"Build-errors-and-compatibility","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Can I test Nix device functionality using iOS simulators?"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"No, iOS simulators do not bridge Bluetooth LE from the host PC."}]}]},{"content":[{"inlineContent":[{"text":"Applications that use the ","type":"text"},{"code":"NixUniversalSDK","type":"codeVoice"},{"text":" will run on iOS simulators, but Nix device operations will be unavailable.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"In an iOS simulator, the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":" will initialize with ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","type":"reference","isActive":true},{"text":" state.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"You can continue to use iOS simulators for general app development and testing, but real iOS devices are required to test Nix device integration on iOS apps."}],"type":"paragraph"}]}]}]}]}]},{"content":[{"inlineContent":[{"text":"Can I test my iOS app natively on Mac with Apple silicon?","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Yes, Bluetooth and Nix functions are available natively when running iOS applications on your Mac with Apple silicon."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If you select ‘My Mac’ as a build target in Xcode, you can run and debug your iOS application with full Nix support.","type":"text"}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"My macOS application is not written in Swift or Objective-C. Is there a C\/C++ interface available?"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"It is possible to build a wrapper for the "},{"type":"codeVoice","code":"NixUniversalSDK"},{"type":"text","text":" which provides a C\/C++ interface. A full-featured project is provided in the examples to accomplish this exact purpose. Refer to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"},{"text":" for additional details.","type":"text"}]}]}]}]}],"type":"orderedList"},{"text":"License and activation issues","type":"heading","anchor":"License-and-activation-issues","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"type":"text","text":" cannot start and is indicating an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE","type":"reference","isActive":true},{"type":"text","text":" state. How do I resolve this?"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check the license manager state via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state"},{"type":"text","text":". This will be one of the entries in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState"},{"type":"text","text":" enum which will describe the problem."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Activate the license manager by calling ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)"},{"type":"text","text":" and ensure that its state is "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","type":"reference"},{"type":"text","text":" before initializing the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"},{"type":"text","text":"."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"My license is active, but Nix devices immediately disconnect with an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED"},{"text":" status.","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Depending on license conditions, the NixUniversalSDK may require periodic internet access to check if a device is authorized by the active license."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set by the license, internet connections are required:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"On the first connection of a particular device serial number.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"At least once per 30 day period thereafter.","type":"text"}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"If you are behind a firewall, white-list access to "},{"type":"reference","isActive":true,"identifier":"https:\/\/nixsensor.com\/nixserial"},{"type":"text","text":" to ensure that the server can be reached."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If your license includes provisions for private-labelled devices, these devices may be exempted from this requirement.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Please contact us via e-mail at ","type":"text"},{"identifier":"mailto:sdk@nixsensor.com","type":"reference","isActive":true},{"text":" if alternate license arrangements are required.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"type":"heading","level":2,"anchor":"User-permissions","text":"User permissions"},{"type":"heading","text":"Device discovery and connection","level":2,"anchor":"Device-discovery-and-connection"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Can a single Nix device be connected to more than one application at a time?","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"No, a Nix device can only communicate with a single application running on a single host at any given time.","type":"text"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Can I open a connection to multiple Nix devices simultaneously inside the same application?","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"No, the "},{"type":"codeVoice","code":"NixUniversalSDK"},{"type":"text","text":" is configured to work with a single device at a time."}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"How long should I run the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":" when discovering nearby devices?","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When discovering Nix devices over Bluetooth, the default 20-second search period is recommended."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"If you wish to use a shorter period, at least 10 seconds is highly suggested."}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"text":"Nix devices advertise their presence once per second, but some advertisement packets may be missed due to other Bluetooth traffic. The default 20-second period allows multiple advertisement to be reliably received.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Can I connect to a Nix device attached to my iPhone or iPad with a USB cable instead of Bluetooth?","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"No, iOS apps only support Bluetooth based communication with Nix devices.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"USB communication is only supported on macOS.","type":"text"}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The device scanner found more than one device. How should I handle multiple nearby devices?"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"It is best practice to show a list of nearby devices in your UI sorted by signal strength ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi"},{"type":"text","text":"). Including the device "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id"},{"type":"text","text":" also helps the user distinguish between devices."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Note that RSSI is a negative number and ranges from 0 (strongest) to -128 (weakest). Show the strongest signal devices at the top of the list.","type":"text"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You should prompt your user to bring their Nix device closer to their phone, tablet, or computer when searching over Bluetooth. This will increase the signal strength of their device relative to other nearby Nix devices."}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"How should signal strength (RSSI) by used?"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"RSSI indicates relative signal strength and ranges from 0 (strongest) to -128 (weakest). When sorting a list of devices by RSSI, sort in descending order (i.e. - show the values closer to 0 at the top of the list).","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rather than displaying the RSSI value directly, consider showing it with signal strength icons, as shown in the demo application."},{"type":"image","identifier":"ios_rssi_example.png"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"macOS only: USB devices will always report an RSSI of ‘0’. You can and should distinguish between USB and Bluetooth devices in any displayed device list. The "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType","type":"reference"},{"type":"text","text":" property allows you to distinguish between the two."}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"My USB attached Nix device is not recognized or listed by the SDK.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"USB communication is only available on macOS. Direct cabled connections are "},{"inlineContent":[{"text":"not","type":"text"}],"type":"strong"},{"type":"text","text":" supported on iOS."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"On macOS:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Verify that your USB cable provides both power and data connection (i.e. - it is a USB data cable and not a simple charging cable).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"If you are connected via a USB hub, try moving the device to a different USB port, or try attaching directly to your Mac.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If you are running antivirus software, verify that it is not blocking access to USB serial modem devices."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]},{"content":[{"inlineContent":[{"text":"The device scanner is running, but no nearby Nix devices are found.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For USB attached devices, complete the troubleshooting steps listed above in item #7."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For Bluetooth devices:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Ensure that the Nix device is charged."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Ensure that it is not actively connected to another application (see item #1). If in doubt, connecting the Nix device to a charger will reset any active connections.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"}]}]},{"text":"Other","anchor":"Other","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Can I rename the Nix device?","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"The device ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name"},{"text":" is fixed in the device firmware and cannot be changed.","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Can I assign a nickname to a particular device?"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"For Bluetooth devices, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id"},{"text":" represents a unique hardware address. Since this is visible during the device search, this can be used by your application to tag or nickname individual devices during a device search or re-connection.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that the ID for USB attached devices is not unique and cannot be used for nicknaming purposes."}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Once connected, the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","isActive":true},{"type":"text","text":" can be used to uniquely identify devices regardless of their connection interface."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Does the SDK provide access to any existing colour libraries (paint colours, PANTONE, RAL, NCS, etc.)?","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"No, the ","type":"text"},{"type":"codeVoice","code":"NixUniversalSDK"},{"text":" does not provide any colour libraries. Creation and maintenance of colour libraries is the responsibility of the application creator or the application end-user.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"When handling your own colour library data, the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","type":"reference"},{"type":"text","text":" class provides many helpful functions for manual colour conversions and delta E calculations (e.g. - for colour matching against a library)."}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Do you provide plugins for cross-platform frameworks (such as Unity, React Native, Flutter, Xamarin, Xojo, etc.)?"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix Sensor Ltd. does not provide ready-made plugins for these third-party frameworks."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"However, most third-party frameworks provide methods to ‘bridge’ or ‘wrap’ platform specific libraries. In most cases, it is possible to use the NixUniversalSDK with some minor adjustments.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Some examples could include:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Native Modules in "},{"identifier":"https:\/\/reactnative.dev\/docs\/turbo-native-modules-introduction","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Bindings library in Xamarin","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"text":"Please contact us via e-mail at ","type":"text"},{"type":"reference","identifier":"mailto:sdk@nixsensor.com","isActive":true,"overridingTitleInlineContent":[{"type":"text","text":"sdk@nixsensor.com"}],"overridingTitle":"sdk@nixsensor.com"},{"type":"text","text":" if assistance is required."}],"type":"paragraph"}]}]}]}]},{"text":"Next Steps","anchor":"Next-Steps","type":"heading","level":2},{"items":[{"content":[{"inlineContent":[{"text":"Review the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Additional-Support","isActive":true}]}]}],"type":"unorderedList"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/faq"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/faq"]}],"abstract":[{"text":"Troubleshooting common issues","type":"text"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/faq","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"sections":[],"metadata":{"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Article","role":"article","title":"Frequently Asked Questions"},"seeAlsoSections":[{"title":"Getting Started","generated":true,"anchor":"Getting-Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"]}],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"abstract":[{"type":"text","text":"Review an example project which provides a C\/C++ interface for macOS applications"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","url":"\/documentation\/nixuniversalsdk\/wrapper","title":"Wrapper for Usage in C\/C++","type":"topic","role":"article","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/interfaceType":{"abstract":[{"type":"text","text":"Interface \/ connection type for this device"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/interfacetype","required":true,"title":"interfaceType","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interfaceType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@InterfaceType","text":"InterfaceType","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"interfaceType","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK#Additional-Support":{"title":"Additional Support","url":"\/documentation\/nixuniversalsdk#Additional-Support","abstract":[],"kind":"section","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Additional-Support","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/activate(options:signature:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","url":"\/documentation\/nixuniversalsdk\/licensemanager\/activate(options:signature:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"signature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","kind":"typeIdentifier"}],"title":"activate(options:signature:)","role":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"activateWithOptions:andSignature:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Activates a license. The options and signature parameters must exactly match the values provided in the SDK license. Calling this function invalidates any currently active license.","type":"text"}],"kind":"symbol"},"https://reactnative.dev/docs/turbo-native-modules-introduction":{"identifier":"https:\/\/reactnative.dev\/docs\/turbo-native-modules-introduction","titleInlineContent":[{"text":"React Native","type":"text"}],"type":"link","url":"https:\/\/reactnative.dev\/docs\/turbo-native-modules-introduction","title":"React Native"},"mailto:sdk@nixsensor.com":{"url":"mailto:sdk@nixsensor.com","titleInlineContent":[{"text":"sdk@nixsensor.com","type":"text"}],"identifier":"mailto:sdk@nixsensor.com","title":"sdk@nixsensor.com","type":"link"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","url":"\/documentation\/nixuniversalsdk\/activating-license","title":"Activating the SDK License","type":"topic","role":"article","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","abstract":[{"type":"text","text":"Color math utility functions"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorUtils"}],"navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","title":"ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","url":"\/documentation\/nixuniversalsdk\/licensemanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}],"title":"LicenseManager","role":"symbol","navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}]},"https://nixsensor.com/nixserial":{"identifier":"https:\/\/nixsensor.com\/nixserial","titleInlineContent":[{"type":"text","text":"https:\/\/nixsensor.com\/nixserial"}],"title":"https:\/\/nixsensor.com\/nixserial","type":"link","url":"https:\/\/nixsensor.com\/nixserial"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/id":{"role":"symbol","abstract":[{"type":"text","text":"Unique identifier for this device"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id","title":"id","navigatorTitle":[{"kind":"identifier","text":"id"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"required":true,"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/id"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/state":{"abstract":[{"text":"Describes the current state of the  ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"text":". Nix Universal SDK functions are available only if license is active (i.e. - the state is ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","isActive":true,"type":"reference"},{"text":")","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","url":"\/documentation\/nixuniversalsdk\/licensemanager\/state","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState"}],"title":"state","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/name":{"abstract":[{"text":"Name for this device","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/name","required":true,"title":"name","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"kind":"article","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","title":"Discovering and Connecting to Nix Devices","role":"article","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","abstract":[{"type":"text","text":"Use the device scanner to discover Nix devices and open a connection"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManagerState","kind":"identifier"}],"title":"LicenseManagerState","role":"symbol","navigatorTitle":[{"text":"LicenseManagerState","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_BLUETOOTH_UNAVAILABLE":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","title":"DeviceScannerState.ERROR_BLUETOOTH_UNAVAILABLE","abstract":[{"type":"text","text":"Bluetooth scanner could not start because Bluetooth is not available on this mobile device."}],"navigatorTitle":[{"text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_unavailable","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"abstract":[{"text":"Add the library bundle to your project and declare peripheral uses","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","url":"\/documentation\/nixuniversalsdk\/add-to-xcode","title":"Adding to Your Xcode Project","type":"topic","role":"article","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/rssi":{"abstract":[{"text":"Signal strength for this device","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/rssi","required":true,"title":"rssi","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rssi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rssi"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_LICENSE":{"navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_LICENSE"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_license","title":"DeviceScannerState.ERROR_LICENSE","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE","abstract":[{"type":"text","text":"Bluetooth scanner could not start due to a problem with the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"type":"text","text":". Check "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","isActive":true,"type":"reference"},{"type":"text","text":" for details."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/serialNumber":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/serialnumber","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"serialNumber","role":"symbol","navigatorTitle":[{"text":"serialNumber","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Serial number for this device. The value is valid only after a connection has successfully been opened."}],"kind":"symbol","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ACTIVE"}],"title":"LicenseManagerState.ACTIVE","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"type":"topic","abstract":[{"text":"The license has activated successfully and Nix Universal SDK functions are available.","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_UNAUTHORIZED":{"role":"symbol","title":"DeviceStatus.ERROR_UNAUTHORIZED","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED","abstract":[{"text":"The device connection attempt was cancelled because the specified device was not authorized for this build of the Nix SDK. Check that the device allocation code and\/or serial number is expected to be authorized for this build.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"DeviceStatusERROR_UNAUTHORIZED","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ERROR_UNAUTHORIZED","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_unauthorized","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"role":"article","title":"Example Applications","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","abstract":[{"type":"text","text":"Explore source code for demo iOS and macOS applications"}],"kind":"article","type":"topic","url":"\/documentation\/nixuniversalsdk\/example-apps"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","kind":"article","title":"Handling Measurement Data","role":"article","type":"topic","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"ios_rssi_example.png":{"type":"image","alt":"iOS RSSI Screenshot","variants":[{"traits":["3x","light"],"url":"\/images\/com.nixsensor.universalsdk\/ios_rssi_example@3x.png"}],"identifier":"ios_rssi_example.png"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"url":"\/documentation\/nixuniversalsdk\/release-notes","kind":"article","title":"Release Notes","role":"article","type":"topic","abstract":[{"type":"text","text":"Review the changes made in this version of the library"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"abstract":[{"type":"text","text":"Take measurements, set device options, and query device properties"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","url":"\/documentation\/nixuniversalsdk\/device-operations","title":"Device Operations","type":"topic","role":"article","kind":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"generated":true,"anchor":"Getting-Started","title":"Getting Started"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1interfaceType\/title","value":"interfaceType","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1interfaceType\/fragments","value":[{"text":"interfaceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/title","value":"activateWithOptions:andSignature:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"activateWithOptions:andSignature:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","value":[{"text":"LicenseManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1id\/title","value":"id","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/title","value":"state","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/fragments","value":[{"text":"state","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title","op":"replace","value":"LicenseManagerState"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments","op":"replace","value":[{"kind":"identifier","text":"LicenseManagerState"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle","op":"replace","value":[{"text":"LicenseManagerState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_UNAVAILABLE\/title","op":"replace","value":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_UNAVAILABLE\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rssi\/title","op":"replace","value":"rssi"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rssi\/fragments","op":"replace","value":[{"text":"rssi","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_LICENSE\/title","op":"replace","value":"DeviceScannerStateERROR_LICENSE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_LICENSE\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceScannerStateERROR_LICENSE"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1serialNumber\/title","op":"replace","value":"serialNumber"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1serialNumber\/fragments","op":"replace","value":[{"text":"serialNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title","op":"replace","value":"LicenseManagerStateACTIVE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments","op":"replace","value":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNAUTHORIZED\/title","op":"replace","value":"DeviceStatusERROR_UNAUTHORIZED"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNAUTHORIZED\/fragments","op":"replace","value":[{"text":"DeviceStatusERROR_UNAUTHORIZED","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}