{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/icolordata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/icolordata"]}],"metadata":{"symbolKind":"protocol","role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)IColorData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IColorData"}],"navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"title":"IColorData","roleHeading":"Protocol","modules":[{"name":"NixUniversalSDK"}]},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/rgbValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/type","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/value"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/compareTo(other:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/convertTo(type:)"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IColorData","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/rgbValue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/rgbValue","required":true,"url":"\/documentation\/nixuniversalsdk\/icolordata\/rgbvalue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rgbValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rgbValue"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"sRGB value for this color."}],"title":"rgbValue"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/type":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"title":"type","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/type","url":"\/documentation\/nixuniversalsdk\/icolordata\/type","abstract":[{"text":"Type of color data stored in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/value","isActive":true},{"text":" field.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/mode":{"url":"\/documentation\/nixuniversalsdk\/icolordata\/mode","navigatorTitle":[{"kind":"identifier","text":"mode"}],"title":"mode","type":"topic","abstract":[{"type":"text","text":"Scan mode for this value."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/mode","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/compareTo(other:type:)":{"url":"\/documentation\/nixuniversalsdk\/icolordata\/compareto(other:type:)","navigatorTitle":[{"text":"compareToOther:type:","kind":"identifier"}],"type":"topic","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compareTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"other"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ColorDifferenceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","abstract":[{"type":"text","text":"Calculate delta E between this color and another. The colors must share the same reference white point ("},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","isActive":true},{"type":"text","text":")."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/compareTo(other:type:)","title":"compareTo(other:type:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","title":"IColorData","navigatorTitle":[{"kind":"identifier","text":"IColorData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","url":"\/documentation\/nixuniversalsdk\/colortype","kind":"symbol","title":"ColorType","role":"symbol","navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorType"}],"abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","type":"reference"},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/convertTo(type:)":{"title":"convertTo(type:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertTo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"}],"navigatorTitle":[{"text":"convertToType:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/icolordata\/convertto(type:)","role":"symbol","abstract":[{"text":"Convert this color value to another ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","type":"reference"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/convertTo(type:)","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/colordata","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorData"}],"navigatorTitle":[{"text":"ColorData","kind":"identifier"}],"title":"ColorData","abstract":[{"text":"Class describing colorimetry data","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/value":{"role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Color value (3 coordinates) in the format specified by "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/mode"},{"type":"text","text":"."}],"required":true,"title":"value","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/value","url":"\/documentation\/nixuniversalsdk\/icolordata\/value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/reference":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","required":true,"url":"\/documentation\/nixuniversalsdk\/icolordata\/reference","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"}],"navigatorTitle":[{"kind":"identifier","text":"reference"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Reference white point for this color value."}],"title":"reference"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"IColorData","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IColorData"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IColorData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/rgbValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/type","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/value"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/compareTo(other:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/convertTo(type:)"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Conforming Types","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData"],"type":"conformingTypes","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"IColorData","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"rgbValue","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1rgbValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1rgbValue\/fragments","value":[{"kind":"identifier","text":"rgbValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1type\/title","value":"type"},{"value":[{"text":"type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1type\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1mode\/title","value":"mode"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1mode\/fragments","value":[{"text":"mode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1compareTo(other:type:)\/title","value":"compareToOther:type:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"compareToOther:type:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1compareTo(other:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","op":"replace","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","op":"replace","value":"ColorType"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","op":"replace","value":[{"text":"ColorType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ColorType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle"},{"value":"convertToType:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1convertTo(type:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1convertTo(type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertToType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/title","value":"ColorData"},{"op":"replace","value":[{"kind":"identifier","text":"ColorData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/fragments"},{"value":[{"kind":"identifier","text":"ColorData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1value\/title","value":"value"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1value\/fragments"},{"value":"reference","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1reference\/title","op":"replace"},{"value":[{"text":"reference","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1reference\/fragments","op":"replace"}]}]}