{"sections":[],"abstract":[{"type":"text","text":"Protocol describing density data"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDensityData"}]}]},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Since 4.0.2","type":"text"}]}]}]}],"kind":"content"}],"metadata":{"externalID":"c:@M@NixUniversalSDK@objc(pl)IDensityData","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IDensityData","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"IDensityData"}],"title":"IDensityData","symbolKind":"protocol","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/idensitydata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/idensitydata"]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/autoIndex","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/status","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/statusLabel","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/value"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData/autoIndex":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoIndex"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"autoIndex","kind":"identifier"}],"title":"autoIndex","type":"topic","abstract":[{"type":"text","text":"Indicates which channel (0 - 3) in "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/value","isActive":true},{"type":"text","text":" has the strongest response, with greyness override"}],"required":true,"url":"\/documentation\/nixuniversalsdk\/idensitydata\/autoindex","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/autoIndex"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData/mode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idensitydata\/mode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/mode","title":"mode","kind":"symbol","required":true,"type":"topic","abstract":[{"type":"text","text":"Scan mode for this measurement."}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDensityData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"IDensityData","kind":"identifier"}],"title":"IDensityData","type":"topic","abstract":[{"type":"text","text":"Protocol describing density data"}],"url":"\/documentation\/nixuniversalsdk\/idensitydata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData/value":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idensitydata\/value","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/value","title":"value","kind":"symbol","required":true,"type":"topic","abstract":[{"type":"text","text":"Density values (4 channels, CMYK order)"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/T":{"url":"\/documentation\/nixuniversalsdk\/densitystatus\/t","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"T","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","title":"DensityStatus.T","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DensityStatusT"}],"abstract":[{"text":"Status T (ISO 5-3:2009)","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DensityData","kind":"identifier"}],"abstract":[{"text":"Class describing density data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/densitydata","type":"topic","kind":"symbol","title":"DensityData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData","role":"symbol","navigatorTitle":[{"text":"DensityData","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData/statusLabel":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/statusLabel","title":"statusLabel","navigatorTitle":[{"kind":"identifier","text":"statusLabel"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","abstract":[{"text":"Density status label for this value (eg - ‘T’ for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T"},{"text":")","type":"text"}],"kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nixuniversalsdk\/idensitydata\/statuslabel"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData/status":{"title":"status","role":"symbol","abstract":[{"text":"Density status for this value","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/status","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"status"}],"url":"\/documentation\/nixuniversalsdk\/idensitydata\/status","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"IDensityData"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDensityData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDensityData"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/autoIndex","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/status","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/statusLabel","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData\/value"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDensityData","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1autoIndex\/title","value":"autoIndex","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1autoIndex\/fragments","value":[{"text":"autoIndex","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1mode\/title","value":"mode"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}],"op":"replace"},{"op":"replace","value":"IDensityData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title"},{"op":"replace","value":[{"text":"IDensityData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle","value":[{"text":"IDensityData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1value\/title","op":"replace","value":"value"},{"value":[{"kind":"identifier","text":"value"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1value\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/title","value":"DensityStatusT","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/fragments","op":"replace","value":[{"text":"DensityStatusT","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/title","value":"DensityData"},{"value":[{"text":"DensityData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/navigatorTitle","value":[{"text":"DensityData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1statusLabel\/title","value":"statusLabel","op":"replace"},{"value":[{"text":"statusLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1statusLabel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1status\/title","value":"status"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData~1status\/fragments","value":[{"kind":"identifier","text":"status"}],"op":"replace"}]}]}