{"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","interfaceLanguage":"swift"},"abstract":[{"text":"Enum to describe the available options for reference illuminant","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Illuminant","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/illuminant"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/illuminant"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/A","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/C","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D55","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D65","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D75","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F11","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F7","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE"],"generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fullName"],"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fromFullName(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fromInt(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fromUInt8(_:)"],"title":"Type Methods","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"metadata":{"externalID":"c:@M@NixUniversalSDK@E@Illuminant","navigatorTitle":[{"kind":"identifier","text":"Illuminant"}],"title":"Illuminant","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"symbolKind":"enum"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/NONE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE","title":"Illuminant.NONE","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NONE","kind":"identifier"}],"navigatorTitle":[{"text":"IlluminantNONE","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/none","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/F11":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IlluminantF11"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F11"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/illuminant\/f11","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F11","title":"Illuminant.F11"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/Equatable-Implementations":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/Equatable-Implementations","url":"\/documentation\/nixuniversalsdk\/illuminant\/equatable-implementations","title":"Equatable Implementations","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/fromFullName(_:)":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/fromfullname(_:)","type":"topic","abstract":[{"type":"text","text":"Helper to provide the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","isActive":true},{"type":"text","text":" enum for a particular illuminant name. If an invalid name is provided, "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE","isActive":true},{"type":"text","text":" is returned."}],"title":"fromFullName(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fromFullName(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromFullName"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"}]},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/fromUInt8(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fromUInt8(_:)","title":"fromUInt8(_:)","type":"topic","role":"symbol","abstract":[{"text":"Helper to provide the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"},{"type":"text","text":" enum for a particular byte value. If an invalid value is provided, "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE","type":"reference"},{"type":"text","text":" is returned."}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/fromuint8(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromUInt8"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/nixuniversalsdk\/illuminant\/rawrepresentable-implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/RawRepresentable-Implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/A":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/A","navigatorTitle":[{"kind":"identifier","text":"IlluminantA"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/a","title":"Illuminant.A","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"A","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/C":{"navigatorTitle":[{"kind":"identifier","text":"IlluminantC"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"C","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/c","kind":"symbol","title":"Illuminant.C","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/C","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"title":"Illuminant","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Illuminant"}],"abstract":[{"text":"Enum to describe the available options for reference illuminant","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","url":"\/documentation\/nixuniversalsdk\/illuminant","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/init(rawValue:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":")"}],"type":"topic","title":"init(rawValue:)","role":"symbol","url":"\/documentation\/nixuniversalsdk\/illuminant\/init(rawvalue:)","kind":"symbol","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D55":{"title":"Illuminant.D55","role":"symbol","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/nixuniversalsdk\/illuminant\/d55","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D55","navigatorTitle":[{"text":"IlluminantD55","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"D55","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D65":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/d65","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"D65","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IlluminantD65"}],"title":"Illuminant.D65","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D65"},"doc://com.nixsensor.universalsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D75":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/d75","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"D75"}],"title":"Illuminant.D75","navigatorTitle":[{"kind":"identifier","text":"IlluminantD75"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D75","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/F7":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/f7","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F7"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IlluminantF7"}],"title":"Illuminant.F7","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F7"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/fullName":{"title":"fullName","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Full name for display in UI (e.g. - ‘D50’ for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true},{"type":"text","text":")"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/fullname","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fullName","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/fromInt(_:)":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/fromint(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromInt","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fromInt(_:)","role":"symbol","abstract":[{"type":"text","text":"Helper to provide the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","isActive":true},{"text":" enum for a particular integer value. If an invalid value is provided, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE"},{"text":" is returned.","type":"text"}],"kind":"symbol","title":"fromInt(_:)","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/F2":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/f2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F2"}],"navigatorTitle":[{"text":"IlluminantF2","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F2","role":"symbol","abstract":[],"kind":"symbol","title":"Illuminant.F2","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50"}],"navigatorTitle":[{"text":"IlluminantD50","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/d50","title":"Illuminant.D50","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"Illuminant","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Illuminant","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/A","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/C","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D55","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D65","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D75","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F11","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/F7","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"},{"kind":"text","text":": "},{"text":"uint8_t","preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1NONE\/title","value":"IlluminantNONE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1NONE\/fragments","op":"replace","value":[{"text":"IlluminantNONE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1F11\/title","value":"IlluminantF11","op":"replace"},{"value":[{"kind":"identifier","text":"IlluminantF11"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1F11\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1A\/title","op":"replace","value":"IlluminantA"},{"value":[{"text":"IlluminantA","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1A\/fragments"},{"op":"replace","value":"IlluminantC","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1C\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1C\/fragments","value":[{"kind":"identifier","text":"IlluminantC"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","op":"replace","value":"Illuminant"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","op":"replace","value":[{"text":"Illuminant","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D55\/title","value":"IlluminantD55","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D55\/fragments","op":"replace","value":[{"text":"IlluminantD55","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D65\/title","value":"IlluminantD65"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D65\/fragments","value":[{"text":"IlluminantD65","kind":"identifier"}]},{"op":"replace","value":"IlluminantD75","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D75\/title"},{"value":[{"kind":"identifier","text":"IlluminantD75"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D75\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1F7\/title","value":"IlluminantF7"},{"value":[{"text":"IlluminantF7","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1F7\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1F2\/title","value":"IlluminantF2","op":"replace"},{"value":[{"text":"IlluminantF2","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1F2\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","op":"replace","value":"IlluminantD50"},{"value":[{"text":"IlluminantD50","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments"}]}]}