{"abstract":[{"type":"text","text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true,"type":"reference"},{"text":" callback after a measurement is taken using an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance, or can be reconstructed from raw string data using ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"IMeasurementData","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"IMeasurementData"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}],"symbolKind":"protocol","externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","modules":[{"name":"NixUniversalSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesDensity","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesSpectral","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/raw","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/spectralData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/status","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/supportedReferences","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tCompEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tReal","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tRef","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tScan","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tileDelta","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tileEnabled"],"title":"Instance Properties","generated":true},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providedColor(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(reference:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toDensityData(status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(reference:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IMeasurementData"}],"platforms":["macOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesDensity":{"navigatorTitle":[{"kind":"identifier","text":"providesDensity"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providesdensity","title":"providesDensity","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Flag (as a "},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" wrapped "},{"code":"Bool","type":"codeVoice"},{"type":"text","text":") indicating if this measurement provides density values. This value depends on both the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType"},{"text":" and availability of the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/DENSITY_DATA","type":"reference","isActive":true},{"type":"text","text":" feature."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesDensity","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"providesDensity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/mode":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/mode","kind":"symbol","title":"mode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/mode","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"mode"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"abstract":[{"type":"text","text":"Scan mode for this measurement."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromRaw","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Reconstructs a "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the data is invalid."}],"url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","title":"fromRaw(_:)","kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toColorData(reference:type:)":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData"},{"text":"?","kind":"text"}],"title":"toColorData(reference:type:)","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(reference:type:)","role":"symbol","navigatorTitle":[{"text":"toColorDataForReference:andType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"code":"nil","type":"codeVoice"},{"text":" if the specified white point is not available for this measurement.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/tScan":{"abstract":[{"type":"text","text":"Temperature of the Nix device at the time of this measurement, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the device did not support temperature measurements. Optional "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value wrapped in a "},{"type":"codeVoice","code":"NSNumber"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tScan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"title":"tScan","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tScan","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"tScan"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tscan"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceScanner","kind":"identifier"}],"kind":"symbol","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","navigatorTitle":[{"text":"DeviceScanner","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/tileDelta":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tiledelta","kind":"symbol","title":"tileDelta","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tileDelta","role":"symbol","required":true,"navigatorTitle":[{"text":"tileDelta","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileDelta"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Delta E value between this measurement and factory reference. Value is non-nil for measurement values from ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","type":"reference","isActive":true},{"type":"text","text":" and "},{"type":"codeVoice","code":"nil"},{"text":" in all other cases.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/status":{"abstract":[{"text":"Scan status byte. A value of ","type":"text"},{"type":"codeVoice","code":"0x01"},{"type":"text","text":" indicates success, all other values indicate error states. "},{"code":"UInt8","type":"codeVoice"},{"text":" value wrapped in ","type":"text"},{"type":"codeVoice","code":"NSNumber"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"}],"title":"status","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/status","role":"symbol","required":true,"navigatorTitle":[{"text":"status","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/status"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/deviceType":{"navigatorTitle":[{"kind":"identifier","text":"deviceType"}],"type":"topic","title":"deviceType","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/devicetype","abstract":[{"type":"text","text":"Device type that was used to make this measurement."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesColor(reference:)":{"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" if color data for the selected combination of illuminant and observer are available for this measurement."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"providesColorForReference:"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providescolor(reference:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providesColor"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"providesColor(reference:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(reference:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/spectralData":{"required":true,"title":"spectralData","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/spectraldata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"spectralData"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)ISpectralData","text":"ISpectralData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"spectralData","kind":"identifier"}],"abstract":[{"text":"Provides a spectral data object from this measurement, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if spectral data is not supported."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/spectralData","type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providedColor(illuminant:observer:)":{"abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" if color data for the selected combination of illuminant and observer are available for this measurement."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providedColor(illuminant:observer:)","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providedcolor(illuminant:observer:)","required":true,"type":"topic","role":"symbol","deprecated":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providedColor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"providedColorForIlluminant:andObserver:","kind":"identifier"}],"title":"providedColor(illuminant:observer:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/tRef":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tRef","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"text":"Baseline reference temperature for this measurement, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the device did not support temperature measurements. Optional "},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value wrapped in a "},{"type":"codeVoice","code":"NSNumber"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"tRef","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tref","title":"tRef","type":"topic","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tRef"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature/DENSITY_DATA":{"abstract":[{"type":"text","text":"Provides access to density values via "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","type":"reference","isActive":true},{"type":"text","text":", if supported by the Nix device."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"LicenseFeatureDENSITY_DATA","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature\/density_data","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"DENSITY_DATA","kind":"identifier"}],"title":"LicenseFeature.DENSITY_DATA","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/DENSITY_DATA","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/tReal":{"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/treal","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tReal"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"tReal","navigatorTitle":[{"text":"tReal","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Flag describing the units for the reported temperature measurement. When "},{"type":"codeVoice","code":"true"},{"type":"text","text":", temperature values are ‘real’ (floating point, degrees C). When "},{"code":"false","type":"codeVoice"},{"type":"text","text":", temperatures are reported on an arbitrary raw scale. Value is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the device did not support temperature measurements. Optional "},{"type":"codeVoice","code":"Bool"},{"text":" value wrapped in a ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tReal"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/raw":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/raw","navigatorTitle":[{"kind":"identifier","text":"raw"}],"abstract":[{"text":"Raw data for a measurement. Can be used for measurement object reconstruction.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/raw","type":"topic","title":"raw","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"raw","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toRgbValue(reference:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"kind":"text","text":") -> "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"required":true,"title":"toRgbValue(reference:)","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/torgbvalue(reference:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(reference:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/tileEnabled":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tileenabled","kind":"symbol","title":"tileEnabled","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tileEnabled","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"tileEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Flag indicating if in-field profiling corrections \/ white reference tile measurements were applied to the calibrated output data. Value is "},{"code":"nil","type":"codeVoice"},{"text":" if the device did not support in-field profiling. Optional ","type":"text"},{"code":"Bool","type":"codeVoice"},{"type":"text","text":" value wrapped in a "},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/runFieldCalibration(tileString:completion:)":{"required":true,"abstract":[{"text":"Start field calibration using provided reference tile, if supported. Upon executing this command, the scan of the reference tile will begin immediately. The user MUST be prompted to place the device onto the reference tile BEFORE this method is executed. This method is asynchronous and will return immediately.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This command requires data from the reference tile QR code. As the format varies between different device types, the string data should be provided exactly as decoded from the QR code."}],"navigatorTitle":[{"text":"runFieldCalibration:completion:","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/runfieldcalibration(tilestring:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"runFieldCalibration"},{"text":"(","kind":"text"},{"text":"tileString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","role":"symbol","title":"runFieldCalibration(tileString:completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toDensityData(status:)":{"navigatorTitle":[{"kind":"identifier","text":"toDensityDataForStatus:"}],"title":"toDensityData(status:)","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toDensityData(status:)","abstract":[{"text":"Provides absolute density values for this measurement evaluated as per ISO 5-3:2009, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if density data is not supported.","type":"text"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/todensitydata(status:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toDensityData"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData","text":"IDensityData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature/SPECTRAL_DATA":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SPECTRAL_DATA"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature\/spectral_data","kind":"symbol","abstract":[{"text":"Provides access to spectral values via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"},{"type":"text","text":", if supported by the Nix device."}],"role":"symbol","title":"LicenseFeature.SPECTRAL_DATA","navigatorTitle":[{"kind":"identifier","text":"LicenseFeatureSPECTRAL_DATA"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/supportedReferences":{"abstract":[{"type":"text","text":"Array describing all reference white points that are available when requesting color data from this measurement using "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","isActive":true},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supportedReferences","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":">"}],"title":"supportedReferences","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/supportedReferences","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"supportedReferences"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/supportedreferences"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesColor(illuminant:observer:)":{"navigatorTitle":[{"text":"providesColorForIlluminant:andObserver:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providescolor(illuminant:observer:)","role":"symbol","required":true,"kind":"symbol","abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if color data for the selected combination of illuminant and observer are available for this measurement."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providesColor"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(illuminant:observer:)","title":"providesColor(illuminant:observer:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toColorData(illuminant:observer:type:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"required":true,"kind":"symbol","navigatorTitle":[{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"toColorData(illuminant:observer:type:)","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(illuminant:observer:type:)","type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceResultCallback"}],"type":"topic","title":"DeviceResultCallback","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"type":"text","text":" instance."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/tCompEnabled":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tCompEnabled","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tcompenabled","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tCompEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"required":true,"title":"tCompEnabled","abstract":[{"type":"text","text":"Flag indicating if temperature compensation was applied to the calibrated output for this measurement. Value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the device did not support temperature measurements. Optional "},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" value wrapped in a "},{"code":"NSNumber","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"tCompEnabled","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesSpectral":{"required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesSpectral","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providesspectral","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"providesSpectral","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"navigatorTitle":[{"text":"providesSpectral","kind":"identifier"}],"abstract":[{"text":"Flag (as a ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"text":" wrapped ","type":"text"},{"type":"codeVoice","code":"Bool"},{"type":"text","text":") indicating if this measurement provides spectral values. This value depends on both the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType","type":"reference","isActive":true},{"text":" and availability of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA"},{"text":" feature.","type":"text"}],"title":"providesSpectral"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"role":"symbol","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","title":"IMeasurementData","abstract":[{"type":"text","text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true,"type":"reference"},{"type":"text","text":" callback after a measurement is taken using an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)"},{"text":".","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IMeasurementData","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDeviceCompat"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toRgbValue(illuminant:observer:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toRgbValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/torgbvalue(illuminant:observer:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(illuminant:observer:)","title":"toRgbValue(illuminant:observer:)","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IMeasurementData"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"IMeasurementData","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IMeasurementData"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesDensity","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesSpectral","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/raw","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/spectralData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/status","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/supportedReferences","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tCompEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tReal","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tRef","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tScan","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tileDelta","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/tileEnabled"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providedColor(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(reference:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toDensityData(status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(reference:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesDensity\/title","value":"providesDensity"},{"value":[{"text":"providesDensity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesDensity\/fragments"},{"value":"mode","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1mode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(reference:type:)\/title","value":"toColorDataForReference:andType:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(reference:type:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"toColorDataForReference:andType:","kind":"identifier"}]},{"value":"tScan","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tScan\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tScan\/fragments","value":[{"text":"tScan","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tileDelta\/title","op":"replace","value":"tileDelta"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tileDelta\/fragments","op":"replace","value":[{"kind":"identifier","text":"tileDelta"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1deviceType\/title","value":"deviceType"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1deviceType\/fragments","value":[{"kind":"identifier","text":"deviceType"}]},{"op":"replace","value":"providesColorForReference:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesColor(reference:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesColor(reference:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"providesColorForReference:","kind":"identifier"}]},{"value":"spectralData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1spectralData\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1spectralData\/fragments","value":[{"kind":"identifier","text":"spectralData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providedColor(illuminant:observer:)\/title","value":"providedColorForIlluminant:andObserver:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"providedColorForIlluminant:andObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providedColor(illuminant:observer:)\/fragments","op":"replace"},{"value":"tRef","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tRef\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tRef\/fragments","op":"replace","value":[{"kind":"identifier","text":"tRef"}]},{"value":"LicenseFeatureDENSITY_DATA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1DENSITY_DATA\/title","op":"replace"},{"value":[{"kind":"identifier","text":"LicenseFeatureDENSITY_DATA"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1DENSITY_DATA\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tReal\/title","op":"replace","value":"tReal"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tReal\/fragments","value":[{"text":"tReal","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1raw\/title","value":"raw"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1raw\/fragments","op":"replace","value":[{"text":"raw","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(reference:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"toRgbValueForReference:","kind":"identifier"}]},{"op":"replace","value":"tileEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tileEnabled\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tileEnabled\/fragments","value":[{"text":"tileEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/title","value":"runFieldCalibration:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"runFieldCalibration:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toDensityData(status:)\/title","value":"toDensityDataForStatus:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toDensityData(status:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toDensityDataForStatus:","kind":"identifier"}],"op":"replace"},{"value":"LicenseFeatureSPECTRAL_DATA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1SPECTRAL_DATA\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1SPECTRAL_DATA\/fragments","value":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1supportedReferences\/title","value":"supportedReferences"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1supportedReferences\/fragments","value":[{"kind":"identifier","text":"supportedReferences"}]},{"op":"replace","value":"providesColorForIlluminant:andObserver:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesColor(illuminant:observer:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesColor(illuminant:observer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"providesColorForIlluminant:andObserver:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(illuminant:observer:type:)\/title","value":"toColorDataForIlluminant:andObserver:andType:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(illuminant:observer:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}]},{"value":"tCompEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tCompEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1tCompEnabled\/fragments","value":[{"text":"tCompEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesSpectral\/title","op":"replace","value":"providesSpectral"},{"value":[{"text":"providesSpectral","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesSpectral\/fragments"},{"value":"IMeasurementData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle","op":"replace","value":[{"text":"IMeasurementData","kind":"identifier"}]},{"value":"IDeviceCompat","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(illuminant:observer:)\/title","value":"toRgbValueForIlluminant:andObserver:"},{"value":[{"kind":"text","text":"- "},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(illuminant:observer:)\/fragments","op":"replace"}]}]}