{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allocations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypesByNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/expiry","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/features-3nk3h","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/featuresByNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/libraryVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/uuid"]},{"title":"Type Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/deactivate()","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)"],"generated":true,"anchor":"Type-Methods"}],"abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"title":"LicenseManager","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManager"}],"roleHeading":"Class","externalID":"c:@M@NixUniversalSDK@objc(cs)LicenseManager","role":"symbol"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/licensemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanager"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.2.0"}]}]}]}],"kind":"content"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/uuid":{"navigatorTitle":[{"text":"uuid","kind":"identifier"}],"abstract":[{"text":"Vendor identifier for the current license.","type":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/uuid","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uuid","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","title":"uuid","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/uuid"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/state":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/state","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","abstract":[{"type":"text","text":"Describes the current state of the  "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"reference"},{"type":"text","text":". Nix Universal SDK functions are available only if license is active (i.e. - the state is "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","isActive":true,"type":"reference"},{"text":")","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","text":"LicenseManagerState","kind":"typeIdentifier"}],"title":"state","navigatorTitle":[{"text":"state","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/activate(options:signature:)":{"abstract":[{"type":"text","text":"Activates a license. The options and signature parameters must exactly match the values provided in the SDK license. Calling this function invalidates any currently active license."}],"role":"symbol","kind":"symbol","title":"activate(options:signature:)","navigatorTitle":[{"text":"activateWithOptions:andSignature:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"signature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","text":"LicenseManagerState"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/activate(options:signature:)","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allocations":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/allocations","type":"topic","role":"symbol","title":"allocations","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allocations","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allocations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"allocations","kind":"identifier"}],"abstract":[{"type":"text","text":"List of Nix device allocation codes associated with the current license."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype","title":"DeviceType"},"doc://com.nixsensor.universalsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/libraryVersion":{"navigatorTitle":[{"text":"libraryVersion","kind":"identifier"}],"abstract":[{"text":"Current version of the Nix Universal SDK.","type":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/libraryversion","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraryVersion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"libraryVersion","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/libraryVersion"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/features-3nk3h":{"title":"features","abstract":[{"text":"Set of features enabled by the current license. Available in Swift only.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/features-3nk3h","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/licensemanager\/features-3nk3h","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"features","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature","text":"LicenseFeature"},{"kind":"text","text":">"}]},"doc://com.nixsensor.universalsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"title":"LicenseManagerState.ACTIVE","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ACTIVE","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active","navigatorTitle":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}],"abstract":[{"text":"The license has activated successfully and Nix Universal SDK functions are available.","type":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isDeviceTypeSupported(_:)":{"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isDeviceTypeSupported","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isDeviceTypeSupported(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","kind":"symbol","navigatorTitle":[{"text":"isDeviceTypeSupported:","kind":"identifier"}],"abstract":[{"type":"text","text":"Helper to check if a particular "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","type":"reference"},{"type":"text","text":" is supported by the current license."}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/isdevicetypesupported(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allowedDeviceTypesByNumber":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypesbynumber","title":"allowedDeviceTypesByNumber","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypesByNumber","navigatorTitle":[{"text":"allowedDeviceTypes","kind":"identifier"}],"abstract":[{"text":"Set of ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" containing the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","isActive":true,"type":"reference"},{"type":"text","text":" values enabled by the current license."}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedDeviceTypesByNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","type":"topic","role":"symbol","title":"isFeatureEnabled(_:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFeatureEnabled","kind":"identifier"},{"kind":"text","text":"("},{"text":"LicenseFeature","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isFeatureEnabled:"}],"abstract":[{"text":"Helper to check if a particular ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"},{"type":"text","text":" is enabled by the current license."}]},"doc://com.nixsensor.universalsdk/s7CVarArgP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allowedDeviceTypes-4f98s":{"abstract":[{"type":"text","text":"Set of device types supported by the current license. Available in Swift only."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","title":"allowedDeviceTypes","url":"\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypes-4f98s","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedDeviceTypes"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/expiry":{"abstract":[{"text":"Expiry date for the current license.","type":"text"}],"type":"topic","title":"expiry","navigatorTitle":[{"text":"expiry","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"expiry","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/expiry","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/expiry","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/deactivate()":{"title":"deactivate()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deactivate","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/deactivate()","url":"\/documentation\/nixuniversalsdk\/licensemanager\/deactivate()","navigatorTitle":[{"text":"deactivate","kind":"identifier"}],"abstract":[{"text":"Deactivates the current license.","type":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseFeature"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"topic","title":"LicenseFeature","navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the optional features that can be enabled by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"type":"text","text":". Feature availability can be queried using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)"},{"text":".","type":"text"}]},"doc://com.nixsensor.universalsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"url":"\/documentation\/nixuniversalsdk\/licensemanager","title":"LicenseManager","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManager"}]},"doc://com.nixsensor.universalsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/featuresByNumber":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/featuresbynumber","type":"topic","role":"symbol","title":"featuresByNumber","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/featuresByNumber","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"featuresByNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"features"}],"abstract":[{"text":"Set of ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" containing the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"},{"type":"text","text":" values enabled by the current license."}]},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"LicenseManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LicenseManager"}]},{"value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allocations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypesByNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/expiry","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/featuresByNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/libraryVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/uuid"]},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/deactivate()","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)"],"anchor":"Type-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1uuid\/title","op":"replace","value":"uuid"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1uuid\/fragments","value":[{"text":"uuid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/title","value":"state","op":"replace"},{"value":[{"kind":"identifier","text":"state"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/fragments","op":"replace"},{"value":"activateWithOptions:andSignature:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"activateWithOptions:andSignature:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allocations\/title","value":"allocations"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allocations\/fragments","value":[{"kind":"identifier","text":"allocations"}],"op":"replace"},{"value":"DeviceType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title"},{"value":[{"text":"DeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1libraryVersion\/title","op":"replace","value":"libraryVersion"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1libraryVersion\/fragments","value":[{"text":"libraryVersion","kind":"identifier"}],"op":"replace"},{"value":"LicenseManagerStateACTIVE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments","op":"replace","value":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/title","value":"isDeviceTypeSupported:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"isDeviceTypeSupported:","kind":"identifier"}]},{"value":"allowedDeviceTypes","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allowedDeviceTypesByNumber\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1allowedDeviceTypesByNumber\/fragments","value":[{"text":"allowedDeviceTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title","op":"replace","value":"isFeatureEnabled:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isFeatureEnabled:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1expiry\/title","value":"expiry"},{"value":[{"kind":"identifier","text":"expiry"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1expiry\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1deactivate()\/title","op":"replace","value":"deactivate"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1deactivate()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"deactivate","kind":"identifier"}]},{"value":"LicenseFeature","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title"},{"value":[{"text":"LicenseFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle","value":[{"text":"LicenseFeature","kind":"identifier"}]},{"value":"LicenseManager","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title"},{"value":[{"text":"LicenseManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments"},{"value":[{"text":"LicenseManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1featuresByNumber\/title","value":"features"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1featuresByNumber\/fragments","op":"replace","value":[{"text":"features","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}