{"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Observer"}],"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"Observer"}],"role":"symbol","symbolKind":"enum","externalID":"c:@M@NixUniversalSDK@E@Observer","title":"Observer"},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/observer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/observer"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","interfaceLanguage":"swift"},"abstract":[{"text":"Enum to describe the available options for reference observer","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1964","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"],"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fov","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fullName","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/intValue"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFov(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFullName(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromInt(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromUInt8(_:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"type":"conformsTo"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fromUInt8(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromUInt8(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromUInt8"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/observer\/fromuint8(_:)","role":"symbol","title":"fromUInt8(_:)","abstract":[{"text":"Helper to provide the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"reference","isActive":true},{"text":" enum for a particular byte value. If an invalid value is provided, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"},{"type":"text","text":" is returned."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/Equatable-Implementations":{"abstract":[],"type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/observer\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/Equatable-Implementations","role":"collectionGroup"},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIE1931","kind":"identifier"}],"abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"title":"Observer.CIE1931","url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ObserverCIE1931","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/intValue":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/intValue","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Integer raw value for this "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"}],"url":"\/documentation\/nixuniversalsdk\/observer\/intvalue","type":"topic","title":"intValue"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fullName":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fullName","title":"fullName","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Full name for display in UI (e.g. - ‘2°’ for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"reference","isActive":true},{"text":")","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/observer\/fullname","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1964":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIE1964","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1964","title":"Observer.CIE1964","abstract":[{"text":"Observer defined by CIE1964 (10 degree)","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/observer\/cie1964","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverCIE1964"}]},"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fromInt(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromInt(_:)","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/fromint(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromInt"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"title":"fromInt(_:)","abstract":[{"type":"text","text":"Helper to provide the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"},{"text":" enum for a particular integer value. If an invalid value is provided, ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE","type":"reference","isActive":true},{"text":" is returned.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fov":{"kind":"symbol","abstract":[{"type":"text","text":"Field of view (i.e. - 2 or 10)"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fov","title":"fov","url":"\/documentation\/nixuniversalsdk\/observer\/fov","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fov","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/RawRepresentable-Implementations","url":"\/documentation\/nixuniversalsdk\/observer\/rawrepresentable-implementations","kind":"article","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fromFullName(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFullName(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fromFullName","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"url":"\/documentation\/nixuniversalsdk\/observer\/fromfullname(_:)","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Helper to provide the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"reference","isActive":true},{"text":" enum for a particular illuminant name. If an invalid name is provided, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"},{"text":" is returned.","type":"text"}],"title":"fromFullName(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}],"url":"\/documentation\/nixuniversalsdk\/observer","navigatorTitle":[{"kind":"identifier","text":"Observer"}],"type":"topic","title":"Observer"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fromFov(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFov(_:)","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/observer\/fromfov(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromFov","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"title":"fromFov(_:)","abstract":[{"text":"Helper to provide the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","isActive":true},{"type":"text","text":" enum for a particular observer field-of-view (FOV). Valid options are 2 and 10; if an invalid value is provided, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"},{"type":"text","text":" is returned."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/init(rawValue:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/NONE":{"title":"Observer.NONE","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverNONE"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"NONE","kind":"identifier"}],"abstract":[{"text":"Observer defined by CIE1964 (10 degree)","type":"text"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/none"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"Observer","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"Observer"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"Observer","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1964","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"],"generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Observer"},{"text":": ","kind":"text"},{"text":"uint8_t","preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title","value":"ObserverCIE1931","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ObserverCIE1931"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments"},{"op":"replace","value":"ObserverCIE1964","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1964\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1964\/fragments","op":"replace","value":[{"text":"ObserverCIE1964","kind":"identifier"}]},{"value":"Observer","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","op":"replace","value":[{"text":"Observer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","value":[{"kind":"identifier","text":"Observer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1NONE\/title","value":"ObserverNONE"},{"value":[{"kind":"identifier","text":"ObserverNONE"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1NONE\/fragments"}]}]}