{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"}],"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ScanMode","symbolKind":"enum","role":"symbol","title":"ScanMode"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M1","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA"]},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fullName","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/intValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/legacyValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/numberValue"],"anchor":"Instance-Properties"},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromInt(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromNumber(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromString(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromUInt8(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/unwrapSet(_:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanMode"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode"]}],"references":{"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fullName":{"type":"topic","abstract":[{"type":"text","text":"Helper to get ‘friendly’ name for this "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"reference"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fullName","url":"\/documentation\/nixuniversalsdk\/scanmode\/fullname","kind":"symbol","title":"fullName","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M0":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/scanmode\/m0","title":"ScanMode.M0","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"M0","kind":"identifier"}],"abstract":[{"type":"text","text":"M0 conditions (ISO 13655)"}],"navigatorTitle":[{"kind":"identifier","text":"ScanModeM0"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/unwrapSet(_:)":{"url":"\/documentation\/nixuniversalsdk\/scanmode\/unwrapset(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unwrapSet","kind":"identifier"},{"kind":"text","text":"("},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":">?) -> "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/unwrapSet(_:)","role":"symbol","abstract":[{"type":"text","text":"Helper to unwrap a set of "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" values to a set of "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true,"type":"reference"},{"text":" values","type":"text"}],"kind":"symbol","type":"topic","title":"unwrapSet(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/scanmode\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","abstract":[],"kind":"article","url":"\/documentation\/nixuniversalsdk\/scanmode\/equatable-implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/intValue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/intValue","abstract":[{"type":"text","text":"Integer representation of this "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"},{"type":"text","text":" enum"}],"kind":"symbol","title":"intValue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/intvalue","type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/numberValue":{"kind":"symbol","title":"numberValue","abstract":[{"type":"text","text":"Helper to wrap this "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"reference","isActive":true},{"text":" enum in a ","type":"text"},{"code":"NSNumber","type":"codeVoice"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/numbervalue","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/numberValue","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M2":{"navigatorTitle":[{"kind":"identifier","text":"ScanModeM2"}],"abstract":[{"type":"text","text":"M2 conditions (ISO 13655)"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/m2","type":"topic","title":"ScanMode.M2","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"M2","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromNumber(_:)":{"abstract":[{"type":"text","text":"Helper to find a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"},{"type":"text","text":" enum from a "},{"type":"codeVoice","code":"NSNumber"},{"text":" value, or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","isActive":true},{"text":" for invalid input.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/fromnumber(_:)","title":"fromNumber(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromNumber","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromNumber(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/init(rawValue:)":{"url":"\/documentation\/nixuniversalsdk\/scanmode\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/init(rawValue:)","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","url":"\/documentation\/nixuniversalsdk\/scanmode","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}],"navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"title":"ScanMode","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromString(_:)":{"title":"fromString(_:)","abstract":[{"type":"text","text":"Helper to find a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"type":"text","text":" enum from a "},{"code":"String","type":"codeVoice"},{"text":" value, or ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","isActive":true,"type":"reference"},{"type":"text","text":" for invalid input."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromString(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/fromstring(_:)","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromUInt8(_:)":{"type":"topic","abstract":[{"type":"text","text":"Helper to find a "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"reference"},{"type":"text","text":" enum from a "},{"code":"uint8","type":"codeVoice"},{"type":"text","text":" value, or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA"},{"text":" for invalid input.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromUInt8"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromUInt8(_:)","url":"\/documentation\/nixuniversalsdk\/scanmode\/fromuint8(_:)","kind":"symbol","title":"fromUInt8(_:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M1":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"M1"}],"navigatorTitle":[{"kind":"identifier","text":"ScanModeM1"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/m1","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M1","abstract":[{"text":"M1 conditions (ISO 13655)","type":"text"}],"title":"ScanMode.M1","role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/NA":{"kind":"symbol","type":"topic","title":"ScanMode.NA","abstract":[{"text":"Unknown \/ undefined conditions","type":"text"}],"navigatorTitle":[{"text":"ScanModeNA","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NA"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/na"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/legacyValue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/legacyValue","abstract":[],"title":"legacyValue","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyValue"},{"kind":"text","text":": "},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/legacyvalue","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromInt(_:)":{"kind":"symbol","abstract":[{"text":"Helper to find a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"type":"text","text":" enum from an integer value, or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA"},{"text":" for invalid input.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/fromint(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromInt(_:)","title":"fromInt(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromInt","kind":"identifier"},{"kind":"text","text":"("},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode"}],"type":"topic"},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"ScanMode","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ScanMode"}]},{"value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M1","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"},{"kind":"text","text":": "},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M0\/title","value":"ScanModeM0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M0\/fragments","op":"replace","value":[{"text":"ScanModeM0","kind":"identifier"}]},{"value":"ScanModeM2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M2\/title"},{"op":"replace","value":[{"text":"ScanModeM2","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M2\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","op":"replace","value":"ScanMode"},{"op":"replace","value":[{"kind":"identifier","text":"ScanMode"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments"},{"value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M1\/title","op":"replace","value":"ScanModeM1"},{"op":"replace","value":[{"kind":"identifier","text":"ScanModeM1"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M1\/fragments"},{"op":"replace","value":"ScanModeNA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/title"},{"op":"replace","value":[{"text":"ScanModeNA","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/fragments"}]}]}