{"metadata":{"roleHeading":"Article","modules":[{"name":"NixUniversalSDK"}],"role":"article","title":"Wrapper for Usage in C\/C++"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"abstract":[{"text":"Review an example project which provides a C\/C++ interface on macOS","type":"text"}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"},"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps"],"title":"Getting Started","anchor":"Getting-Started","generated":true}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For macOS applications that require a C\/C++ interface, it may be possible to use NixUniversalSDK indirectly. For example, the SDK download provides a project "},{"code":"example-macos-wrapper","type":"codeVoice"},{"type":"text","text":" which allows for its usage in C\/C++ applications."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This project contains single "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" instances. It provides a static interface to access these instances and also provides callbacks for device and scanner events. The project contains a basic implementation, but can be modified or expanded to better suit your specific application."}]},{"inlineContent":[{"text":"The wrapper project is part of the SDK examples which are available ","type":"text"},{"isActive":true,"identifier":"https:\/\/www.nixsensor.com\/sdk-ios","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"heading","text":"Building the wrapper project","level":3,"anchor":"Building-the-wrapper-project"},{"inlineContent":[{"type":"text","text":"TBD"}],"type":"paragraph"},{"type":"heading","text":"Using the wrapper in a C\/C++ project","anchor":"Using-the-wrapper-in-a-CC++-project","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"TBD"}]},{"type":"heading","anchor":"Modifying-or-extending-the-wrapper-project","level":3,"text":"Modifying or extending the wrapper project"},{"type":"paragraph","inlineContent":[{"text":"TBD","type":"text"}]},{"level":2,"text":"Next Steps","anchor":"Next-Steps","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Additional-Support","type":"reference"}]}]}]}]}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/wrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/wrapper"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"title":"Handling Measurement Data","abstract":[{"text":"Query measurement values including colorimetry, spectral reflectance, and density","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","role":"article","kind":"article","url":"\/documentation\/nixuniversalsdk\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"role":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","abstract":[{"text":"Enable Nix device functions with your license code","type":"text"}],"title":"Activating the SDK License","kind":"article","type":"topic","url":"\/documentation\/nixuniversalsdk\/activating-license"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"type":"topic","kind":"article","title":"Example Applications","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","role":"article","abstract":[{"text":"Explore source code for demo iOS and macOS applications","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/example-apps"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","abstract":[{"type":"text","text":"Review the changes made in this version of the library"}],"type":"topic","title":"Release Notes","role":"article","kind":"article","url":"\/documentation\/nixuniversalsdk\/release-notes"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"title":"Discovering and Connecting to Nix Devices","abstract":[{"type":"text","text":"Use the device scanner to discover Nix devices and open a connection"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","role":"article","kind":"article","url":"\/documentation\/nixuniversalsdk\/discovering-connecting"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"url":"\/documentation\/nixuniversalsdk\/idevicescanner","role":"symbol","abstract":[{"type":"text","text":"Protocol implemented by the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceScanner","kind":"identifier"}],"title":"IDeviceScanner","navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"title":"Adding to Your Xcode Project","abstract":[{"type":"text","text":"Add the library bundle to your project and declare peripheral uses"}],"kind":"article","url":"\/documentation\/nixuniversalsdk\/add-to-xcode","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"abstract":[{"text":"Take measurements, set device options, and query device properties","type":"text"}],"title":"Device Operations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/device-operations","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"type":"topic","title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":".","type":"text"}]},"https://www.nixsensor.com/sdk-ios":{"identifier":"https:\/\/www.nixsensor.com\/sdk-ios","titleInlineContent":[{"type":"text","text":"online"}],"title":"online","type":"link","url":"https:\/\/www.nixsensor.com\/sdk-ios"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK#Additional-Support":{"url":"\/documentation\/nixuniversalsdk#Additional-Support","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Additional-Support","type":"topic","title":"Additional Support","abstract":[],"kind":"section"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps"],"anchor":"Getting-Started"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","value":"IDeviceScanner"},{"value":[{"kind":"identifier","text":"IDeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"IDeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace","value":"IDeviceCompat"},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"value":[{"kind":"identifier","text":"IDeviceCompat"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace"}]}]}