{"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@DeviceState@DeviceStateDISCONNECTED","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DISCONNECTED"}],"role":"symbol","navigatorTitle":[{"text":"DeviceStateDISCONNECTED","kind":"identifier"}],"title":"DeviceState.DISCONNECTED"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DISCONNECTED"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicestate\/disconnected"]},{"paths":["\/documentation\/nixuniversalsdk\/devicestate\/disconnected"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The device is disconnected.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/DISCONNECTED"},"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState/DISCONNECTED":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/DISCONNECTED","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicestate\/disconnected","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"DISCONNECTED","kind":"identifier"}],"type":"topic","title":"DeviceState.DISCONNECTED","abstract":[{"type":"text","text":"The device is disconnected."}],"navigatorTitle":[{"text":"DeviceStateDISCONNECTED","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"type":"text","text":"."}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestate","role":"symbol","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceState"}],"navigatorTitle":[{"text":"DeviceState","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","title":"DeviceState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DeviceStateDISCONNECTED","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"DeviceStateDISCONNECTED","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DeviceStateDISCONNECTED"}],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1DISCONNECTED\/title","value":"DeviceStateDISCONNECTED","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceStateDISCONNECTED"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1DISCONNECTED\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"op":"replace","value":"DeviceState","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/fragments","value":[{"kind":"identifier","text":"DeviceState"}]},{"value":[{"text":"DeviceState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/navigatorTitle"}]}]}