{"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@LicenseFeature@LicenseFeatureSPECTRAL_DATA","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"SPECTRAL_DATA","kind":"identifier"}],"title":"LicenseFeature.SPECTRAL_DATA","role":"symbol","navigatorTitle":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Provides access to spectral values via "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","isActive":true,"type":"reference"},{"type":"text","text":", if supported by the Nix device."}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/licensefeature\/spectral_data"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/licensefeature\/spectral_data"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"SPECTRAL_DATA","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"url":"\/documentation\/nixuniversalsdk\/licensefeature","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseFeature"}],"title":"LicenseFeature","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","role":"symbol","abstract":[{"text":"Enum describing the optional features that can be enabled by the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"type":"text","text":". Feature availability can be queried using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager","title":"LicenseManager","abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}],"navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature/SPECTRAL_DATA":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA","navigatorTitle":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"SPECTRAL_DATA","kind":"identifier"}],"type":"topic","title":"LicenseFeature.SPECTRAL_DATA","url":"\/documentation\/nixuniversalsdk\/licensefeature\/spectral_data","role":"symbol","abstract":[{"type":"text","text":"Provides access to spectral values via "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","isActive":true,"type":"reference"},{"type":"text","text":", if supported by the Nix device."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","title":"ISpectralData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","type":"topic","title":"isFeatureEnabled(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFeatureEnabled","kind":"identifier"},{"kind":"text","text":"("},{"text":"LicenseFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFeatureEnabled:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Helper to check if a particular "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"},{"text":" is enabled by the current license.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"LicenseFeatureSPECTRAL_DATA","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title","op":"replace","value":"LicenseFeature"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments","value":[{"text":"LicenseFeature","kind":"identifier"}]},{"value":[{"text":"LicenseFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager"},{"value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"LicenseManager"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1SPECTRAL_DATA\/title","op":"replace","value":"LicenseFeatureSPECTRAL_DATA"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1SPECTRAL_DATA\/fragments","value":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","op":"replace","value":"ISpectralData"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","op":"replace"},{"op":"replace","value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"value":"isFeatureEnabled:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"isFeatureEnabled:","kind":"identifier"}]}]}]}