{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"]]},"abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(toColorDataForReference:andType:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected reference white (defaults to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","isActive":true},{"type":"text","text":")"}]}],"name":"reference"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Output color type (defaults to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","isActive":true},{"type":"text","text":")"}]}],"name":"type"}]},{"kind":"mentions","mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"See also: ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","type":"reference"}],"type":"paragraph"}]}]}],"kind":"content"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"toColorData(reference:type:)","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"toColorDataForReference:andType:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData(im)toColorDataForReference:andType:","symbolKind":"method","required":true,"modules":[{"name":"NixUniversalSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(reference:type:)"]},{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(reference:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_2":{"role":"symbol","abstract":[{"type":"text","text":"White point using Illuminant D50 and 2 degree observer."}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","title":"ReferenceWhite.D50_2","navigatorTitle":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"D50_2"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toColorData(illuminant:observer:type:)":{"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(illuminant:observer:type:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"toColorData(illuminant:observer:type:)","role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"code":"nil","type":"codeVoice"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ReferenceWhite","kind":"identifier"}],"title":"ReferenceWhite","type":"topic","navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}],"title":"IMeasurementData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IMeasurementData"}],"type":"topic","abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true,"type":"reference"},{"text":" callback after a measurement is taken using an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance, or can be reconstructed from raw string data using ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"role":"symbol","title":"ColorType","abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true,"type":"reference"},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","kind":"symbol","navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorType","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colortype","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"kind":"symbol","abstract":[{"type":"text","text":"Report color value as CIEXYZ value on unity scale."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIEXYZ","kind":"identifier"}],"navigatorTitle":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","type":"topic","title":"ColorType.CIEXYZ"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toColorData(reference:type:)":{"abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(reference:type:)","navigatorTitle":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toColorDataForReference:andType:"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","type":"topic","required":true,"title":"toColorData(reference:type:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","text":"ColorType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier","text":"IColorData"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","kind":"article","title":"Handling Measurement Data","role":"article","type":"topic","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"url":"\/documentation\/nixuniversalsdk\/icolordata","kind":"symbol","title":"IColorData","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IColorData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"role":"symbol","title":"fromRaw(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","abstract":[{"type":"text","text":"Reconstructs a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the data is invalid."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromRaw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"title":"IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"role":"symbol","title":"DeviceResultCallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","abstract":[{"text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceResultCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"DeviceResultCallback","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"toColorDataForReference:andType:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForReference:andType:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","text":"id<IColorData>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"toColorDataForReference:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reference"},{"kind":"text","text":" "},{"kind":"identifier","text":"andType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"reference","content":[{"inlineContent":[{"type":"text","text":"Selected reference white (defaults to "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","type":"reference"},{"type":"text","text":")"}],"type":"paragraph"}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"Output color type (defaults to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","type":"reference"},{"text":")","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/title","value":"ReferenceWhiteD50_2"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(illuminant:observer:type:)\/title","value":"toColorDataForIlluminant:andObserver:andType:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(illuminant:observer:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","value":"IMeasurementData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","value":[{"text":"IMeasurementData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle","value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","value":"ColorType","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"kind":"identifier","text":"ColorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"text":"ColorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title","value":"ColorTypeCIEXYZ","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments","value":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(reference:type:)\/title","value":"toColorDataForReference:andType:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(reference:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toColorDataForReference:andType:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"kind":"identifier","text":"IColorData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","value":[{"kind":"identifier","text":"IColorData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"kind":"identifier","text":"IDeviceCompat"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace"}]}]}