{"metadata":{"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"IlluminantD75"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"D75","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@Illuminant@IlluminantD75","title":"Illuminant.D75","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/illuminant\/d75"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/illuminant\/d75"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"D75","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D75","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D75":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D75","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D75","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/d75","kind":"symbol","abstract":[],"role":"symbol","title":"Illuminant.D75","navigatorTitle":[{"kind":"identifier","text":"IlluminantD75"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"url":"\/documentation\/nixuniversalsdk\/illuminant","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","title":"Illuminant"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"IlluminantD75","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"IlluminantD75"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"IlluminantD75","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D75\/title","op":"replace","value":"IlluminantD75"},{"value":[{"text":"IlluminantD75","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D75\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","value":"Illuminant","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","op":"replace","value":[{"kind":"identifier","text":"Illuminant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"kind":"identifier","text":"Illuminant"}]}]}]}