{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"]]},"abstract":[{"text":"Full name for display in UI (e.g. - ‘D50’ for ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true,"type":"reference"},{"type":"text","text":")"}],"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"s:15NixUniversalSDK10IlluminantO8fullNameSSvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fullName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","title":"fullName","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/illuminant\/fullname"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fullName"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IlluminantD50"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/illuminant\/d50","title":"Illuminant.D50"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"type":"topic","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"role":"symbol","kind":"symbol","title":"Illuminant","url":"\/documentation\/nixuniversalsdk\/illuminant"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/fullName":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Full name for display in UI (e.g. - ‘D50’ for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true},{"text":")","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/fullname","kind":"symbol","role":"symbol","title":"fullName","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/fullName"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","value":"IlluminantD50","op":"replace"},{"op":"replace","value":[{"text":"IlluminantD50","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","value":"Illuminant","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"text":"Illuminant","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}