{"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/illuminant\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/illuminant\/none"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"]]},"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NONE"}],"navigatorTitle":[{"text":"IlluminantNONE","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@Illuminant@IlluminantNONE","title":"Illuminant.NONE"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NONE"}],"languages":["swift"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"role":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"kind":"symbol","title":"Illuminant","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/illuminant"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/NONE":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/none","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/NONE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NONE"}],"title":"Illuminant.NONE","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IlluminantNONE"}],"type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"IlluminantNONE"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"IlluminantNONE","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"IlluminantNONE"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"Illuminant","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title"},{"op":"replace","value":[{"text":"Illuminant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments"},{"value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle"},{"value":"IlluminantNONE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1NONE\/title"},{"value":[{"kind":"identifier","text":"IlluminantNONE"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1NONE\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}