{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fromRaw","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"raw","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"IMeasurementData","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"s:15NixUniversalSDK15MeasurementDataC7fromRawyAA012IMeasurementE0_pSgSSFZ","role":"symbol","roleHeading":"Type Method","modules":[{"name":"NixUniversalSDK"}],"title":"fromRaw(_:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromRaw","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"IMeasurementData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData"]]},"abstract":[{"type":"text","text":"Reconstructs a "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference"},{"type":"text","text":" instance from its raw string value, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the data is invalid."}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IMeasurementData"}],"title":"IMeasurementData","abstract":[{"type":"text","text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true},{"text":" callback after a measurement is taken using an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)"},{"text":".","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IMeasurementData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromRaw"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"text":"IMeasurementData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}],"title":"fromRaw(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Reconstructs a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"code":"nil","type":"codeVoice"},{"text":" if the data is invalid.","type":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData","url":"\/documentation\/nixuniversalsdk\/measurementdata","title":"MeasurementData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasurementData"}],"navigatorTitle":[{"kind":"identifier","text":"MeasurementData"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Class describing measurement data from a Nix device"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceResultCallback","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" instance."}],"kind":"symbol","title":"DeviceResultCallback","type":"topic","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"type":"topic","title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":".","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","value":"IMeasurementData","op":"replace"},{"value":[{"kind":"identifier","text":"IMeasurementData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle","value":[{"kind":"identifier","text":"IMeasurementData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/title","value":"MeasurementData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/fragments","value":[{"text":"MeasurementData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/navigatorTitle","value":[{"text":"MeasurementData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"text":"IDeviceCompat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}