{"deprecationSummary":[{"inlineContent":[{"text":"Use LicenseManager.uuid instead","type":"text"}],"type":"paragraph"}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"extendedModule":"NixUniversalSDK","platforms":[],"externalID":"s:15NixUniversalSDK14IDeviceScannerPAAE5sdkIdSSvp","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"sdkId"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/idevicescanner\/sdkid"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/sdkId"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner/sdkId":{"title":"sdkId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","abstract":[],"url":"\/documentation\/nixuniversalsdk\/idevicescanner\/sdkid","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/sdkId","deprecated":true,"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DeviceScanner","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","kind":"symbol","role":"symbol","title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicescanner","role":"symbol","abstract":[{"type":"text","text":"Protocol implemented by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","title":"IDeviceScanner"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DeviceScanner","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","value":"IDeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"IDeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle"}]}]}