{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/start(closure:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","text":"DeviceFoundCallback"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","text":"DeviceScannerState"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicescanner\/start(closure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicescanner\/start(closure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","kind":"typeIdentifier","text":"DeviceFoundCallback"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","text":"DeviceScannerState","kind":"typeIdentifier"}],"title":"start(closure:)","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@NixUniversalSDK@objc(cs)DeviceScanner(im)startWithClosure:","modules":[{"name":"NixUniversalSDK"}]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDeviceScanner.start(closure:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner/start(closure:)":{"role":"symbol","title":"start(closure:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/start(closure:)","url":"\/documentation\/nixuniversalsdk\/devicescanner\/start(closure:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"closure","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DeviceFoundCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka"},{"text":") -> ","kind":"text"},{"text":"DeviceScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"role":"symbol","title":"IDeviceScanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","abstract":[{"type":"text","text":"Protocol implemented by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/idevicescanner","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceFoundCallback":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback","url":"\/documentation\/nixuniversalsdk\/devicefoundcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceFoundCallback","kind":"identifier"}],"title":"DeviceFoundCallback","role":"symbol","navigatorTitle":[{"text":"DeviceFoundCallback","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Definition for a closure invoked when an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true,"type":"reference"},{"type":"text","text":" has discovered a supported Nix device"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate","abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"navigatorTitle":[{"text":"DeviceScannerState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","type":"topic","title":"DeviceScannerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"startWithClosure:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","text":"DeviceScannerState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startWithClosure:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"id<IDeviceCompat>","kind":"typeIdentifier"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"closure","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner~1start(closure:)\/title","op":"replace","value":"startWithClosure:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner~1start(closure:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithClosure:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","op":"replace","value":"IDeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}]},{"op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle"},{"op":"replace","value":"DeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle"},{"op":"replace","value":"DeviceScannerState","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title"},{"op":"replace","value":[{"text":"DeviceScannerState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScannerState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle"}]}]}