{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicetype\/mini"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/mini"]}],"kind":"symbol","abstract":[{"text":"Type for Nix Mini colorimeter","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"metadata":{"role":"symbol","title":"DeviceType.MINI","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@DeviceType@DeviceTypeMINI","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MINI"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeMINI"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MINI"}],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI":{"url":"\/documentation\/nixuniversalsdk\/devicetype\/mini","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"MINI","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceTypeMINI"}],"abstract":[{"type":"text","text":"Type for Nix Mini colorimeter"}],"title":"DeviceType.MINI"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype","title":"DeviceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DeviceTypeMINI","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeviceTypeMINI"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DeviceTypeMINI","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}]}},{"value":"DeviceTypeMINI","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI\/fragments","value":[{"kind":"identifier","text":"DeviceTypeMINI"}]},{"value":"DeviceType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","op":"replace","value":[{"text":"DeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle","value":[{"text":"DeviceType","kind":"identifier"}]}]}]}