{"sections":[],"abstract":[{"text":"Color difference using CIE1994 equation using constants recommended for graphic design.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94G"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIE94G","kind":"identifier"}],"role":"symbol","title":"ColorDifferenceType.CIE94G","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94G"}],"externalID":"c:@M@NixUniversalSDK@E@ColorDifferenceType@ColorDifferenceTypeCIE94G","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CIE94G","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94g"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94g"]}],"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE94G":{"kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94g","type":"topic","navigatorTitle":[{"text":"ColorDifferenceTypeCIE94G","kind":"identifier"}],"title":"ColorDifferenceType.CIE94G","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94G","abstract":[{"text":"Color difference using CIE1994 equation using constants recommended for graphic design.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIE94G","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"role":"symbol","title":"ColorDifferenceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorDifferenceType"}],"abstract":[{"type":"text","text":"Enum describing the available color difference (delta E) equations."}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceType"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/colordifferencetype"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ColorDifferenceTypeCIE94G","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94G"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94G"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94G\/title","value":"ColorDifferenceTypeCIE94G","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94G\/fragments","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94G"}]},{"op":"replace","value":"ColorDifferenceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}]},{"value":[{"kind":"identifier","text":"ColorDifferenceType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","op":"replace"}]}]}