{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"type","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorData(py)type","navigatorTitle":[{"text":"type","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","symbolKind":"property"},"sections":[],"abstract":[{"text":"Type of color data stored in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value","isActive":true,"type":"reference"},{"type":"text","text":" field."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colordata\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colordata\/type"]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/type","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/type":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of color data stored in the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value","isActive":true,"type":"reference"},{"type":"text","text":" field."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/type","url":"\/documentation\/nixuniversalsdk\/colordata\/type","title":"type","role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/value":{"kind":"symbol","abstract":[{"type":"text","text":"Color value (3 coordinates) in the format specified by "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/mode","isActive":true},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value","url":"\/documentation\/nixuniversalsdk\/colordata\/value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">"}],"role":"symbol","title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IColorData","kind":"identifier"}],"abstract":[{"text":"Protocol describing colorimetry data","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","title":"IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","role":"symbol","navigatorTitle":[{"text":"IColorData","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorData"}],"title":"ColorData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","type":"topic","abstract":[{"type":"text","text":"Class describing colorimetry data"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorData"}],"url":"\/documentation\/nixuniversalsdk\/colordata","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true,"type":"reference"},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ColorType"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype","title":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/mode":{"navigatorTitle":[{"text":"mode","kind":"identifier"}],"abstract":[{"type":"text","text":"Scan mode for this value."}],"title":"mode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/mode","type":"topic","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colordata\/mode","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"type","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1type\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1value\/title","value":"value"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1value\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","op":"replace","value":"IColorData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","value":[{"kind":"identifier","text":"IColorData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/title","op":"replace","value":"ColorData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/fragments","value":[{"text":"ColorData","kind":"identifier"}]},{"value":[{"text":"ColorData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/navigatorTitle","op":"replace"},{"value":"ColorType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"text":"ColorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","op":"replace","value":[{"text":"ColorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1mode\/title","value":"mode","op":"replace"},{"value":[{"kind":"identifier","text":"mode"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1mode\/fragments","op":"replace"}]}]}