{"abstract":[{"type":"text","text":"Report color value as CIELAB value."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIELAB","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/colortype\/cielab"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colortype\/cielab"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELAB"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIELAB","kind":"identifier"}],"navigatorTitle":[{"text":"ColorTypeCIELAB","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@ColorType@ColorTypeCIELAB","title":"ColorType.CIELAB","role":"symbol","roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"]]},"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","url":"\/documentation\/nixuniversalsdk\/colortype","kind":"symbol","title":"ColorType","role":"symbol","navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorType"}],"abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","type":"reference"},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIELAB":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIELAB","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colortype\/cielab","role":"symbol","abstract":[{"type":"text","text":"Report color value as CIELAB value."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELAB","navigatorTitle":[{"kind":"identifier","text":"ColorTypeCIELAB"}],"kind":"symbol","title":"ColorType.CIELAB","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","title":"IColorData","navigatorTitle":[{"kind":"identifier","text":"IColorData"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ColorTypeCIELAB","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ColorTypeCIELAB","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"ColorTypeCIELAB"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","value":"ColorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"text":"ColorType","kind":"identifier"}]},{"op":"replace","value":[{"text":"ColorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELAB\/title","value":"ColorTypeCIELAB","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELAB\/fragments","value":[{"text":"ColorTypeCIELAB","kind":"identifier"}],"op":"replace"},{"value":"IColorData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"text":"IColorData","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"IColorData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"}]}]}