{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIEXYZ","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Report color value as CIEXYZ value on unity scale."}],"metadata":{"externalID":"c:@M@NixUniversalSDK@E@ColorType@ColorTypeCIEXYZ","title":"ColorType.CIEXYZ","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CIEXYZ","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colortype\/ciexyz"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colortype\/ciexyz"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"title":"IColorData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IColorData","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/icolordata","navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","role":"symbol","abstract":[{"text":"Protocol describing colorimetry data","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"abstract":[{"text":"Report color value as CIEXYZ value on unity scale.","type":"text"}],"title":"ColorType.CIEXYZ","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIEXYZ","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorType"}],"url":"\/documentation\/nixuniversalsdk\/colortype","role":"symbol","navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"title":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","kind":"symbol","abstract":[{"text":"Enum to describe the base color data types available for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ColorTypeCIEXYZ","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title","value":"ColorTypeCIEXYZ","op":"replace"},{"value":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments"},{"value":"ColorType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"kind":"identifier","text":"ColorType"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"kind":"identifier","text":"ColorType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}