{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"BLE","kind":"identifier"}],"title":"InterfaceType.BLE","externalID":"c:@M@NixUniversalSDK@E@InterfaceType@InterfaceTypeBLE","symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"InterfaceTypeBLE","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"BLE","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/ble"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/ble"]}],"abstract":[{"text":"Device connects via Bluetooth (BLE) interface.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/BLE","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/BLE":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BLE"}],"navigatorTitle":[{"text":"InterfaceTypeBLE","kind":"identifier"}],"type":"topic","title":"InterfaceType.BLE","url":"\/documentation\/nixuniversalsdk\/interfacetype\/ble","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/BLE","abstract":[{"type":"text","text":"Device connects via Bluetooth (BLE) interface."}],"kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterfaceType"}],"abstract":[{"type":"text","text":"Enum describing the supported connection interface types for Nix devices."}],"navigatorTitle":[{"text":"InterfaceType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/interfacetype","title":"InterfaceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"InterfaceTypeBLE"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InterfaceTypeBLE"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"InterfaceTypeBLE","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"InterfaceTypeBLE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1BLE\/title"},{"value":[{"text":"InterfaceTypeBLE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1BLE\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/title","value":"InterfaceType","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/fragments","value":[{"kind":"identifier","text":"InterfaceType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/navigatorTitle","value":[{"text":"InterfaceType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}