{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"metadata":{"role":"symbol","title":"hashValue","roleHeading":"Instance Property","modules":[{"name":"NixUniversalSDK","relatedModules":["Swift"]}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@NixUniversalSDK@E@InterfaceType","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","extendedModule":"Swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/RawRepresentable-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/hashValue"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterfaceType"}],"abstract":[{"type":"text","text":"Enum describing the supported connection interface types for Nix devices."}],"navigatorTitle":[{"text":"InterfaceType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/interfacetype","title":"InterfaceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/hashValue":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/interfacetype\/hashvalue","title":"hashValue","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/hashValue","abstract":[],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/nixuniversalsdk\/interfacetype\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/RawRepresentable-Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"InterfaceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/title"},{"value":[{"kind":"identifier","text":"InterfaceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/navigatorTitle","value":[{"kind":"identifier","text":"InterfaceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}