{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EMPTY"}],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"title":"ReferenceWhite.EMPTY","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"EMPTY","kind":"identifier"}],"navigatorTitle":[{"text":"ReferenceWhiteEMPTY","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteEMPTY","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/empty"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/empty"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"abstract":[{"type":"text","text":"Unknown \/ other reference white point"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/EMPTY":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"EMPTY","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/empty","role":"symbol","abstract":[{"type":"text","text":"Unknown \/ other reference white point"}],"title":"ReferenceWhite.EMPTY","navigatorTitle":[{"text":"ReferenceWhiteEMPTY","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"title":"ReferenceWhite","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","url":"\/documentation\/nixuniversalsdk\/referencewhite","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"ReferenceWhiteEMPTY","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ReferenceWhiteEMPTY"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ReferenceWhiteEMPTY"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1EMPTY\/title","value":"ReferenceWhiteEMPTY"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhiteEMPTY"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1EMPTY\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ReferenceWhite"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}