{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/!=(_:_:)"],"title":"Operators","anchor":"Operators"}],"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/Equatable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/equatable-implementations"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/!=(_:_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"title":"ReferenceWhite","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","url":"\/documentation\/nixuniversalsdk\/referencewhite","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace"}]}]}