{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(illuminant:observer:)"]},{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(illuminant:observer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(toRgbValueForIlluminant:andObserver:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":">?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"illuminant","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected illuminant reference for output (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50"},{"text":")","type":"text"}]}]},{"name":"observer","content":[{"inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"reference"},{"text":")","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"See also: "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"sections":[],"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"metadata":{"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"title":"toRgbValue(illuminant:observer:)","symbolKind":"method","roleHeading":"Instance Method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"observer"},{"text":": ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">?"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(im)toRgbValueForIlluminant:andObserver:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toRgbValue(reference:)":{"title":"toRgbValue(reference:)","abstract":[{"type":"text","text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"required":true,"type":"topic","navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(reference:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?","kind":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"url":"\/documentation\/nixuniversalsdk\/observer","type":"topic","role":"symbol","title":"Observer","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"navigatorTitle":[{"text":"Observer","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"type":"topic","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"role":"symbol","kind":"symbol","title":"Illuminant","url":"\/documentation\/nixuniversalsdk\/illuminant"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","kind":"symbol","type":"topic","title":"ISpectralData","abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ISpectralData","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IlluminantD50"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/illuminant\/d50","title":"Illuminant.D50"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toRgbValue(illuminant:observer:)":{"abstract":[{"type":"text","text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(illuminant:observer:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"kind":"symbol","required":true,"title":"toRgbValue(illuminant:observer:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"title":"Observer.CIE1931","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverCIE1931"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIE1931","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"toRgbValueForIlluminant:andObserver:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"toRgbValueForIlluminant:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"kind":"text","text":") "},{"text":"illuminant","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"andObserver:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"illuminant","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected illuminant reference for output (defaults to "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","type":"reference"},{"text":")","type":"text"}]}]},{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"reference","isActive":true},{"type":"text","text":")"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toRgbValueForReference:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(reference:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer"},{"value":[{"text":"Observer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Observer"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","value":"Illuminant"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","op":"replace","value":[{"kind":"identifier","text":"Illuminant"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle","value":[{"text":"ISpectralData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","value":"IlluminantD50","op":"replace"},{"value":[{"text":"IlluminantD50","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(illuminant:observer:)\/title","value":"toRgbValueForIlluminant:andObserver:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(illuminant:observer:)\/fragments"},{"value":"ObserverCIE1931","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments","value":[{"text":"ObserverCIE1931","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}