{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)"},"metadata":{"externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(im)toRgbValueForReference:","roleHeading":"Instance Method","modules":[{"name":"NixUniversalSDK"}],"title":"toRgbValue(reference:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toRgbValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}],"required":true,"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(toRgbValueForReference:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Selected reference white (defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","isActive":true},{"text":")","type":"text"}],"type":"paragraph"}],"name":"reference"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"items":[{"content":[{"inlineContent":[{"text":"See also: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(reference:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(reference:)"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toRgbValue(illuminant:observer:)":{"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(illuminant:observer:)","title":"toRgbValue(illuminant:observer:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier","text":"Observer"},{"text":") -> ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toRgbValue(reference:)":{"title":"toRgbValue(reference:)","kind":"symbol","required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)","navigatorTitle":[{"kind":"identifier","text":"toRgbValueForReference:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reference"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":">?","kind":"text"}],"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(reference:)","role":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"title":"ISpectralData","url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISpectralData"}],"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_2":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}],"title":"ReferenceWhite.D50_2","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_2","kind":"symbol","abstract":[{"type":"text","text":"White point using Illuminant D50 and 2 degree observer."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"D50_2"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"url":"\/documentation\/nixuniversalsdk\/referencewhite","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"type":"topic","title":"ReferenceWhite","kind":"symbol","navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"toRgbValueForReference:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"toRgbValueForReference:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"toRgbValueForReference:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"reference"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"reference","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected reference white (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2"},{"type":"text","text":")"}]}]}]}},{"value":"toRgbValueForIlluminant:andObserver:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(illuminant:observer:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(illuminant:observer:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(reference:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForReference:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData","op":"replace"},{"op":"replace","value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments"},{"value":[{"kind":"identifier","text":"ISpectralData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle","op":"replace"},{"value":"ReferenceWhiteD50_2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/title"},{"op":"replace","value":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","op":"replace","value":"ReferenceWhite"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}