{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fov","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"]]},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/observer\/fov"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"property","title":"fov","roleHeading":"Instance Property","externalID":"s:15NixUniversalSDK8ObserverO3fovSivp","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fov"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"kind":"symbol","abstract":[{"type":"text","text":"Field of view (i.e. - 2 or 10)"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fov","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fov":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fov","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fov"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/fov","abstract":[{"type":"text","text":"Field of view (i.e. - 2 or 10)"}],"title":"fov"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"navigatorTitle":[{"text":"Observer","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/observer","type":"topic","title":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"text":"Observer","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"Observer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}