{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFullName(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/observer\/fromfullname(_:)"]}],"kind":"symbol","metadata":{"symbolKind":"method","title":"fromFullName(_:)","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","roleHeading":"Type Method","externalID":"s:15NixUniversalSDK8ObserverO12fromFullNameyACSSSgFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromFullName","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}]},"abstract":[{"type":"text","text":"Helper to provide the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","isActive":true},{"text":" enum for a particular illuminant name. If an invalid name is provided, ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE","type":"reference","isActive":true},{"type":"text","text":" is returned."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromFullName","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/NONE":{"title":"Observer.NONE","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverNONE"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"NONE","kind":"identifier"}],"abstract":[{"text":"Observer defined by CIE1964 (10 degree)","type":"text"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/none"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}],"url":"\/documentation\/nixuniversalsdk\/observer","navigatorTitle":[{"kind":"identifier","text":"Observer"}],"type":"topic","title":"Observer"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fromFullName(_:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFullName(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fromFullName","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}],"url":"\/documentation\/nixuniversalsdk\/observer\/fromfullname(_:)","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Helper to provide the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"reference","isActive":true},{"text":" enum for a particular illuminant name. If an invalid name is provided, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"},{"text":" is returned.","type":"text"}],"title":"fromFullName(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ObserverNONE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1NONE\/title"},{"value":[{"kind":"identifier","text":"ObserverNONE"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1NONE\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer"},{"value":[{"kind":"identifier","text":"Observer"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Observer"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle"}]}]}