{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Full name for display in UI (e.g. - ‘2°’ for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","isActive":true,"type":"reference"},{"type":"text","text":")"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/observer\/fullname"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fullName"},"metadata":{"symbolKind":"property","modules":[{"name":"NixUniversalSDK"}],"title":"fullName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:15NixUniversalSDK8ObserverO8fullNameSSvp","roleHeading":"Instance Property"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}],"url":"\/documentation\/nixuniversalsdk\/observer","navigatorTitle":[{"kind":"identifier","text":"Observer"}],"type":"topic","title":"Observer"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fullName":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fullName","title":"fullName","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Full name for display in UI (e.g. - ‘2°’ for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"reference","isActive":true},{"text":")","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/observer\/fullname","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIE1931","kind":"identifier"}],"abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"title":"Observer.CIE1931","url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ObserverCIE1931","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"Observer","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"kind":"identifier","text":"Observer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","op":"replace","value":[{"text":"Observer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title","value":"ObserverCIE1931","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments","value":[{"text":"ObserverCIE1931","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}