{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState"]]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Bluetooth scanner could not start because Bluetooth is not available on this mobile device."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_unavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_unavailable"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Case","externalID":"c:@M@NixUniversalSDK@E@DeviceScannerState@DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE"}],"title":"DeviceScannerState.ERROR_BLUETOOTH_UNAVAILABLE","symbolKind":"case","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_BLUETOOTH_UNAVAILABLE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_unavailable","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE"}],"title":"DeviceScannerState.ERROR_BLUETOOTH_UNAVAILABLE","abstract":[{"text":"Bluetooth scanner could not start because Bluetooth is not available on this mobile device.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"title":"DeviceScannerState","navigatorTitle":[{"text":"DeviceScannerState","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescannerstate","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceScannerState","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/idevicescanner","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Protocol implemented by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"title":"IDeviceScanner","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_UNAVAILABLE\/title","value":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_UNAVAILABLE\/fragments","value":[{"text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title","op":"replace","value":"DeviceScannerState"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","value":[{"text":"DeviceScannerState","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScannerState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","value":"IDeviceScanner","op":"replace"},{"value":[{"kind":"identifier","text":"IDeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","value":[{"kind":"identifier","text":"IDeviceScanner"}]}]}]}