{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"platforms":["macOS"]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INVALID_HARDWARE_ID","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"title":"DeviceScannerState.ERROR_INVALID_HARDWARE_ID","symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@DeviceScannerState@DeviceScannerStateERROR_INVALID_HARDWARE_ID"},"abstract":[{"text":"Bluetooth scanner could not start because an invalid hardware ID was provided.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate\/error_invalid_hardware_id"]},{"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate\/error_invalid_hardware_id"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_INVALID_HARDWARE_ID":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INVALID_HARDWARE_ID","navigatorTitle":[{"text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"role":"symbol","title":"DeviceScannerState.ERROR_INVALID_HARDWARE_ID","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_INVALID_HARDWARE_ID"}],"abstract":[{"type":"text","text":"Bluetooth scanner could not start because an invalid hardware ID was provided."}],"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_invalid_hardware_id"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceScannerState"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescannerstate","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","type":"reference"}],"title":"DeviceScannerState","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","navigatorTitle":[{"text":"DeviceScannerState","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicescanner","role":"symbol","abstract":[{"type":"text","text":"Protocol implemented by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","title":"IDeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_INVALID_HARDWARE_ID\/title","value":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","op":"replace"},{"op":"replace","value":[{"text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_INVALID_HARDWARE_ID\/fragments"},{"op":"replace","value":"DeviceScannerState","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title"},{"value":[{"kind":"identifier","text":"DeviceScannerState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DeviceScannerState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","value":"IDeviceScanner","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"IDeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments"},{"value":[{"text":"IDeviceScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle"}]}]}