{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/densitydata\/init(lambda:reflectance:mode:status:)"]}],"sections":[],"metadata":{"externalID":"s:15NixUniversalSDK11DensityDataC6lambda11reflectance4mode6statusACSaySiG_SaySfGAA8ScanModeOAA0D6StatusOtcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lambda"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"reflectance"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":">, "},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"kind":"text","text":")"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"init","role":"symbol","title":"init(lambda:reflectance:mode:status:)","roleHeading":"Initializer"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lambda","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">, "},{"text":"reflectance","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"},{"kind":"text","text":" = .M2, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier","text":"DensityStatus"},{"kind":"text","text":" = .T)"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/init(lambda:reflectance:mode:status:)"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","title":"ScanMode","navigatorTitle":[{"kind":"identifier","text":"ScanMode"}],"type":"topic","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"navigatorTitle":[{"kind":"identifier","text":"DensityStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DensityStatus","kind":"identifier"}],"title":"DensityStatus","url":"\/documentation\/nixuniversalsdk\/densitystatus","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for density status"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData":{"navigatorTitle":[{"kind":"identifier","text":"DensityData"}],"abstract":[{"type":"text","text":"Class describing density data"}],"url":"\/documentation\/nixuniversalsdk\/densitydata","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DensityData","kind":"identifier"}],"kind":"symbol","title":"DensityData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/init(lambda:reflectance:mode:status:)":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/densitydata\/init(lambda:reflectance:mode:status:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/init(lambda:reflectance:mode:status:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lambda","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":">, ","kind":"text"},{"text":"reflectance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">, "},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","text":"DensityStatus"},{"kind":"text","text":")"}],"title":"init(lambda:reflectance:mode:status:)","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","value":"ScanMode"},{"value":[{"kind":"identifier","text":"ScanMode"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ScanMode"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","op":"replace"},{"value":"DensityStatus","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title"},{"value":[{"kind":"identifier","text":"DensityStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DensityStatus"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle"},{"value":"DensityData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DensityData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DensityData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}