{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/densitydata\/status"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/densitydata\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"DensityStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/status"},"metadata":{"externalID":"c:@M@NixUniversalSDK@objc(cs)DensityData(py)status","roleHeading":"Instance Property","title":"status","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"status","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier"}]},"sections":[],"abstract":[{"type":"text","text":"Density status for this value"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","title":"DensityStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DensityStatus"}],"navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/densitystatus","abstract":[{"type":"text","text":"Enum to describe the available options for density status"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/status":{"abstract":[{"type":"text","text":"Density status for this value"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"role":"symbol","type":"topic","title":"status","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/status","url":"\/documentation\/nixuniversalsdk\/densitydata\/status","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData","navigatorTitle":[{"text":"DensityData","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/densitydata","title":"DensityData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DensityData","kind":"identifier"}],"abstract":[{"type":"text","text":"Class describing density data"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"status","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"status"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DensityStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","value":"DensityStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments","value":[{"kind":"identifier","text":"DensityStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","value":[{"text":"DensityStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1status\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/title","value":"DensityData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/fragments","value":[{"kind":"identifier","text":"DensityData"}]},{"value":[{"kind":"identifier","text":"DensityData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/navigatorTitle","op":"replace"}]}]}