{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/invalidatefieldcalibration(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/invalidatefieldcalibration(completion:)"]}],"abstract":[{"type":"text","text":"Invalidates current field calibration date, so that "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","isActive":true},{"text":" is reported as ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", if supported by the device.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/invalidateFieldCalibration(completion:)"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"invalidateFieldCalibration","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","text":"DeviceResultCallback","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"Closure which will provide command status on completion.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"invalidateFieldCalibrationWithCompletion:"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat(im)invalidateFieldCalibrationWithCompletion:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidateFieldCalibration","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DeviceResultCallback","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","required":true,"title":"invalidateFieldCalibration(completion:)","symbolKind":"method","modules":[{"name":"NixUniversalSDK"}]},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"title":"DeviceResultCallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"DeviceResultCallback","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"text":" instance.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/invalidateFieldCalibration(completion:)":{"abstract":[{"text":"Invalidates current field calibration date, so that ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","isActive":true},{"type":"text","text":" is reported as "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if supported by the device."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/invalidateFieldCalibration(completion:)","navigatorTitle":[{"text":"invalidateFieldCalibrationWithCompletion:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/invalidatefieldcalibration(completion:)","kind":"symbol","required":true,"title":"invalidateFieldCalibration(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"invalidateFieldCalibration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DeviceResultCallback","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"kind":"text","text":")"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":".","type":"text"}],"title":"IDeviceCompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/fieldCalibrationDue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldCalibrationDue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"fieldCalibrationDue","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/fieldcalibrationdue","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fieldCalibrationDue"}],"kind":"symbol","abstract":[{"text":"Flag to indicate if in-field calibration is recommended for this device at this time (if supported). This value is only valid after opening a connection and is a function of both time and ambient temperature. This value also updates each time a measurement is completed.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescanner","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus":{"title":"CommandStatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommandStatus"}],"navigatorTitle":[{"text":"CommandStatus","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/commandstatus","kind":"symbol","abstract":[{"text":"Enum describing the possible status of commands executed by the Nix device, as provided in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"invalidateFieldCalibrationWithCompletion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"invalidateFieldCalibrationWithCompletion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"invalidateFieldCalibrationWithCompletion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@CommandStatus","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus","text":"CommandStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSNumber *,id<IMeasurementData>>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"Closure which will provide command status on completion.","type":"text"}],"type":"paragraph"}]}]}},{"value":"invalidateFieldCalibrationWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1invalidateFieldCalibration(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"invalidateFieldCalibrationWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1invalidateFieldCalibration(completion:)\/fragments"},{"value":"IDeviceCompat","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace"},{"op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationDue\/title","value":"fieldCalibrationDue","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationDue\/fragments","value":[{"text":"fieldCalibrationDue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"value":[{"text":"DeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"text":"DeviceScanner","kind":"identifier"}],"op":"replace"},{"value":"CommandStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/title","op":"replace"},{"value":[{"text":"CommandStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/navigatorTitle","value":[{"kind":"identifier","text":"CommandStatus"}],"op":"replace"}]}]}