{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(measureWithModes:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"measure","kind":"identifier"},{"kind":"text","text":"("},{"text":"modes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":">, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","kind":"typeIdentifier","text":"DeviceResultCallback"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"modes","content":[{"inlineContent":[{"type":"text","text":"Scan modes to select. Set must contain "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" values matching "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"text":" enum values","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Closure which will provide command status on completion.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"See also: "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/measure(modes:completion:)-18cni"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/measure(modes:completion:)-18cni"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Run a measurement in the specified scan modes. If any unsupported modes are selected, the measurement will fail with status code "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED","isActive":true,"type":"reference"},{"text":". This method is asynchronous and will return immediately.","type":"text"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-71wc2"],"anchor":"IDeviceCompat-Implementations","title":"IDeviceCompat Implementations"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"measureWithModes:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"measure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","kind":"typeIdentifier","text":"DeviceResultCallback"},{"text":")","kind":"text"}],"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat(im)measureWithModes:completion:","role":"symbol","roleHeading":"Instance Method","required":true,"title":"measure(modes:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"type":"topic","title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":".","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(modes:completion:)-18cni":{"abstract":[{"type":"text","text":"Run a measurement in the specified scan modes. If any unsupported modes are selected, the measurement will fail with status code "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED"},{"text":". This method is asynchronous and will return immediately.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(modes:completion:)-18cni","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"measure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","defaultImplementations":1,"kind":"symbol","title":"measure(modes:completion:)","navigatorTitle":[{"kind":"identifier","text":"measureWithModes:completion:"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceResultCallback","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" instance."}],"kind":"symbol","title":"DeviceResultCallback","type":"topic","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(completion:)":{"kind":"symbol","navigatorTitle":[{"text":"measure:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"measure","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DeviceResultCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(completion:)","abstract":[{"type":"text","text":"Run a measurement for all supported scan modes. This method is asynchronous and will return immediately."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)","title":"measure(completion:)","required":true,"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CommandStatus"}],"abstract":[{"text":"Enum describing the possible status of commands executed by the Nix device, as provided in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/commandstatus","title":"CommandStatus","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus","role":"symbol","navigatorTitle":[{"text":"CommandStatus","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","url":"\/documentation\/nixuniversalsdk\/scanmode","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}],"navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"title":"ScanMode","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(modes:completion:)-71wc2":{"abstract":[{"type":"text","text":"Run a measurement in the specified scan modes. If any unsupported modes are selected, the measurement will fail with status code "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED"},{"text":". This method is asynchronous and will return immediately.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(modes:completion:)-71wc2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-71wc2","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"measure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol","title":"measure(modes:completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus/ERROR_NOT_SUPPORTED":{"abstract":[{"type":"text","text":"Status code indicating that the command was aborted because the it was not supported by the Nix device instance."}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/commandstatus\/error_not_supported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_NOT_SUPPORTED","kind":"identifier"}],"navigatorTitle":[{"text":"CommandStatusERROR_NOT_SUPPORTED","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED","title":"CommandStatus.ERROR_NOT_SUPPORTED"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"measureWithModes:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"measureWithModes:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"measureWithModes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modes"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus","text":"CommandStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@CommandStatus","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSDictionary<NSNumber *,id<IMeasurementData>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"modes","content":[{"type":"paragraph","inlineContent":[{"text":"Scan modes to select. Set must contain ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"text":" values matching ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"reference"},{"type":"text","text":" enum values"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Closure which will provide command status on completion."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat","op":"replace"},{"value":[{"kind":"identifier","text":"IDeviceCompat"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"kind":"identifier","text":"IDeviceCompat"}],"op":"replace"},{"op":"replace","value":"measureWithModes:completion:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(modes:completion:)-18cni\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(modes:completion:)-18cni\/fragments","value":[{"kind":"text","text":"- "},{"text":"measureWithModes:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(completion:)\/title","op":"replace","value":"measure:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"measure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(completion:)\/fragments"},{"value":"CommandStatus","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/fragments","value":[{"text":"CommandStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/navigatorTitle","op":"replace","value":[{"text":"CommandStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","op":"replace","value":"ScanMode"},{"value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","value":[{"text":"ScanMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_NOT_SUPPORTED\/title","value":"CommandStatusERROR_NOT_SUPPORTED","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_NOT_SUPPORTED\/fragments","value":[{"text":"CommandStatusERROR_NOT_SUPPORTED","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}