{"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"I"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"DensityStatusI","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@DensityStatus@DensityStatusI","modules":[{"name":"NixUniversalSDK"}],"title":"DensityStatus.I"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"I","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Status I (ISO 5-3:2009)"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/densitystatus\/i"]},{"paths":["\/documentation\/nixuniversalsdk\/densitystatus\/i"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/I"},"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/I":{"url":"\/documentation\/nixuniversalsdk\/densitystatus\/i","role":"symbol","navigatorTitle":[{"text":"DensityStatusI","kind":"identifier"}],"title":"DensityStatus.I","kind":"symbol","abstract":[{"text":"Status I (ISO 5-3:2009)","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/I","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"I"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","url":"\/documentation\/nixuniversalsdk\/densitystatus","type":"topic","abstract":[{"text":"Enum to describe the available options for density status","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DensityStatus"}],"title":"DensityStatus","navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"DensityStatusI","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DensityStatusI"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DensityStatusI","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DensityStatusI","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1I\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1I\/fragments","value":[{"text":"DensityStatusI","kind":"identifier"}],"op":"replace"},{"value":"DensityStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","op":"replace"},{"value":[{"text":"DensityStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","op":"replace","value":[{"text":"DensityStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}