{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"CommandStatus.WARNING_TEMPERATURE","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WARNING_TEMPERATURE"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@NixUniversalSDK@E@CommandStatus@CommandStatusWARNING_TEMPERATURE","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"CommandStatusWARNING_TEMPERATURE","kind":"identifier"}]},"abstract":[{"type":"text","text":"Status code indicating that the in-field calibration operation completed successfully, but a temperature warning was issued (i.e. - the ambient temperature of the device is currently outside of the recommended range). This status is only possible after a "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","type":"reference","isActive":true},{"type":"text","text":" command."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WARNING_TEMPERATURE"}],"platforms":["macOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/commandstatus\/warning_temperature"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/commandstatus\/warning_temperature"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/WARNING_TEMPERATURE"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance."}],"navigatorTitle":[{"kind":"identifier","text":"DeviceResultCallback"}],"title":"DeviceResultCallback","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceResultCallback","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/runFieldCalibration(tileString:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"runFieldCalibration:completion:"}],"abstract":[{"type":"text","text":"Start field calibration using provided reference tile, if supported. Upon executing this command, the scan of the reference tile will begin immediately. The user MUST be prompted to place the device onto the reference tile BEFORE this method is executed. This method is asynchronous and will return immediately."},{"type":"text","text":" "},{"text":"This command requires data from the reference tile QR code. As the format varies between different device types, the string data should be provided exactly as decoded from the QR code.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/runfieldcalibration(tilestring:completion:)","required":true,"title":"runFieldCalibration(tileString:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"runFieldCalibration"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tileString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus/WARNING_TEMPERATURE":{"title":"CommandStatus.WARNING_TEMPERATURE","url":"\/documentation\/nixuniversalsdk\/commandstatus\/warning_temperature","kind":"symbol","abstract":[{"type":"text","text":"Status code indicating that the in-field calibration operation completed successfully, but a temperature warning was issued (i.e. - the ambient temperature of the device is currently outside of the recommended range). This status is only possible after a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","isActive":true},{"text":" command.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/WARNING_TEMPERATURE","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WARNING_TEMPERATURE"}],"navigatorTitle":[{"text":"CommandStatusWARNING_TEMPERATURE","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus":{"abstract":[{"text":"Enum describing the possible status of commands executed by the Nix device, as provided in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"CommandStatus","kind":"identifier"}],"type":"topic","title":"CommandStatus","role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/commandstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CommandStatus","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CommandStatusWARNING_TEMPERATURE"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"CommandStatusWARNING_TEMPERATURE","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"CommandStatusWARNING_TEMPERATURE"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/title","value":"runFieldCalibration:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"runFieldCalibration:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1WARNING_TEMPERATURE\/title","value":"CommandStatusWARNING_TEMPERATURE"},{"value":[{"kind":"identifier","text":"CommandStatusWARNING_TEMPERATURE"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1WARNING_TEMPERATURE\/fragments"},{"value":"CommandStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/title","op":"replace"},{"value":[{"text":"CommandStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/fragments","op":"replace"},{"op":"replace","value":[{"text":"CommandStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}