{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"symbolKind":"method","title":"interpolate(lT:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interpolate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lT"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"interpolateAtLt:"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(im)interpolateAtLt:","roleHeading":"Instance Method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/interpolate(lt:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/interpolate(lt:)"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interpolate(lT:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interpolate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lT"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Wavelength (nm) at which to query the interpolated reflectance","type":"text"}]}],"name":"lT"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Interpolated reflectance value at lT","type":"text"}]}]}],"abstract":[{"type":"text","text":"Provides an interpolated reflectance value at a specified wavelength value using natural cubic spines. The cubic splines are evaluated at the points specified by "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value","isActive":true},{"text":". Interpolated values are evaluated using natural cubic splines.","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/interpolate(lT:)":{"kind":"symbol","title":"interpolate(lT:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"interpolateAtLt:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interpolate(lT:)","abstract":[{"text":"Provides an interpolated reflectance value at a specified wavelength value using natural cubic spines. The cubic splines are evaluated at the points specified by ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value","isActive":true,"type":"reference"},{"type":"text","text":". Interpolated values are evaluated using natural cubic splines."}],"type":"topic","role":"symbol","url":"\/documentation\/nixuniversalsdk\/spectraldata\/interpolate(lt:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/value":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":">"}],"type":"topic","abstract":[{"type":"text","text":"Spectral reflectance values. Each entry "},{"type":"codeVoice","code":"i"},{"text":" in this array corresponds to a wavelength value in ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","type":"reference","isActive":true},{"type":"text","text":" at the same index."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value","title":"value","url":"\/documentation\/nixuniversalsdk\/spectraldata\/value","navigatorTitle":[{"kind":"identifier","text":"value"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/lambda":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lambda","kind":"identifier"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/lambda","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","type":"topic","title":"lambda","navigatorTitle":[{"text":"lambda","kind":"identifier"}],"abstract":[{"text":"Wavelength values. Each entry ","type":"text"},{"type":"codeVoice","code":"i"},{"text":" in this array corresponds to a spectral value in ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value","type":"reference","isActive":true},{"text":" at the same index.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpectralData"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","type":"topic","title":"SpectralData","navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"abstract":[{"text":"Class describing spectral data","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"interpolateAtLt:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interpolateAtLt:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"interpolateAtLt:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"lT"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1interpolate(lT:)\/title","op":"replace","value":"interpolateAtLt:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interpolateAtLt:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1interpolate(lT:)\/fragments"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1value\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1lambda\/title","value":"lambda"},{"value":[{"text":"lambda","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1lambda\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","value":"SpectralData"},{"value":[{"text":"SpectralData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","value":[{"kind":"identifier","text":"SpectralData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}