{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"text":"ScanMode","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/mode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"mode"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(py)mode","role":"symbol","title":"mode"},"abstract":[{"text":"Scan mode for this measurement.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/mode"]},{"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/mode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/mode":{"navigatorTitle":[{"kind":"identifier","text":"mode"}],"title":"mode","role":"symbol","abstract":[{"text":"Scan mode for this measurement.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/spectraldata\/mode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/mode"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpectralData"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","type":"topic","title":"SpectralData","navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"abstract":[{"text":"Class describing spectral data","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"url":"\/documentation\/nixuniversalsdk\/scanmode","title":"ScanMode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","navigatorTitle":[{"kind":"identifier","text":"ScanMode"}],"abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanMode"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mode","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"mode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1mode\/title","value":"mode","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1mode\/fragments","op":"replace","value":[{"text":"mode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","op":"replace","value":"SpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","value":[{"kind":"identifier","text":"SpectralData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","op":"replace","value":[{"text":"SpectralData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","value":"ScanMode"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","op":"replace","value":[{"text":"ScanMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","value":[{"kind":"identifier","text":"ScanMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}