{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(illuminant:observer:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(illuminant:observer:type:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"},{"kind":"text","text":" = .D50, "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","text":"Observer","kind":"typeIdentifier"},{"text":" = .CIE1931, ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"text":" = .CIEXYZ) -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"text":"?","kind":"text"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"illuminant","content":[{"inlineContent":[{"text":"Selected illuminant reference for output (defaults to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true,"type":"reference"},{"type":"text","text":")"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931"},{"type":"text","text":")"}],"type":"paragraph"}],"name":"observer"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Output color type (defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","isActive":true},{"type":"text","text":")"}]}],"name":"type"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"See also: "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","type":"reference"}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if an invalid white point is specified.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"method","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(im)toColorDataForIlluminant:andObserver:andType:","roleHeading":"Instance Method","title":"toColorData(illuminant:observer:type:)","navigatorTitle":[{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toColorData(illuminant:observer:type:)":{"navigatorTitle":[{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"code":"nil","type":"codeVoice"},{"text":" if an invalid white point is specified.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toColorData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier","text":"Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"IColorData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"text":"?","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(illuminant:observer:type:)","type":"topic","title":"toColorData(illuminant:observer:type:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)","kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SpectralData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","navigatorTitle":[{"text":"SpectralData","kind":"identifier"}],"title":"SpectralData","abstract":[{"type":"text","text":"Class describing spectral data"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"title":"Observer.CIE1931","role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"navigatorTitle":[{"kind":"identifier","text":"ObserverCIE1931"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIE1931","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"navigatorTitle":[{"text":"Observer","kind":"identifier"}],"title":"Observer","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/observer","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"navigatorTitle":[{"kind":"identifier","text":"IlluminantD50"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D50","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/illuminant\/d50","type":"topic","title":"Illuminant.D50","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true,"type":"reference"},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorType"}],"title":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorType","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toColorData(reference:type:)":{"title":"toColorData(reference:type:)","role":"symbol","url":"\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(reference:type:)","abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if an invalid white point is specified."}],"navigatorTitle":[{"kind":"identifier","text":"toColorDataForReference:andType:"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"url":"\/documentation\/nixuniversalsdk\/icolordata","navigatorTitle":[{"text":"IColorData","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Protocol describing colorimetry data","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IColorData","kind":"identifier"}],"title":"IColorData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIEXYZ","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","title":"ColorType.CIEXYZ","type":"topic","url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","kind":"symbol","abstract":[{"type":"text","text":"Report color value as CIEXYZ value on unity scale."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"abstract":[{"text":"Enum to describe the available options for reference illuminant","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/illuminant","type":"topic","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"Illuminant"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"toColorDataForIlluminant:andObserver:andType:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier","text":"id<IColorData>"},{"kind":"text","text":") "},{"text":"toColorDataForIlluminant:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","text":"Illuminant"},{"text":") ","kind":"text"},{"text":"illuminant","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"andObserver:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","text":"Observer"},{"kind":"text","text":") "},{"text":"observer","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"andType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(illuminant:observer:type:)\/title","value":"toColorDataForIlluminant:andObserver:andType:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(illuminant:observer:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","value":"SpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","value":[{"text":"SpectralData","kind":"identifier"}]},{"value":[{"text":"SpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title","value":"ObserverCIE1931"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments","op":"replace","value":[{"kind":"identifier","text":"ObserverCIE1931"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","op":"replace","value":"Observer"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","op":"replace","value":[{"text":"Observer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","value":[{"kind":"identifier","text":"Observer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","value":"IlluminantD50"},{"value":[{"text":"IlluminantD50","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments"},{"value":"ColorType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title"},{"value":[{"text":"ColorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"kind":"identifier","text":"ColorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(reference:type:)\/title","value":"toColorDataForReference:andType:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(reference:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForReference:andType:"}],"op":"replace"},{"value":"IColorData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","op":"replace"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","op":"replace","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title","op":"replace","value":"ColorTypeCIEXYZ"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments","value":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}]},{"value":"Illuminant","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","op":"replace","value":[{"kind":"identifier","text":"Illuminant"}]},{"op":"replace","value":[{"text":"Illuminant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}