{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/BUSY_DATA_TRANSFER"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The device is busy with a data transfer to the host device."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BUSY_DATA_TRANSFER"}],"platforms":["macOS"],"languages":["swift"]}]}],"metadata":{"title":"DeviceState.BUSY_DATA_TRANSFER","navigatorTitle":[{"kind":"identifier","text":"DeviceStateBUSY_DATA_TRANSFER"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@E@DeviceState@DeviceStateBUSY_DATA_TRANSFER","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"BUSY_DATA_TRANSFER","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicestate\/busy_data_transfer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicestate\/busy_data_transfer"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDeviceCompat"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState/BUSY_DATA_TRANSFER":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/BUSY_DATA_TRANSFER","url":"\/documentation\/nixuniversalsdk\/devicestate\/busy_data_transfer","abstract":[{"type":"text","text":"The device is busy with a data transfer to the host device."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceStateBUSY_DATA_TRANSFER"}],"title":"DeviceState.BUSY_DATA_TRANSFER","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BUSY_DATA_TRANSFER"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DeviceState","kind":"identifier"}],"type":"topic","title":"DeviceState","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","url":"\/documentation\/nixuniversalsdk\/devicestate","navigatorTitle":[{"kind":"identifier","text":"DeviceState"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DeviceStateBUSY_DATA_TRANSFER"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DeviceStateBUSY_DATA_TRANSFER"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"DeviceStateBUSY_DATA_TRANSFER","kind":"identifier"}],"languages":["occ"]}]}},{"value":"IDeviceCompat","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1BUSY_DATA_TRANSFER\/title","value":"DeviceStateBUSY_DATA_TRANSFER"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceStateBUSY_DATA_TRANSFER"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1BUSY_DATA_TRANSFER\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/title","op":"replace","value":"DeviceState"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/fragments"},{"value":[{"text":"DeviceState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/navigatorTitle"}]}]}