{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"BUSY_SUBSCRIBING","kind":"identifier"}],"title":"DeviceState.BUSY_SUBSCRIBING","symbolKind":"case","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"DeviceStateBUSY_SUBSCRIBING","kind":"identifier"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@E@DeviceState@DeviceStateBUSY_SUBSCRIBING"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BUSY_SUBSCRIBING","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The device is busy; a connection has been opened but characteristic notification \/ subscriptions are pending."}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/BUSY_SUBSCRIBING","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestate\/busy_subscribing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestate\/busy_subscribing"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState/BUSY_SUBSCRIBING":{"title":"DeviceState.BUSY_SUBSCRIBING","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestate\/busy_subscribing","abstract":[{"type":"text","text":"The device is busy; a connection has been opened but characteristic notification \/ subscriptions are pending."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/BUSY_SUBSCRIBING","navigatorTitle":[{"text":"DeviceStateBUSY_SUBSCRIBING","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BUSY_SUBSCRIBING"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DeviceState","kind":"identifier"}],"type":"topic","title":"DeviceState","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","url":"\/documentation\/nixuniversalsdk\/devicestate","navigatorTitle":[{"kind":"identifier","text":"DeviceState"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDeviceCompat"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DeviceStateBUSY_SUBSCRIBING"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeviceStateBUSY_SUBSCRIBING"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DeviceStateBUSY_SUBSCRIBING"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","value":"DeviceStateBUSY_SUBSCRIBING","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1BUSY_SUBSCRIBING\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1BUSY_SUBSCRIBING\/fragments","value":[{"kind":"identifier","text":"DeviceStateBUSY_SUBSCRIBING"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/title","value":"DeviceState","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceState"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/navigatorTitle","value":[{"text":"DeviceState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}