{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestate\/busy_discovering"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestate\/busy_discovering"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@NixUniversalSDK@E@DeviceState@DeviceStateBUSY_DISCOVERING","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DeviceStateBUSY_DISCOVERING"}],"role":"symbol","title":"DeviceState.BUSY_DISCOVERING","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BUSY_DISCOVERING","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BUSY_DISCOVERING","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/BUSY_DISCOVERING","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The device is busy; a connection has been opened but services are being discovered."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"title":"IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState":{"navigatorTitle":[{"text":"DeviceState","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicestate","kind":"symbol","title":"DeviceState","role":"symbol","type":"topic","abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceState","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState/BUSY_DISCOVERING":{"role":"symbol","abstract":[{"type":"text","text":"The device is busy; a connection has been opened but services are being discovered."}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState\/BUSY_DISCOVERING","title":"DeviceState.BUSY_DISCOVERING","navigatorTitle":[{"text":"DeviceStateBUSY_DISCOVERING","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BUSY_DISCOVERING","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicestate\/busy_discovering","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DeviceStateBUSY_DISCOVERING"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceStateBUSY_DISCOVERING"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DeviceStateBUSY_DISCOVERING"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace","value":"IDeviceCompat"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/title","op":"replace","value":"DeviceState"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/fragments","op":"replace","value":[{"text":"DeviceState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/navigatorTitle","op":"replace","value":[{"text":"DeviceState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1BUSY_DISCOVERING\/title","op":"replace","value":"DeviceStateBUSY_DISCOVERING"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState~1BUSY_DISCOVERING\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceStateBUSY_DISCOVERING"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}