{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The license has failed to activate because the signature was invalid. Verify that the correct  options and signature were used when calling "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","type":"reference"},{"type":"text","text":". Contact the Nix SDK support team if this error persists."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE"}],"symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"title":"LicenseManagerState.ERROR_LICENSE_BAD_SIGNATURE","externalID":"c:@M@NixUniversalSDK@E@LicenseManagerState@LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_LICENSE_BAD_SIGNATURE"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_BAD_SIGNATURE"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_bad_signature"]},{"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_bad_signature"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE_BAD_SIGNATURE"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseManagerState"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LicenseManagerState","kind":"identifier"}],"kind":"symbol","type":"topic","title":"LicenseManagerState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ERROR_LICENSE_BAD_SIGNATURE":{"kind":"symbol","title":"LicenseManagerState.ERROR_LICENSE_BAD_SIGNATURE","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_bad_signature","role":"symbol","navigatorTitle":[{"text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","kind":"identifier"}],"type":"topic","abstract":[{"text":"The license has failed to activate because the signature was invalid. Verify that the correct  options and signature were used when calling ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","type":"reference","isActive":true},{"type":"text","text":". Contact the Nix SDK support team if this error persists."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE_BAD_SIGNATURE"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_BAD_SIGNATURE"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/activate(options:signature:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Activates a license. The options and signature parameters must exactly match the values provided in the SDK license. Calling this function invalidates any currently active license."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","text":"LicenseManagerState"}],"navigatorTitle":[{"text":"activateWithOptions:andSignature:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/activate(options:signature:)","title":"activate(options:signature:)","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager","title":"LicenseManager","abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}],"navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title","value":"LicenseManagerState","op":"replace"},{"value":[{"kind":"identifier","text":"LicenseManagerState"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments"},{"value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_BAD_SIGNATURE\/title","value":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE"},{"value":[{"text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_BAD_SIGNATURE\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/title","value":"activateWithOptions:andSignature:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"activateWithOptions:andSignature:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"LicenseManager"}]},{"value":[{"text":"LicenseManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle"}]}]}