{"metadata":{"role":"symbol","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_EXPIRED"}],"symbolKind":"case","roleHeading":"Case","title":"LicenseManagerState.ERROR_LICENSE_EXPIRED","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ERROR_LICENSE_EXPIRED","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@LicenseManagerState@LicenseManagerStateERROR_LICENSE_EXPIRED"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_LICENSE_EXPIRED"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_expired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_expired"]}],"sections":[],"abstract":[{"text":"The license has expired and is no longer valid. Contact the Nix SDK support team.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_EXPIRED"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ERROR_LICENSE_EXPIRED":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_EXPIRED","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_expired","abstract":[{"text":"The license has expired and is no longer valid. Contact the Nix SDK support team.","type":"text"}],"kind":"symbol","title":"LicenseManagerState.ERROR_LICENSE_EXPIRED","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_LICENSE_EXPIRED","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_EXPIRED"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseManager"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","role":"symbol","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"}],"title":"LicenseManager"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","role":"symbol","title":"LicenseManagerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LicenseManagerState","kind":"identifier"}],"navigatorTitle":[{"text":"LicenseManagerState","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"LicenseManagerStateERROR_LICENSE_EXPIRED"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"LicenseManagerStateERROR_LICENSE_EXPIRED","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"LicenseManagerStateERROR_LICENSE_EXPIRED","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_EXPIRED\/title","value":"LicenseManagerStateERROR_LICENSE_EXPIRED"},{"value":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_EXPIRED"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_EXPIRED\/fragments"},{"value":"LicenseManager","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","value":[{"kind":"identifier","text":"LicenseManager"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"text":"LicenseManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"LicenseManagerState","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseManagerState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle","value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}