{"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","externalID":"s:15NixUniversalSDK19LicenseManagerStateO4nameSSvp","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","title":"name"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/name"]}],"abstract":[{"type":"text","text":"String representation of this "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"reference","isActive":true}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/name","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManagerState"}],"navigatorTitle":[{"text":"LicenseManagerState","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","title":"LicenseManagerState","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"role":"symbol","title":"isFeatureEnabled(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFeatureEnabled:"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","abstract":[{"type":"text","text":"Helper to check if a particular "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"reference","isActive":true},{"type":"text","text":" is enabled by the current license."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFeatureEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature","text":"LicenseFeature"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/name":{"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/name","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/name","title":"name","abstract":[{"text":"String representation of this ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"reference"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"role":"symbol","title":"LicenseFeature","kind":"symbol","navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature","abstract":[{"type":"text","text":"Enum describing the optional features that can be enabled by the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"type":"text","text":". Feature availability can be queried using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LicenseFeature","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseManager"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}],"title":"LicenseManager","role":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title","value":"LicenseManagerState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments","value":[{"kind":"identifier","text":"LicenseManagerState"}]},{"value":[{"kind":"identifier","text":"LicenseManagerState"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title","value":"isFeatureEnabled:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isFeatureEnabled:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title","op":"replace","value":"LicenseFeature"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments","value":[{"text":"LicenseFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle","value":[{"text":"LicenseFeature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","op":"replace","value":"LicenseManager"},{"value":[{"kind":"identifier","text":"LicenseManager"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"text":"LicenseManager","kind":"identifier"}],"op":"replace"}]}]}