{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cmykToXyz","kind":"identifier"},{"kind":"text","text":"("},{"text":"cmykIn","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"], "},{"text":"refOut","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"], "},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"m"},{"kind":"text","text":": [["},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]], ","kind":"text"},{"text":"input","kind":"externalParam"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":"]], ","kind":"text"},{"kind":"externalParam","text":"clut"},{"text":": [[","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]]) -> ["},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"cmykIn","content":[{"inlineContent":[{"type":"text","text":"CMYK colour input, unity scale (element order C, M, Y, K)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Reference white value for XYZ output, unity scale (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"name":"refOut"},{"name":"bpc","content":[{"inlineContent":[{"type":"text","text":"Black point compensation enabled \/ disabled"}],"type":"paragraph"}]},{"name":"m","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3x3 Extracted from ICC profile: transformation matrix to perform on LAB value (NOT used in current function)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"256x4 matrix extracted from ICC profile: "},{"code":"InputCurves","type":"codeVoice"}]}],"name":"input"},{"name":"clut","content":[{"inlineContent":[{"text":"6561x3 matrix extracted from ICC profile: CMYK to LAB LUT (flattened 9x9x9x9 array with 3 channels, one each for L, A, B)","type":"text"}],"type":"paragraph"}]},{"name":"output","content":[{"inlineContent":[{"type":"text","text":"Extracted from ICC profile: "},{"type":"codeVoice","code":"OutputCurves"},{"type":"text","text":" (NOT used in current function, default profile has 1:1 output)"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"XYZ value output, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]}],"sections":[],"abstract":[{"text":"Calculates XYZ value from CMYK input using lookup tables provided as input arguments","type":"text"}],"metadata":{"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","symbolKind":"method","navigatorTitle":[{"text":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cmykToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cmykIn","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"text":"refOut","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"m","kind":"externalParam"},{"text":": [[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"]], ","kind":"text"},{"text":"input","kind":"externalParam"},{"text":": [[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"]], "},{"text":"clut","kind":"externalParam"},{"kind":"text","text":": [["},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"]], "},{"text":"output","kind":"externalParam"},{"text":": [[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"]]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]"}],"modules":[{"name":"NixUniversalSDK"}],"title":"cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:m:input:clut:output:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:m:input:clut:output:)"]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)":{"type":"topic","navigatorTitle":[{"text":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","kind":"identifier"}],"kind":"symbol","title":"cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:m:input:clut:output:)","abstract":[{"text":"Calculates XYZ value from CMYK input using lookup tables provided as input arguments","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cmykToXyz"},{"kind":"text","text":"("},{"text":"cmykIn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"refOut","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"m"},{"text":": [[","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]], ","kind":"text"},{"kind":"externalParam","text":"input"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"clut"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]], ","kind":"text"},{"kind":"externalParam","text":"output"},{"kind":"text","text":": [["},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"]]) -> [","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","abstract":[{"text":"Color math utility functions","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/colorutils","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"title":"ColorUtils"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"cmykToXyzWithCmykIn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"cmykIn","kind":"internalParam"},{"kind":"text","text":" "},{"text":"refOut:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"refOut","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bpc:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bpc"},{"kind":"text","text":" "},{"text":"m:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSArray<NSNumber *> *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"m","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"input:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSArray<NSNumber *> *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"input"},{"kind":"text","text":" "},{"text":"clut:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSArray<NSNumber *> *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"clut","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"output:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSArray<NSNumber *> *>"},{"kind":"text","text":" *) "},{"text":"output","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"CMYK colour input, unity scale (element order C, M, Y, K)"}],"type":"paragraph"}],"name":"cmykIn"},{"name":"refOut","content":[{"inlineContent":[{"type":"text","text":"Reference white value for XYZ output, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]},{"name":"bpc","content":[{"inlineContent":[{"text":"Black point compensation enabled \/ disabled","type":"text"}],"type":"paragraph"}]},{"name":"m","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3x3 Extracted from ICC profile: transformation matrix to perform on LAB value (NOT used in current function)"}]}]},{"name":"input","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"256x4 matrix extracted from ICC profile: "},{"type":"codeVoice","code":"InputCurves"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"6561x3 matrix extracted from ICC profile: CMYK to LAB LUT (flattened 9x9x9x9 array with 3 channels, one each for L, A, B)"}],"type":"paragraph"}],"name":"clut"},{"name":"output","content":[{"inlineContent":[{"text":"Extracted from ICC profile: ","type":"text"},{"code":"OutputCurves","type":"codeVoice"},{"text":" (NOT used in current function, default profile has 1:1 output)","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"XYZ value output, unity scale (element order X, Y, Z)"}]}],"kind":"content"}},{"value":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"cmykToXyzWithCmykIn:refOut:bpc:m:input:clut:output:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:m:input:clut:output:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"text":"ColorUtils","kind":"identifier"}]}]}]}