{"metadata":{"navigatorTitle":[{"text":"deltaE94WithLab1:lab2:kL:k1:k2:","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deltaE94"},{"kind":"text","text":"("},{"text":"lab1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"kL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"k1","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"k2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)deltaE94WithLab1:lab2:kL:k1:k2:","role":"symbol","title":"deltaE94(lab1:lab2:kL:k1:k2:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/deltae94(lab1:lab2:kl:k1:k2:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/deltae94(lab1:lab2:kl:k1:k2:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94(lab1:lab2:kL:k1:k2:)"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula. Requires weighting factors kL, k1, and k2 which are dependent on application. Use the "},{"type":"codeVoice","code":"deltaE94G"},{"type":"text","text":" method for graphic design applications and the "},{"code":"deltaE94T","type":"codeVoice"},{"text":" for textile applications. Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deltaE94"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lab1"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"kL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"k1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"k2","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"First CIELAB value (element order L, a, b)","type":"text"}]}],"name":"lab1"},{"name":"lab2","content":[{"inlineContent":[{"type":"text","text":"Second CIELAB value (element order L, a, b)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Weighting factor (application dependent)"}]}],"name":"kL"},{"name":"k1","content":[{"type":"paragraph","inlineContent":[{"text":"Weighting factor (application dependent)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Weighting factor (application dependent)"}]}],"name":"k2"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"dE (CIE1994) value"}]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE94(lab1:lab2:kL:k1:k2:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae94(lab1:lab2:kl:k1:k2:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deltaE94WithLab1:lab2:kL:k1:k2:"}],"title":"deltaE94(lab1:lab2:kL:k1:k2:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94(lab1:lab2:kL:k1:k2:)","abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula. Requires weighting factors kL, k1, and k2 which are dependent on application. Use the "},{"code":"deltaE94G","type":"codeVoice"},{"text":" method for graphic design applications and the ","type":"text"},{"code":"deltaE94T","type":"codeVoice"},{"text":" for textile applications. Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deltaE94"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lab1"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"text":"kL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"k1"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"k2","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"abstract":[{"type":"text","text":"Color math utility functions"}],"kind":"symbol","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ColorUtils","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","role":"symbol","title":"ColorUtils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"deltaE94WithLab1:lab2:kL:k1:k2:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"deltaE94WithLab1:lab2:kL:k1:k2:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"text":"deltaE94WithLab1:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"lab1","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lab2:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"lab2"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kL:"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"kL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"k1:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"k1","kind":"internalParam"},{"kind":"text","text":" "},{"text":"k2:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"k2"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"lab1","content":[{"inlineContent":[{"text":"First CIELAB value (element order L, a, b)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Second CIELAB value (element order L, a, b)","type":"text"}]}],"name":"lab2"},{"name":"kL","content":[{"inlineContent":[{"type":"text","text":"Weighting factor (application dependent)"}],"type":"paragraph"}]},{"name":"k1","content":[{"inlineContent":[{"type":"text","text":"Weighting factor (application dependent)"}],"type":"paragraph"}]},{"name":"k2","content":[{"inlineContent":[{"text":"Weighting factor (application dependent)","type":"text"}],"type":"paragraph"}]}]}},{"value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"dE (CIE1994) value","type":"text"}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94(lab1:lab2:kL:k1:k2:)\/title","value":"deltaE94WithLab1:lab2:kL:k1:k2:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94(lab1:lab2:kL:k1:k2:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deltaE94WithLab1:lab2:kL:k1:k2:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"kind":"identifier","text":"ColorUtils"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"kind":"identifier","text":"ColorUtils"}],"op":"replace"}]}]}