{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(im)init","symbolKind":"method","roleHeading":"Instance Method","title":"init","role":"symbol","modules":[{"name":"NixUniversalSDK"}]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/init"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/init":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/init","title":"init","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/init"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"role":"symbol","title":"ColorUtils","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorUtils"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","op":"replace","value":"ColorUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}]},{"value":[{"text":"ColorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}