{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/luvtolch(luvin:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/luvtolch(luvin:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"luvToLch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"luvIn"},{"kind":"text","text":": "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"CIELUV value (element order L, u, v)"}],"type":"paragraph"}],"name":"luvIn"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"LCHuv value (element order L, c, h). Hue angle h is in degrees","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToLch(luvIn:)"},"abstract":[{"text":"Takes CIELUV value and converts to polar coordinates (LCH)","type":"text"}],"metadata":{"role":"symbol","title":"luvToLch(luvIn:)","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)luvToLchWithLuvIn:","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"luvToLch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"luvIn"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"luvToLchWithLuvIn:","kind":"identifier"}]},"sections":[],"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/luvToLch(luvIn:)":{"title":"luvToLch(luvIn:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/luvtolch(luvin:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"luvToLch","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"luvIn"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToLch(luvIn:)","type":"topic","abstract":[{"type":"text","text":"Takes CIELUV value and converts to polar coordinates (LCH)"}],"navigatorTitle":[{"text":"luvToLchWithLuvIn:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"type":"topic","abstract":[{"type":"text","text":"Color math utility functions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorUtils"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","url":"\/documentation\/nixuniversalsdk\/colorutils","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"title":"ColorUtils"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"luvToLchWithLuvIn:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"luvToLchWithLuvIn:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"luvToLchWithLuvIn:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"luvIn","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIELUV value (element order L, u, v)"}]}],"name":"luvIn"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"LCHuv value (element order L, c, h). Hue angle h is in degrees"}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToLch(luvIn:)\/title","op":"replace","value":"luvToLchWithLuvIn:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToLch(luvIn:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"luvToLchWithLuvIn:"}]},{"value":"ColorUtils","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","op":"replace"},{"value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments"},{"value":[{"kind":"identifier","text":"ColorUtils"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}