{"abstract":[{"type":"text","text":"Takes CIELUV value and its reference white to calculate CIEXYZ value"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/luvtoxyz(luvin:xyzref:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/luvtoxyz(luvin:xyzref:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"luvToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"luvIn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"luvIn","content":[{"inlineContent":[{"text":"CIELUV value (element order L, u, v)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"CIEXYZ reference white (element order X, Y, Z)"}],"type":"paragraph"}],"name":"xyzRef"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"CIEXYZ value (element order X, Y, Z)","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToXyz(luvIn:xyzRef:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"luvToXyzWithLuvIn:xyzRef:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"luvToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"luvIn"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"xyzRef"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"title":"luvToXyz(luvIn:xyzRef:)","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)luvToXyzWithLuvIn:xyzRef:","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Type Method"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/luvToXyz(luvIn:xyzRef:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"luvToXyz"},{"kind":"text","text":"("},{"text":"luvIn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Takes CIELUV value and its reference white to calculate CIEXYZ value"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/luvToXyz(luvIn:xyzRef:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/luvtoxyz(luvin:xyzref:)","role":"symbol","title":"luvToXyz(luvIn:xyzRef:)","navigatorTitle":[{"kind":"identifier","text":"luvToXyzWithLuvIn:xyzRef:"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"abstract":[{"type":"text","text":"Color math utility functions"}],"kind":"symbol","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ColorUtils","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","role":"symbol","title":"ColorUtils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"luvToXyzWithLuvIn:xyzRef:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"luvToXyzWithLuvIn:xyzRef:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"luvToXyzWithLuvIn:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"luvIn","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"xyzRef:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"xyzRef"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"luvIn","content":[{"inlineContent":[{"type":"text","text":"CIELUV value (element order L, u, v)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"CIEXYZ reference white (element order X, Y, Z)"}],"type":"paragraph"}],"name":"xyzRef"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"CIEXYZ value (element order X, Y, Z)"}]}]},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToXyz(luvIn:xyzRef:)\/title","op":"replace","value":"luvToXyzWithLuvIn:xyzRef:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1luvToXyz(luvIn:xyzRef:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"luvToXyzWithLuvIn:xyzRef:","kind":"identifier"}]},{"op":"replace","value":"ColorUtils","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle"}]}]}