{"abstract":[{"type":"text","text":"Takes reflectance data on 10 nm intervals and calculates CMYK densities according to ISO 5-3:2009. Data must be provided on 10 nm intervals corresponding to the nearest 10 nanometer. Density values are calculated across the range 340 - 770 nm. If the provided data spans a shorter range (eg - 400 - 700 nm), the values at the boundaries are repeated."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(spectral10ToDensityWithLambda:reflectance:status:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"spectral10ToDensity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lambda"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"reflectance"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier","text":"DensityStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wavelength values of provided reflectance data."}]}],"name":"lambda"},{"name":"reflectance","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reflectance data. Must contain the same number of elements as "},{"code":"lambda","type":"codeVoice"}]}]},{"name":"status","content":[{"inlineContent":[{"text":"Selected density status","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"CMYK densities (element order C, M, Y, K)"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.0.2"}]}]}],"type":"unorderedList"}]}],"metadata":{"title":"spectral10ToDensity(lambda:reflectance:status:)","navigatorTitle":[{"text":"spectral10ToDensityWithLambda:reflectance:status:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"spectral10ToDensity","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lambda"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"reflectance"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":">, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier","text":"DensityStatus"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}],"roleHeading":"Type Method","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)spectral10ToDensityWithLambda:reflectance:status:"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/spectral10todensity(lambda:reflectance:status:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/spectral10todensity(lambda:reflectance:status:)"]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToDensity(lambda:reflectance:status:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/spectral10ToDensity(lambda:reflectance:status:)":{"abstract":[{"type":"text","text":"Takes reflectance data on 10 nm intervals and calculates CMYK densities according to ISO 5-3:2009. Data must be provided on 10 nm intervals corresponding to the nearest 10 nanometer. Density values are calculated across the range 340 - 770 nm. If the provided data spans a shorter range (eg - 400 - 700 nm), the values at the boundaries are repeated."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToDensity(lambda:reflectance:status:)","title":"spectral10ToDensity(lambda:reflectance:status:)","role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/spectral10todensity(lambda:reflectance:status:)","navigatorTitle":[{"text":"spectral10ToDensityWithLambda:reflectance:status:","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"spectral10ToDensity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lambda"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"reflectance"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","text":"DensityStatus"},{"text":") -> ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"role":"symbol","title":"ColorUtils","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorUtils"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"navigatorTitle":[{"kind":"identifier","text":"DensityStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DensityStatus"}],"url":"\/documentation\/nixuniversalsdk\/densitystatus","type":"topic","title":"DensityStatus","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the available options for density status"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"spectral10ToDensityWithLambda:reflectance:status:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"spectral10ToDensityWithLambda:reflectance:status:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"spectral10ToDensityWithLambda:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"lambda","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reflectance:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reflectance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"status:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"lambda","content":[{"inlineContent":[{"text":"Wavelength values of provided reflectance data.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Reflectance data. Must contain the same number of elements as "},{"code":"lambda","type":"codeVoice"}],"type":"paragraph"}],"name":"reflectance"},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected density status"}]}]}]}},{"value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"CMYK densities (element order C, M, Y, K)"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToDensity(lambda:reflectance:status:)\/title","value":"spectral10ToDensityWithLambda:reflectance:status:"},{"value":[{"kind":"text","text":"+ "},{"text":"spectral10ToDensityWithLambda:reflectance:status:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToDensity(lambda:reflectance:status:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","op":"replace","value":"ColorUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"kind":"identifier","text":"ColorUtils"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ColorUtils"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","value":"DensityStatus","op":"replace"},{"value":[{"kind":"identifier","text":"DensityStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","value":[{"text":"DensityStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}