{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"sections":[],"abstract":[{"text":"Calculates XYZ from sRGB value.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sRgbToXyz"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sRgb"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"refOut"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Non-linear sRGB value, 0-255 scale (element order R, G, B)","type":"text"}]}],"name":"sRgb"},{"content":[{"inlineContent":[{"type":"text","text":"Selected reference white of output XYZ color, unity scale (element order X, Y, Z)"}],"type":"paragraph"}],"name":"refOut"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"XYZ value, unity scale, with reference white "},{"code":"refOut","type":"codeVoice"},{"text":" (element order X, Y, Z)","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/srgbtoxyz(srgb:refout:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/srgbtoxyz(srgb:refout:)"]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/sRgbToXyz(sRgb:refOut:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)sRgbToXyzWithSRgb:refOut:","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"NixUniversalSDK"}],"title":"sRgbToXyz(sRgb:refOut:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sRgbToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sRgb"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refOut"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">) -> "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"sRgbToXyzWithSRgb:refOut:","kind":"identifier"}]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","abstract":[{"text":"Color math utility functions","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/colorutils","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"title":"ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/sRgbToXyz(sRgb:refOut:)":{"title":"sRgbToXyz(sRgb:refOut:)","kind":"symbol","navigatorTitle":[{"text":"sRgbToXyzWithSRgb:refOut:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sRgbToXyz"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sRgb"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":">, ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/sRgbToXyz(sRgb:refOut:)","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/srgbtoxyz(srgb:refout:)","abstract":[{"text":"Calculates XYZ from sRGB value.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sRgbToXyzWithSRgb:refOut:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sRgbToXyzWithSRgb:refOut:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sRgbToXyzWithSRgb:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"sRgb","kind":"internalParam"},{"kind":"text","text":" "},{"text":"refOut:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"refOut","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"sRgb","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Non-linear sRGB value, 0-255 scale (element order R, G, B)"}]}]},{"name":"refOut","content":[{"inlineContent":[{"type":"text","text":"Selected reference white of output XYZ color, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"XYZ value, unity scale, with reference white "},{"type":"codeVoice","code":"refOut"},{"type":"text","text":" (element order X, Y, Z)"}],"type":"paragraph"}],"kind":"content"}},{"value":"ColorUtils","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"kind":"identifier","text":"ColorUtils"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"text":"ColorUtils","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1sRgbToXyz(sRgb:refOut:)\/title","value":"sRgbToXyzWithSRgb:refOut:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1sRgbToXyz(sRgb:refOut:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sRgbToXyzWithSRgb:refOut:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}