{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"onScannerInit:state:","kind":"identifier"}],"title":"onScannerInit(_:state:)","required":true,"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onScannerInit"},{"kind":"text","text":"("},{"text":"IDeviceScanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceScanner"},{"text":", ","kind":"text"},{"text":"state","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState"},{"text":")","kind":"text"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)ScannerStateDelegate(im)onScannerInit:state:","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate\/onScannerInit(_:state:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Called when the "},{"code":"IDeviceScanner","type":"codeVoice"},{"type":"text","text":" has initialized. Check "},{"code":"state","type":"codeVoice"},{"text":" to determine success or failure code.","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/scannerstatedelegate\/onscannerinit(_:state:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/scannerstatedelegate\/onscannerinit(_:state:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onScannerInit","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceScanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","text":"IDeviceScanner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","kind":"typeIdentifier","text":"DeviceScannerState"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"IDeviceScanner"},{"text":" instance that invoked this call","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Current state of the "},{"code":"IDeviceScanner","type":"codeVoice"}],"type":"paragraph"}],"name":"state"}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescanner","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScannerStateDelegate/onScannerInit(_:state:)":{"required":true,"url":"\/documentation\/nixuniversalsdk\/scannerstatedelegate\/onscannerinit(_:state:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate\/onScannerInit(_:state:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onScannerInit"},{"kind":"text","text":"("},{"text":"IDeviceScanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceScanner"},{"text":", ","kind":"text"},{"text":"state","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceScannerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onScannerInit:state:"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Called when the ","type":"text"},{"type":"codeVoice","code":"IDeviceScanner"},{"type":"text","text":" has initialized. Check "},{"type":"codeVoice","code":"state"},{"text":" to determine success or failure code.","type":"text"}],"title":"onScannerInit(_:state:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScannerStateDelegate":{"navigatorTitle":[{"text":"ScannerStateDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate","role":"symbol","url":"\/documentation\/nixuniversalsdk\/scannerstatedelegate","abstract":[{"type":"text","text":"Protocol definition for a callback to be invoked when an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true,"type":"reference"},{"text":" starts or stops a search.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScannerStateDelegate"}],"type":"topic","title":"ScannerStateDelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"title":"DeviceScannerState","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScannerState"}],"url":"\/documentation\/nixuniversalsdk\/devicescannerstate","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","abstract":[{"text":"Protocol implemented by the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"}],"title":"IDeviceScanner","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceScanner","kind":"identifier"}],"navigatorTitle":[{"text":"IDeviceScanner","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicescanner","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onScannerInit:state:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onScannerInit:state:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onScannerInit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceScanner","text":"id<IDeviceScanner>"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","text":"DeviceScannerState"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"state"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"sender","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"IDeviceScanner"},{"text":" instance that invoked this call","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current state of the "},{"code":"IDeviceScanner","type":"codeVoice"}]}],"name":"state"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"value":"onScannerInit:state:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate~1onScannerInit(_:state:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate~1onScannerInit(_:state:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onScannerInit:state:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/title","value":"ScannerStateDelegate","op":"replace"},{"value":[{"text":"ScannerStateDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/navigatorTitle","value":[{"text":"ScannerStateDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title","value":"DeviceScannerState"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","value":[{"text":"DeviceScannerState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceScannerState"}]},{"value":"IDeviceScanner","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","value":[{"text":"IDeviceScanner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}