{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/adaptXyz(xyzIn:refIn:refOut:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/adaptxyz(xyzin:refin:refout:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/adaptxyz(xyzin:refin:refout:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adaptXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"refIn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">) -> "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Source color, referenced to ","type":"text"},{"type":"codeVoice","code":"refIn"},{"text":" (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"name":"xyzIn"},{"content":[{"inlineContent":[{"text":"Source reference white (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"name":"refIn"},{"name":"refOut","content":[{"type":"paragraph","inlineContent":[{"text":"Destination reference white (element order X, Y, Z)","type":"text"}]}]}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Adapted color, referenced to "},{"type":"codeVoice","code":"refOut"},{"type":"text","text":" (element order X, Y, Z)"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"roleHeading":"Type Method","title":"adaptXyz(xyzIn:refIn:refOut:)","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)adaptXyzWithXyzIn:refIn:refOut:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptXyz"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"xyzIn"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refIn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adaptXyzWithXyzIn:refIn:refOut:"}],"modules":[{"name":"NixUniversalSDK"}]},"abstract":[{"text":"Adapts colour in XYZ from one reference white to another using Bradford adaptation method. NOTE: ","type":"text"},{"type":"codeVoice","code":"refIn"},{"type":"text","text":", "},{"type":"codeVoice","code":"refOut"},{"text":", ","type":"text"},{"code":"xyzIn","type":"codeVoice"},{"type":"text","text":" must all be on the same scale."}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"type":"topic","abstract":[{"type":"text","text":"Color math utility functions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorUtils"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","url":"\/documentation\/nixuniversalsdk\/colorutils","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"title":"ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/adaptXyz(xyzIn:refIn:refOut:)":{"kind":"symbol","title":"adaptXyz(xyzIn:refIn:refOut:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/adaptxyz(xyzin:refin:refout:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptXyz"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"text":"refIn","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"refOut","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/adaptXyz(xyzIn:refIn:refOut:)","type":"topic","abstract":[{"type":"text","text":"Adapts colour in XYZ from one reference white to another using Bradford adaptation method. NOTE: "},{"code":"refIn","type":"codeVoice"},{"type":"text","text":", "},{"code":"refOut","type":"codeVoice"},{"text":", ","type":"text"},{"code":"xyzIn","type":"codeVoice"},{"type":"text","text":" must all be on the same scale."}],"navigatorTitle":[{"text":"adaptXyzWithXyzIn:refIn:refOut:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adaptXyzWithXyzIn:refIn:refOut:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"adaptXyzWithXyzIn:refIn:refOut:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"adaptXyzWithXyzIn:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"xyzIn","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refIn:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"refIn","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"refOut:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"refOut","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Source color, referenced to ","type":"text"},{"type":"codeVoice","code":"refIn"},{"text":" (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"name":"xyzIn"},{"name":"refIn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Source reference white (element order X, Y, Z)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Destination reference white (element order X, Y, Z)"}]}],"name":"refOut"}]},"op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Adapted color, referenced to "},{"code":"refOut","type":"codeVoice"},{"text":" (element order X, Y, Z)","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorUtils"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"adaptXyzWithXyzIn:refIn:refOut:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1adaptXyz(xyzIn:refIn:refOut:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1adaptXyz(xyzIn:refIn:refOut:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adaptXyzWithXyzIn:refIn:refOut:"}],"op":"replace"}]}]}