{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:)"]},{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"cmykToXyz(cmykIn:refOut:bpc:)","roleHeading":"Type Method","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)cmykToXyzWithCmykIn:refOut:bpc:","navigatorTitle":[{"text":"cmykToXyzWithCmykIn:refOut:bpc:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cmykToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cmykIn","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"refOut"},{"kind":"text","text":": ["},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"bpc"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"]","kind":"text"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cmykToXyz"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cmykIn"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"text":"refOut","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"parameters":[{"name":"cmykIn","content":[{"inlineContent":[{"text":"CMYK colour input, unity scale (element order C, M, Y, K)","type":"text"}],"type":"paragraph"}]},{"name":"refOut","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference white value for XYZ output, unity scale (element order X, Y, Z)"}]}]},{"name":"bpc","content":[{"type":"paragraph","inlineContent":[{"text":"Black point compensation enabled \/ disabled","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"XYZ value output, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]}],"abstract":[{"text":"Calculates XYZ value from CMYK input using built-in lookup tables","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"title":"ColorUtils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/cmykToXyz(cmykIn:refOut:bpc:)":{"navigatorTitle":[{"kind":"identifier","text":"cmykToXyzWithCmykIn:refOut:bpc:"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/cmyktoxyz(cmykin:refout:bpc:)","type":"topic","title":"cmykToXyz(cmykIn:refOut:bpc:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/cmykToXyz(cmykIn:refOut:bpc:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmykToXyz"},{"text":"(","kind":"text"},{"text":"cmykIn","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"], "},{"text":"refOut","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Calculates XYZ value from CMYK input using built-in lookup tables"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"cmykToXyzWithCmykIn:refOut:bpc:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"cmykToXyzWithCmykIn:refOut:bpc:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"cmykToXyzWithCmykIn:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"cmykIn","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refOut:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"refOut","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bpc:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bpc"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"cmykIn","content":[{"inlineContent":[{"type":"text","text":"CMYK colour input, unity scale (element order C, M, Y, K)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Reference white value for XYZ output, unity scale (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"name":"refOut"},{"name":"bpc","content":[{"type":"paragraph","inlineContent":[{"text":"Black point compensation enabled \/ disabled","type":"text"}]}]}]},"op":"replace"},{"value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"XYZ value output, unity scale (element order X, Y, Z)"}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"ColorUtils","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"kind":"identifier","text":"ColorUtils"}],"op":"replace"},{"value":"cmykToXyzWithCmykIn:refOut:bpc:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1cmykToXyz(cmykIn:refOut:bpc:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"cmykToXyzWithCmykIn:refOut:bpc:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}