{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/labtolch(labin:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/labtolch(labin:)"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToLch(labIn:)","interfaceLanguage":"swift"},"abstract":[{"text":"Takes CIELAB value and converts to polar coordinates (LCH)","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labToLch"},{"text":"(","kind":"text"},{"text":"labIn","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"CIELAB value (element order L, a, b)","type":"text"}]}],"name":"labIn"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"LCHab value (element order L, c, h). Hue angle h is in degrees"}]}]}],"metadata":{"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)labToLchWithLabIn:","navigatorTitle":[{"text":"labToLchWithLabIn:","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labToLch"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"labIn"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"labToLch(labIn:)","symbolKind":"method","role":"symbol"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"title":"ColorUtils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/labToLch(labIn:)":{"kind":"symbol","abstract":[{"type":"text","text":"Takes CIELAB value and converts to polar coordinates (LCH)"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/labtolch(labin:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labToLch"},{"text":"(","kind":"text"},{"text":"labIn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"labToLchWithLabIn:","kind":"identifier"}],"role":"symbol","type":"topic","title":"labToLch(labIn:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/labToLch(labIn:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"labToLchWithLabIn:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"labToLchWithLabIn:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"labToLchWithLabIn:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"labIn","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]}},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIELAB value (element order L, a, b)"}]}],"name":"labIn"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"LCHab value (element order L, c, h). Hue angle h is in degrees"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}]},{"value":"labToLchWithLabIn:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1labToLch(labIn:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"labToLchWithLabIn:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1labToLch(labIn:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}