{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/rgbtoxyz(rgbin:rchrom:gchrom:bchrom:wchrom:refout:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/rgbtoxyz(rgbin:rchrom:gchrom:bchrom:wchrom:refout:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rgbToXyz"},{"text":"(","kind":"text"},{"text":"rgbIn","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"rChrom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"text":"gChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"bChrom"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"wChrom"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refOut"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"rgbIn","content":[{"inlineContent":[{"text":"Input linear RGB value, unity scale (element order R, G, B)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"RGB space red primary chromaticity coordinates (element order x, y)"}],"type":"paragraph"}],"name":"rChrom"},{"content":[{"type":"paragraph","inlineContent":[{"text":"RGB space green primary chromaticity coordinates (element order x, y)","type":"text"}]}],"name":"gChrom"},{"name":"bChrom","content":[{"inlineContent":[{"type":"text","text":"RGB space blue primary chromaticity coordinates (element order x, y)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB space reference white\/grey chromaticity coordinates (element order x, y)"}]}],"name":"wChrom"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Selected reference white of output XYZ color, unity scale (element order X, Y, Z)","type":"text"}]}],"name":"refOut"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"XYZ value, unity scale, with reference white ","type":"text"},{"type":"codeVoice","code":"refOut"},{"type":"text","text":" (element order X, Y, Z)"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)"},"kind":"symbol","metadata":{"role":"symbol","title":"rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","navigatorTitle":[{"kind":"identifier","text":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgbToXyz"},{"kind":"text","text":"("},{"text":"rgbIn","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"text":"rChrom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"gChrom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">, ","kind":"text"},{"text":"bChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"text":"wChrom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"symbolKind":"method","modules":[{"name":"NixUniversalSDK"}]},"abstract":[{"text":"Calculates XYZ from linear RGB given chromaticity coordinates of RGB working space primaries and reference whites of RGB and XYZ value.","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"title":"ColorUtils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)":{"abstract":[{"text":"Calculates XYZ from linear RGB given chromaticity coordinates of RGB working space primaries and reference whites of RGB and XYZ value.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/rgbtoxyz(rgbin:rchrom:gchrom:bchrom:wchrom:refout:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rgbToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rgbIn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"rChrom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"gChrom"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"bChrom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"text":"wChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"refOut","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)","navigatorTitle":[{"kind":"identifier","text":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"rgbToXyzWithRgbIn:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rgbIn"},{"kind":"text","text":" "},{"text":"rChrom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rChrom"},{"kind":"text","text":" "},{"text":"gChrom:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"gChrom"},{"text":" ","kind":"text"},{"text":"bChrom:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"bChrom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wChrom:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"wChrom","kind":"internalParam"},{"kind":"text","text":" "},{"text":"refOut:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"refOut","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"rgbIn","content":[{"type":"paragraph","inlineContent":[{"text":"Input linear RGB value, unity scale (element order R, G, B)","type":"text"}]}]},{"name":"rChrom","content":[{"inlineContent":[{"type":"text","text":"RGB space red primary chromaticity coordinates (element order x, y)"}],"type":"paragraph"}]},{"name":"gChrom","content":[{"inlineContent":[{"text":"RGB space green primary chromaticity coordinates (element order x, y)","type":"text"}],"type":"paragraph"}]},{"name":"bChrom","content":[{"inlineContent":[{"type":"text","text":"RGB space blue primary chromaticity coordinates (element order x, y)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB space reference white\/grey chromaticity coordinates (element order x, y)"}]}],"name":"wChrom"},{"name":"refOut","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected reference white of output XYZ color, unity scale (element order X, Y, Z)"}]}]}]}},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"XYZ value, unity scale, with reference white "},{"type":"codeVoice","code":"refOut"},{"text":" (element order X, Y, Z)","type":"text"}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorUtils"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"kind":"identifier","text":"ColorUtils"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)\/title","value":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rgbToXyzWithRgbIn:rChrom:gChrom:bChrom:wChrom:refOut:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1rgbToXyz(rgbIn:rChrom:gChrom:bChrom:wChrom:refOut:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}