{"metadata":{"symbolKind":"method","title":"spectral10ToXyz(lambda:reflectance:illuminant:observer:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spectral10ToXyz","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lambda"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"reflectance"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier","text":"Illuminant"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)spectral10ToXyzWithLambda:reflectance:illuminant:observer:","roleHeading":"Type Method","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:"}]},"abstract":[{"type":"text","text":"Takes reflectance data on 10 nm intervals and calculates a CIEXYZ value according to ASTM E308. Data must be provided on 10 nm intervals corresponding to the nearest 10 nanometer. CIEXYZ values are calculated across the range 360 - 780 nm. If the provided data spans a shorter range (eg - 400 - 700 nm), the values at the boundaries are repeated."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(spectral10ToXyzWithLambda:reflectance:illuminant:observer:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"spectral10ToXyz","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lambda"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"reflectance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"illuminant"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Illuminant","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"lambda","content":[{"inlineContent":[{"type":"text","text":"Wavelength values of provided reflectance data."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reflectance data. Must contain the same number of elements as "},{"type":"codeVoice","code":"lambda"}]}],"name":"reflectance"},{"name":"illuminant","content":[{"inlineContent":[{"text":"Selected illuminant","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Selected observer","type":"text"}]}],"name":"observer"}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"CIEXYZ value reported on 0 - 1.0 scale (element order X, Y, Z)","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToXyz(lambda:reflectance:illuminant:observer:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/spectral10toxyz(lambda:reflectance:illuminant:observer:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/spectral10toxyz(lambda:reflectance:illuminant:observer:)"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Observer"}],"title":"Observer","role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Observer","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/spectral10ToXyz(lambda:reflectance:illuminant:observer:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/spectral10ToXyz(lambda:reflectance:illuminant:observer:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"spectral10ToXyz","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lambda"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"reflectance"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:"}],"abstract":[{"text":"Takes reflectance data on 10 nm intervals and calculates a CIEXYZ value according to ASTM E308. Data must be provided on 10 nm intervals corresponding to the nearest 10 nanometer. CIEXYZ values are calculated across the range 360 - 780 nm. If the provided data spans a shorter range (eg - 400 - 700 nm), the values at the boundaries are repeated.","type":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/spectral10toxyz(lambda:reflectance:illuminant:observer:)","title":"spectral10ToXyz(lambda:reflectance:illuminant:observer:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"title":"Illuminant","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Illuminant"}],"abstract":[{"text":"Enum to describe the available options for reference illuminant","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","url":"\/documentation\/nixuniversalsdk\/illuminant","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"title":"ColorUtils","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"spectral10ToXyzWithLambda:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"lambda","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reflectance:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reflectance"},{"kind":"text","text":" "},{"text":"illuminant:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"kind":"text","text":") "},{"text":"illuminant","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"observer:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":") ","kind":"text"},{"text":"observer","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wavelength values of provided reflectance data."}]}],"name":"lambda"},{"name":"reflectance","content":[{"inlineContent":[{"type":"text","text":"Reflectance data. Must contain the same number of elements as "},{"type":"codeVoice","code":"lambda"}],"type":"paragraph"}]},{"name":"illuminant","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected illuminant"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected observer"}]}],"name":"observer"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"CIEXYZ value reported on 0 - 1.0 scale (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"kind":"identifier","text":"Observer"}],"op":"replace"},{"value":[{"text":"Observer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToXyz(lambda:reflectance:illuminant:observer:)\/title","value":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1spectral10ToXyz(lambda:reflectance:illuminant:observer:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"spectral10ToXyzWithLambda:reflectance:illuminant:observer:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","op":"replace","value":"Illuminant"},{"value":[{"text":"Illuminant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"text":"Illuminant","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","value":"ColorUtils"},{"op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments"},{"value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}