{"metadata":{"navigatorTitle":[{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToCmyk","kind":"identifier"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"], "},{"text":"xyzRef","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"], "},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"m","kind":"externalParam"},{"kind":"text","text":": [["},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]], ","kind":"text"},{"kind":"externalParam","text":"inputCurves"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]], ","kind":"text"},{"text":"clut","kind":"externalParam"},{"kind":"text","text":": [["},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]], ","kind":"text"},{"text":"outputCurves","kind":"externalParam"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]]) -> [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}],"roleHeading":"Type Method","symbolKind":"method","title":"xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","modules":[{"name":"NixUniversalSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","interfaceLanguage":"swift"},"abstract":[{"text":"Calculates CMYK value from XYZ using lookup tables provided as ","type":"text"},{"code":"inputCurves","type":"codeVoice"},{"text":" arguments","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToCmyk","kind":"identifier"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"xyzRef"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"m","kind":"externalParam"},{"text":": [[","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"inputCurves"},{"text":": [[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"clut"},{"text":": [[","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"]], ","kind":"text"},{"text":"outputCurves","kind":"externalParam"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]]) -> [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}]}]},{"parameters":[{"name":"xyzIn","content":[{"inlineContent":[{"type":"text","text":"XYZ colour, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Reference white value for "},{"code":"xyzIn","type":"codeVoice"},{"type":"text","text":", unity scale (element order X, Y, Z)"}],"type":"paragraph"}],"name":"xyzRef"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Black point compensation enabled \/ disabled"}]}],"name":"bpc"},{"name":"m","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3x3 matrix extracted from ICC profile: transformation matrix to perform on LAB value (code only tested with identity matrix)"}]}]},{"content":[{"inlineContent":[{"text":"256x3 matrix extracted from ICC profile: ","type":"text"},{"type":"codeVoice","code":"InputCurves"}],"type":"paragraph"}],"name":"inputCurves"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Extracted from ICC profile: Lab to CMYK LUT (flattened 33x33x33 array with 4 channels, one each for C,M,Y,K)","type":"text"}]}],"name":"clut"},{"name":"outputCurves","content":[{"type":"paragraph","inlineContent":[{"text":"256x4 matrix extracted from ICC profile: ","type":"text"},{"type":"codeVoice","code":"OutputCurves"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"CMYK value on unity scale (element order C, M, Y, K)","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:m:inputcurves:clut:outputcurves:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:m:inputcurves:clut:outputcurves:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"text":"Color math utility functions","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"role":"symbol","title":"ColorUtils","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorUtils"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xyzToCmyk"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":"], ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"bpc"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"m"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"inputCurves"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"]], ","kind":"text"},{"text":"clut","kind":"externalParam"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":"]], ","kind":"text"},{"text":"outputCurves","kind":"externalParam"},{"text":": [[","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]]) -> [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","type":"topic","url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:m:inputcurves:clut:outputcurves:)","title":"xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)","navigatorTitle":[{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","kind":"identifier"}],"abstract":[{"type":"text","text":"Calculates CMYK value from XYZ using lookup tables provided as "},{"type":"codeVoice","code":"inputCurves"},{"text":" arguments","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"xyzToCmykWithXyzIn:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"xyzIn"},{"kind":"text","text":" "},{"kind":"identifier","text":"xyzRef:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"text":"xyzRef","kind":"internalParam"},{"kind":"text","text":" "},{"text":"bpc:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bpc","kind":"internalParam"},{"kind":"text","text":" "},{"text":"m:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSArray<NSNumber *> *>"},{"kind":"text","text":" *) "},{"text":"m","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inputCurves:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSArray<NSNumber *> *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"inputCurves"},{"kind":"text","text":" "},{"kind":"identifier","text":"clut:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSArray<NSNumber *> *>"},{"kind":"text","text":" *) "},{"text":"clut","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outputCurves:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSArray<NSNumber *> *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputCurves"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"xyzIn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"XYZ colour, unity scale (element order X, Y, Z)"}]}]},{"name":"xyzRef","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference white value for "},{"code":"xyzIn","type":"codeVoice"},{"text":", unity scale (element order X, Y, Z)","type":"text"}]}]},{"name":"bpc","content":[{"type":"paragraph","inlineContent":[{"text":"Black point compensation enabled \/ disabled","type":"text"}]}]},{"name":"m","content":[{"type":"paragraph","inlineContent":[{"text":"3x3 matrix extracted from ICC profile: transformation matrix to perform on LAB value (code only tested with identity matrix)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"256x3 matrix extracted from ICC profile: "},{"type":"codeVoice","code":"InputCurves"}],"type":"paragraph"}],"name":"inputCurves"},{"name":"clut","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Extracted from ICC profile: Lab to CMYK LUT (flattened 33x33x33 array with 4 channels, one each for C,M,Y,K)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"256x4 matrix extracted from ICC profile: ","type":"text"},{"code":"OutputCurves","type":"codeVoice"}]}],"name":"outputCurves"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"CMYK value on unity scale (element order C, M, Y, K)"}]}]},"op":"replace"},{"value":"ColorUtils","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ColorUtils"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)\/title","op":"replace","value":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"xyzToCmykWithXyzIn:xyzRef:bpc:m:inputCurves:clut:outputCurves:"}]}]}]}