{"metadata":{"roleHeading":"Type Method","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)xyzToLabWithXyz:xyzRef:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xyzToLab"},{"text":"(","kind":"text"},{"text":"xyz","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"xyzRef"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"xyzToLab(xyz:xyzRef:)","navigatorTitle":[{"text":"xyzToLabWithXyz:xyzRef:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToLab","kind":"identifier"},{"kind":"text","text":"("},{"text":"xyz","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">, ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"CIEXYZ value (element order X, Y, Z)","type":"text"}]}],"name":"xyz"},{"name":"xyzRef","content":[{"inlineContent":[{"type":"text","text":"Reference white (element order X, Y, Z)"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"CIELAB value (element order L, a, b)"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztolab(xyz:xyzref:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztolab(xyz:xyzref:)"]}],"kind":"symbol","sections":[],"abstract":[{"text":"Takes CIEXYZ value and its reference white to calculate CIELAB value. ","type":"text"},{"type":"codeVoice","code":"xyz"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"xyzRef"},{"type":"text","text":" can be either unity (0 - 1) or scaled (0 - 100) input, but both vectors must be the same scale; if "},{"type":"codeVoice","code":"xyz"},{"text":" is unity scale, ","type":"text"},{"type":"codeVoice","code":"xyzRef"},{"type":"text","text":" must also be unity scale"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLab(xyz:xyzRef:)","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","url":"\/documentation\/nixuniversalsdk\/colorutils","type":"topic","kind":"symbol","title":"ColorUtils","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorUtils","kind":"identifier"}],"abstract":[{"text":"Color math utility functions","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToLab(xyz:xyzRef:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToLab(xyz:xyzRef:)","role":"symbol","abstract":[{"text":"Takes CIEXYZ value and its reference white to calculate CIELAB value. ","type":"text"},{"type":"codeVoice","code":"xyz"},{"type":"text","text":" and "},{"type":"codeVoice","code":"xyzRef"},{"text":" can be either unity (0 - 1) or scaled (0 - 100) input, but both vectors must be the same scale; if ","type":"text"},{"type":"codeVoice","code":"xyz"},{"type":"text","text":" is unity scale, "},{"code":"xyzRef","type":"codeVoice"},{"text":" must also be unity scale","type":"text"}],"type":"topic","title":"xyzToLab(xyz:xyzRef:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"xyzToLab","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyz","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"xyzRef"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztolab(xyz:xyzref:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"xyzToLabWithXyz:xyzRef:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"xyzToLabWithXyz:xyzRef:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"xyzToLabWithXyz:xyzRef:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"xyzToLabWithXyz:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"xyz"},{"kind":"text","text":" "},{"text":"xyzRef:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"xyzRef"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"xyz","content":[{"inlineContent":[{"type":"text","text":"CIEXYZ value (element order X, Y, Z)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference white (element order X, Y, Z)"}]}],"name":"xyzRef"}],"kind":"parameters"}},{"value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"CIELAB value (element order L, a, b)","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"ColorUtils","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title"},{"value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"text":"ColorUtils","kind":"identifier"}]},{"value":"xyzToLabWithXyz:xyzRef:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToLab(xyz:xyzRef:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToLab(xyz:xyzRef:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"xyzToLabWithXyz:xyzRef:","kind":"identifier"}]}]}]}