{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIE76","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cie76"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cie76"]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE76","interfaceLanguage":"swift"},"abstract":[{"text":"Color difference using CIE1976 equation.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"]]},"metadata":{"symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCIE76"}],"externalID":"c:@M@NixUniversalSDK@E@ColorDifferenceType@ColorDifferenceTypeCIE76","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIE76"}],"title":"ColorDifferenceType.CIE76"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE76":{"title":"ColorDifferenceType.CIE76","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIE76"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie76","abstract":[{"type":"text","text":"Color difference using CIE1976 equation."}],"navigatorTitle":[{"text":"ColorDifferenceTypeCIE76","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE76","role":"symbol","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"role":"symbol","abstract":[{"type":"text","text":"Enum describing the available color difference (delta E) equations."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorDifferenceType","kind":"identifier"}],"navigatorTitle":[{"text":"ColorDifferenceType","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype","title":"ColorDifferenceType","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ColorDifferenceTypeCIE76","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE76"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"ColorDifferenceTypeCIE76"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ColorDifferenceTypeCIE76","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE76\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE76"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE76\/fragments"},{"op":"replace","value":"ColorDifferenceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title"},{"value":[{"text":"ColorDifferenceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","value":[{"kind":"identifier","text":"ColorDifferenceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}