{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"init","externalID":"s:15NixUniversalSDK19ColorDifferenceTypeO8rawValueACSgSi_tcfc","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/init(rawvalue:)"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","abstract":[],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"role":"symbol","abstract":[{"type":"text","text":"Enum describing the available color difference (delta E) equations."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorDifferenceType","kind":"identifier"}],"navigatorTitle":[{"text":"ColorDifferenceType","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype","title":"ColorDifferenceType","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title","value":"ColorDifferenceType","op":"replace"},{"value":[{"kind":"identifier","text":"ColorDifferenceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}