{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/active"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate\/active"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@NixUniversalSDK@E@LicenseManagerState@LicenseManagerStateACTIVE","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"role":"symbol","title":"LicenseManagerState.ACTIVE","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ACTIVE"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ACTIVE","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/faq"],"kind":"mentions"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE"},"abstract":[{"type":"text","text":"The license has activated successfully and Nix Universal SDK functions are available."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","url":"\/documentation\/nixuniversalsdk\/activating-license","title":"Activating the SDK License","type":"topic","role":"article","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"kind":"article","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","title":"Discovering and Connecting to Nix Devices","role":"article","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","abstract":[{"type":"text","text":"Use the device scanner to discover Nix devices and open a connection"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ACTIVE"}],"title":"LicenseManagerState.ACTIVE","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"type":"topic","abstract":[{"text":"The license has activated successfully and Nix Universal SDK functions are available.","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManagerState","kind":"identifier"}],"title":"LicenseManagerState","role":"symbol","navigatorTitle":[{"text":"LicenseManagerState","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","url":"\/documentation\/nixuniversalsdk\/licensemanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}],"title":"LicenseManager","role":"symbol","navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/faq":{"abstract":[{"type":"text","text":"Troubleshooting common issues"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/faq","url":"\/documentation\/nixuniversalsdk\/faq","title":"Frequently Asked Questions","type":"topic","role":"article","kind":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"LicenseManagerStateACTIVE","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title","value":"LicenseManagerStateACTIVE","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments","value":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title","value":"LicenseManagerState","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments","value":[{"kind":"identifier","text":"LicenseManagerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle","value":[{"kind":"identifier","text":"LicenseManagerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"text":"LicenseManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}