{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceTemperature","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Baseline temperature for this device. Corresponds to in-field normalization temperature for "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","isActive":true},{"text":", or factory temperature for others. ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" contains a "},{"code":"Float","type":"codeVoice"},{"text":" value. Value is ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the device does not support this feature. The value is valid only after a connection has successfully been opened."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"referenceTemperature","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/referencetemperature"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/referencetemperature"]}],"sections":[],"metadata":{"modules":[{"name":"NixUniversalSDK"}],"required":true,"externalID":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat(py)referenceTemperature","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceTemperature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"referenceTemperature","navigatorTitle":[{"text":"referenceTemperature","kind":"identifier"}],"roleHeading":"Instance Property"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":".","type":"text"}],"title":"IDeviceCompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescanner","role":"symbol","abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/SPECTRO2":{"kind":"symbol","abstract":[{"type":"text","text":"Type for Nix Spectro 2 spectrophotometer"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/spectro2","type":"topic","title":"DeviceType.SPECTRO2","navigatorTitle":[{"text":"DeviceTypeSPECTRO2","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SPECTRO2"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI3":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"MINI3","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","abstract":[{"type":"text","text":"Type for Nix Mini 3 colorimeter"}],"title":"DeviceType.MINI3","role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/mini3","navigatorTitle":[{"text":"DeviceTypeMINI3","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/referenceTemperature":{"role":"symbol","required":true,"abstract":[{"type":"text","text":"Baseline temperature for this device. Corresponds to in-field normalization temperature for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","type":"reference","isActive":true},{"type":"text","text":", or factory temperature for others. "},{"code":"NSNumber","type":"codeVoice"},{"text":" contains a ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value. Value is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the device does not support this feature. The value is valid only after a connection has successfully been opened.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/referencetemperature","type":"topic","navigatorTitle":[{"text":"referenceTemperature","kind":"identifier"}],"title":"referenceTemperature","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"referenceTemperature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceTemperature"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"referenceTemperature","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"referenceTemperature","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"text":"referenceTemperature","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace"},{"value":"IDeviceCompat","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"IDeviceCompat"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/title","op":"replace","value":"DeviceTypeSPECTRO2"},{"value":[{"kind":"identifier","text":"DeviceTypeSPECTRO2"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/fragments"},{"value":"DeviceTypeMINI3","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/fragments","value":[{"kind":"identifier","text":"DeviceTypeMINI3"}],"op":"replace"},{"op":"replace","value":"referenceTemperature","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1referenceTemperature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"referenceTemperature"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1referenceTemperature\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}