{"abstract":[{"text":"Add the library bundle to your project and declare peripheral uses","type":"text"}],"kind":"article","metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"NixUniversalSDK"}],"title":"Adding to Your Xcode Project"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The Nix Universal SDK is provided as an XCFramework bundle containing support for iOS, iOS Simulator, and macOS devices. The provided XCFramework file can be added and embedded in your project directly, or you may add it as a Swift Package dependency.","type":"text"}]},{"style":"tip","name":"Tip","content":[{"type":"paragraph","inlineContent":[{"text":"The latest stable version of the Nix Universal SDK is hosted on ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist"},{"text":" and can be added to your project as a Swift Package dependency. It is recommended to install from this source.","type":"text"}]}],"type":"aside"},{"type":"heading","level":3,"anchor":"Review-the-End-User-License-Agreement","text":"Review the End User License Agreement"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before proceeding, review and accept the "},{"identifier":"https:\/\/www.nixsensor.com\/sdk-eula-ios","type":"reference","isActive":true},{"text":".","type":"text"}]},{"text":"Adding the package reference","level":3,"anchor":"Adding-the-package-reference","type":"heading"},{"inlineContent":[{"text":"In Xcode:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Open the Swift Package Manager via “File > Add Package Dependencies…”"}]}]}]},{"inlineContent":[{"type":"image","identifier":"filemenu.png"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Enter "},{"type":"codeVoice","code":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist.git"},{"type":"text","text":" in the search box at the top right"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The description for ‘Nix Universal SDK’ should appear in the package manager. Select ‘nix-universal-sdk-dist’ as the package and click ‘Add Package’","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"image","identifier":"swiftpm.png"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Make sure that ‘NixUniversalSDK’ is included in the ‘Frameworks, Library, and Embedded Content’ for your build target.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If not, click on the ‘+’ icon and add ‘NixUniversalSDK’ from the ‘NixUniversalSDK Package’"}]}]}],"type":"unorderedList"}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"frameworks.png"}]},{"text":"Add required usage descriptions","level":3,"type":"heading","anchor":"Add-required-usage-descriptions"},{"type":"paragraph","inlineContent":[{"text":"Add entries for ","type":"text"},{"type":"codeVoice","code":"NSBluetoothAlwaysUsageDescription"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"NSBluetoothPeripheralUsageDescription"},{"type":"text","text":" to your "},{"type":"codeVoice","code":"info.plist"},{"type":"text","text":" file. The value for these keys is a string shown presented to the user when the application requests permission to use the Bluetooth peripheral."}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The wording of the string is up to you but should essentially state that ‘Bluetooth is required for connection to a Nix device’","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"When editing "},{"code":"info.plist","type":"codeVoice"},{"text":" from within Xcode, these keys correspond to the following entries:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"NSBluetoothPeripheralUsageDescription"},{"type":"text","text":": ‘Privacy – Bluetooth Peripheral Usage Description’"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"NSBluetoothAlwaysUsageDescription"},{"type":"text","text":": ‘Privacy – Bluetooth Always Usage Description’"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"},{"name":"Important","style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Failure to add these strings will cause the app to crash when accessing the Bluetooth peripheral","type":"text"}]}]},{"type":"heading","anchor":"Add-required-entitlements","level":3,"text":"Add required entitlements"},{"type":"paragraph","inlineContent":[{"text":"For macOS projects, additional entries are required in the ","type":"text"},{"type":"codeVoice","code":".entitlements"},{"type":"text","text":" file for your project:"}]},{"rows":[[[{"inlineContent":[{"type":"text","text":"Key"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Type"}]}],[{"type":"paragraph","inlineContent":[{"text":"Value","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Remark"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"com.apple.security.device.bluetooth","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Boolean","type":"text"}]}],[{"inlineContent":[{"code":"YES","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required for access to Nix device via Bluetooth"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"com.apple.security.device.serial"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Boolean","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"}]}],[{"inlineContent":[{"type":"text","text":"Required for access to Nix device via USB"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"com.apple.security.device.usb"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Boolean"}]}],[{"type":"paragraph","inlineContent":[{"code":"YES","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required for access to Nix device via USB"}]}]],[[{"inlineContent":[{"code":"com.apple.security.network.client","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Boolean","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"code":"YES","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Required for SDK authentication (once per 30 day period)"}],"type":"paragraph"}]]],"alignments":["left","left","left","left"],"type":"table","header":"row"},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"text":"You can skip this step if your project targets iOS only.","type":"text"}]}],"name":"Tip","type":"aside"},{"level":3,"text":"Import statements","type":"heading","anchor":"Import-statements"},{"inlineContent":[{"type":"text","text":"Add an import statement to your source code files that will use the Nix Universal SDK."}],"type":"paragraph"},{"text":"Swift example","anchor":"Swift-example","level":4,"type":"heading"},{"syntax":"swift","type":"codeListing","code":["import NixUniversalSDK"]},{"level":4,"anchor":"Objective-C-example","text":"Objective-C example","type":"heading"},{"code":["#import <NixUniversalSDK\/universalsdk.h>"],"type":"codeListing","syntax":"objc"},{"type":"heading","text":"Next Steps","level":2,"anchor":"Next-Steps"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","type":"reference","isActive":true}]}]}]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/add-to-xcode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/add-to-xcode"]}],"seeAlsoSections":[{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"anchor":"Getting-Started"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"references":{"swiftpm.png":{"identifier":"swiftpm.png","alt":"Swift Package Manager","type":"image","variants":[{"url":"\/images\/com.nixsensor.universalsdk\/swiftpm@3x.png","traits":["3x","light"]}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"title":"Discovering and Connecting to Nix Devices","kind":"article","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","abstract":[{"text":"Use the device scanner to discover Nix devices and open a connection","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","role":"article","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"title":"Handling Measurement Data","url":"\/documentation\/nixuniversalsdk\/handling-measurements","kind":"article","abstract":[{"text":"Query measurement values including colorimetry, spectral reflectance, and density","type":"text"}],"role":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"title":"Wrapper for Usage in C\/C++","url":"\/documentation\/nixuniversalsdk\/wrapper","kind":"article","abstract":[{"type":"text","text":"Review an example project which provides a C\/C++ interface on macOS"}],"role":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","type":"topic"},"https://www.nixsensor.com/sdk-eula-ios":{"type":"link","titleInlineContent":[{"type":"text","text":"End User License Agreement"}],"title":"End User License Agreement","url":"https:\/\/www.nixsensor.com\/sdk-eula-ios","identifier":"https:\/\/www.nixsensor.com\/sdk-eula-ios"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"abstract":[{"type":"text","text":"Review the changes made in this version of the library"}],"role":"article","kind":"article","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","title":"Release Notes","url":"\/documentation\/nixuniversalsdk\/release-notes"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"url":"\/documentation\/nixuniversalsdk\/example-apps","role":"article","abstract":[{"type":"text","text":"Explore source code for demo iOS and macOS applications"}],"title":"Example Applications","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","kind":"article","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"title":"Device Operations","role":"article","type":"topic","abstract":[{"text":"Take measurements, set device options, and query device properties","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","url":"\/documentation\/nixuniversalsdk\/device-operations","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"role":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","title":"Activating the SDK License","kind":"article","url":"\/documentation\/nixuniversalsdk\/activating-license","type":"topic","abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}]},"filemenu.png":{"type":"image","alt":"Xcode file menu","variants":[{"url":"\/images\/com.nixsensor.universalsdk\/filemenu@3x.png","traits":["3x","light"]}],"identifier":"filemenu.png"},"https://www.github.com/nixsensor/nix-universal-sdk-ios-dist":{"type":"link","titleInlineContent":[{"text":"GitHub","type":"text"}],"title":"GitHub","url":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist","identifier":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist"},"frameworks.png":{"type":"image","alt":"Build Target Frameworks","variants":[{"url":"\/images\/com.nixsensor.universalsdk\/frameworks@3x.png","traits":["3x","light"]}],"identifier":"frameworks.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"generated":true,"anchor":"Getting-Started"}],"op":"replace","path":"\/seeAlsoSections"}]}]}