{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colortype"]}],"sections":[],"abstract":[{"text":"Enum to describe the base color data types available for ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","type":"reference","isActive":true},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ColorType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorType","kind":"identifier"}],"navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ColorType","symbolKind":"enum","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","title":"ColorType","roleHeading":"Enumeration"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELAB","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELCH","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELUV","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/name"]},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/fromName(_:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/RawRepresentable-Implementations"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"type":"topic","role":"collection","title":"NixUniversalSDK","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"abstract":[{"text":"Enum to describe the base color data types available for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorType"}],"kind":"symbol","title":"ColorType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorType","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/colortype","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","role":"symbol"},"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"abstract":[{"text":"Report color value as CIEXYZ value on unity scale.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","navigatorTitle":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIEXYZ","kind":"identifier"}],"type":"topic","title":"ColorType.CIEXYZ"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIELAB":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIELAB"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype\/cielab","navigatorTitle":[{"text":"ColorTypeCIELAB","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Report color value as CIELAB value.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELAB","title":"ColorType.CIELAB"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/init(rawValue:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype\/init(rawvalue:)","type":"topic","title":"init(rawValue:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/name":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype\/name","role":"symbol","title":"name","abstract":[{"text":"String representation of this ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","isActive":true,"type":"reference"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/name"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/nixuniversalsdk\/colortype\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIELCH":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIELCH"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype\/cielch","navigatorTitle":[{"text":"ColorTypeCIELCH","kind":"identifier"}],"role":"symbol","title":"ColorType.CIELCH","abstract":[{"text":"Report color value as CIELCH \/ LCH(ab) value","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELCH"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"type":"topic","title":"IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"IColorData","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IColorData","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/nixuniversalsdk\/colortype\/equatable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/Equatable-Implementations","title":"Equatable Implementations","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/fromName(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype\/fromname(_:)","role":"symbol","title":"fromName(_:)","abstract":[{"text":"Helper to provide the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","type":"reference","isActive":true},{"text":" enum for a particular color type name. If an invalid name is provided, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","isActive":true},{"text":" is returned.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/fromName(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIELUV":{"role":"symbol","title":"ColorType.CIELUV","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIELUV"}],"abstract":[{"type":"text","text":"Report color as CIELUV value"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELUV","navigatorTitle":[{"text":"ColorTypeCIELUV","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/colortype\/cieluv"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ColorType","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ColorType"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ColorType"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELAB","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELCH","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELUV","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ"],"title":"Enumeration Cases","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ColorType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","value":"ColorType","op":"replace"},{"value":[{"kind":"identifier","text":"ColorType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"text":"ColorType","kind":"identifier"}]},{"value":"ColorTypeCIEXYZ","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELAB\/title","value":"ColorTypeCIELAB","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELAB\/fragments","value":[{"text":"ColorTypeCIELAB","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELCH\/title","value":"ColorTypeCIELCH","op":"replace"},{"value":[{"kind":"identifier","text":"ColorTypeCIELCH"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELCH\/fragments"},{"value":"IColorData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"kind":"identifier","text":"IColorData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","value":[{"text":"IColorData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELUV\/title","value":"ColorTypeCIELUV"},{"value":[{"text":"ColorTypeCIELUV","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELUV\/fragments"}]}]}