{"metadata":{"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DensityData"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)DensityData","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DensityData","kind":"identifier"}],"title":"DensityData","roleHeading":"Class"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DensityData","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Since 4.0.2","type":"text"}],"type":"paragraph"}]}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/init(lambda:reflectance:mode:status:)"],"anchor":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/autoIndex","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/status","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/statusLabel","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/value"],"anchor":"Instance-Properties"},{"anchor":"Type-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_C","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_K","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_M","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_Y"],"title":"Type Properties","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/densitydata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/densitydata"]}],"abstract":[{"text":"Class describing density data","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/DENSITY_CHANNEL_K":{"abstract":[],"role":"symbol","type":"topic","title":"DENSITY_CHANNEL_K","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_K","url":"\/documentation\/nixuniversalsdk\/densitydata\/density_channel_k","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"DENSITY_CHANNEL_K","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"navigatorTitle":[{"text":"IDensityData","kind":"identifier"}],"title":"IDensityData","role":"symbol","url":"\/documentation\/nixuniversalsdk\/idensitydata","abstract":[{"text":"Protocol describing density data","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IDensityData","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/T":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","abstract":[{"type":"text","text":"Status T (ISO 5-3:2009)"}],"title":"DensityStatus.T","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"T","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/densitystatus\/t","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DensityStatusT"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/status":{"abstract":[{"type":"text","text":"Density status for this value"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"role":"symbol","type":"topic","title":"status","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/status","url":"\/documentation\/nixuniversalsdk\/densitydata\/status","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","type":"unresolvable"},"doc://com.nixsensor.universalsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/DENSITY_CHANNEL_Y":{"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_Y","type":"topic","url":"\/documentation\/nixuniversalsdk\/densitydata\/density_channel_y","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DENSITY_CHANNEL_Y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"DENSITY_CHANNEL_Y"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/DENSITY_CHANNEL_C":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_C","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DENSITY_CHANNEL_C"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"DENSITY_CHANNEL_C","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/nixuniversalsdk\/densitydata\/density_channel_c"},"doc://com.nixsensor.universalsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/init(lambda:reflectance:mode:status:)":{"url":"\/documentation\/nixuniversalsdk\/densitydata\/init(lambda:reflectance:mode:status:)","role":"symbol","title":"init(lambda:reflectance:mode:status:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"lambda","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">, "},{"text":"reflectance","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier","text":"ScanMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","text":"DensityStatus","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/init(lambda:reflectance:mode:status:)","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/statusLabel":{"role":"symbol","abstract":[{"type":"text","text":"Density status label for this value (eg - ‘T’ for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T"},{"type":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"statusLabel"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/statusLabel","url":"\/documentation\/nixuniversalsdk\/densitydata\/statuslabel","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"statusLabel"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/autoIndex":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/autoIndex","title":"autoIndex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoIndex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoIndex"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Indicates which channel (0 - 3) in ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/value","isActive":true},{"type":"text","text":" has the strongest response, with greyness override"}],"url":"\/documentation\/nixuniversalsdk\/densitydata\/autoindex"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData","navigatorTitle":[{"text":"DensityData","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/densitydata","title":"DensityData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DensityData","kind":"identifier"}],"abstract":[{"type":"text","text":"Class describing density data"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/DENSITY_CHANNEL_M":{"abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"DENSITY_CHANNEL_M","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/DENSITY_CHANNEL_M","url":"\/documentation\/nixuniversalsdk\/densitydata\/density_channel_m","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"DENSITY_CHANNEL_M","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://com.nixsensor.universalsdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ"},"doc://com.nixsensor.universalsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/mode":{"url":"\/documentation\/nixuniversalsdk\/densitydata\/mode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"abstract":[{"type":"text","text":"Scan mode for this measurement."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/mode","role":"symbol","navigatorTitle":[{"text":"mode","kind":"identifier"}],"title":"mode","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData/value":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/densitydata\/value","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/value","role":"symbol","title":"value","type":"topic","kind":"symbol","abstract":[{"text":"Density values (4 channels, CMYK order)","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"DensityData","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DensityData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DensityData"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/autoIndex","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/status","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/statusLabel","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData\/value"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"],"title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DensityData","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title","value":"IDensityData","op":"replace"},{"op":"replace","value":[{"text":"IDensityData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments"},{"value":[{"kind":"identifier","text":"IDensityData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/title","value":"DensityStatusT","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/fragments","op":"replace","value":[{"text":"DensityStatusT","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1status\/title","value":"status"},{"op":"replace","value":[{"kind":"identifier","text":"status"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1status\/fragments"},{"value":"statusLabel","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1statusLabel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"statusLabel"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1statusLabel\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1autoIndex\/title","value":"autoIndex","op":"replace"},{"op":"replace","value":[{"text":"autoIndex","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1autoIndex\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/title","value":"DensityData","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/fragments","op":"replace","value":[{"text":"DensityData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/navigatorTitle","value":[{"kind":"identifier","text":"DensityData"}],"op":"replace"},{"value":"mode","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1mode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1value\/title","op":"replace","value":"value"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData~1value\/fragments"}]}]}