{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/COLD","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_DISABLED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_PERMISSIONS","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INTERNAL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INVALID_HARDWARE_ID","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/IDLE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/SCANNING"],"generated":true},{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/name"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState"},"kind":"symbol","metadata":{"role":"symbol","title":"DeviceScannerState","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerState"}],"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@DeviceScannerState","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScannerState"}]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/COLD":{"type":"topic","title":"DeviceScannerState.COLD","navigatorTitle":[{"text":"DeviceScannerStateCOLD","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Bluetooth scanner state is cold \/ unknown (scanner is initializing)"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"COLD","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/cold","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/COLD"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_INTERNAL":{"role":"symbol","title":"DeviceScannerState.ERROR_INTERNAL","abstract":[{"type":"text","text":"Bluetooth scanner could not start due to an internal error."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INTERNAL","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_internal","navigatorTitle":[{"text":"DeviceScannerStateERROR_INTERNAL","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_INTERNAL","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/SCANNING":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/SCANNING","abstract":[{"text":"Bluetooth scanner is actively searching for devices.","type":"text"}],"title":"DeviceScannerState.SCANNING","navigatorTitle":[{"text":"DeviceScannerStateSCANNING","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCANNING","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/scanning"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"role":"symbol","title":"IDeviceScanner","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","abstract":[{"type":"text","text":"Protocol implemented by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/idevicescanner","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_BLUETOOTH_DISABLED":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_disabled","abstract":[{"type":"text","text":"Bluetooth scanner could not start because Bluetooth is disabled on this mobile device."}],"navigatorTitle":[{"text":"DeviceScannerStateERROR_BLUETOOTH_DISABLED","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_DISABLED","kind":"symbol","title":"DeviceScannerState.ERROR_BLUETOOTH_DISABLED","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_BLUETOOTH_DISABLED","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/RawRepresentable-Implementations","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/rawrepresentable-implementations","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/Equatable-Implementations","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/equatable-implementations"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_LICENSE":{"navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_LICENSE"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_license","title":"DeviceScannerState.ERROR_LICENSE","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE","abstract":[{"type":"text","text":"Bluetooth scanner could not start due to a problem with the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"type":"text","text":". Check "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","isActive":true,"type":"reference"},{"type":"text","text":" for details."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/name":{"role":"symbol","title":"name","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/name","kind":"symbol","abstract":[{"text":"String representation of this ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","type":"reference"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/name"},"doc://com.nixsensor.universalsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/IDLE":{"role":"symbol","abstract":[{"text":"Bluetooth scanner is not actively searching for devices.","type":"text"}],"kind":"symbol","title":"DeviceScannerState.IDLE","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/IDLE","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateIDLE"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDLE"}],"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/idle","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/state":{"abstract":[{"text":"Describes the current state of the  ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"text":". Nix Universal SDK functions are available only if license is active (i.e. - the state is ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","isActive":true,"type":"reference"},{"text":")","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","url":"\/documentation\/nixuniversalsdk\/licensemanager\/state","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState"}],"title":"state","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","url":"\/documentation\/nixuniversalsdk\/licensemanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}],"title":"LicenseManager","role":"symbol","navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_INVALID_HARDWARE_ID":{"role":"symbol","title":"DeviceScannerState.ERROR_INVALID_HARDWARE_ID","abstract":[{"type":"text","text":"Bluetooth scanner could not start because an invalid hardware ID was provided."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INVALID_HARDWARE_ID","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_invalid_hardware_id","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_INVALID_HARDWARE_ID"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_BLUETOOTH_PERMISSIONS":{"role":"symbol","abstract":[{"text":"Bluetooth scanner could not start because Bluetooth permissions have not been granted.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_PERMISSIONS","title":"DeviceScannerState.ERROR_BLUETOOTH_PERMISSIONS","navigatorTitle":[{"text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_permissions"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_BLUETOOTH_UNAVAILABLE":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","title":"DeviceScannerState.ERROR_BLUETOOTH_UNAVAILABLE","abstract":[{"type":"text","text":"Bluetooth scanner could not start because Bluetooth is not available on this mobile device."}],"navigatorTitle":[{"text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_unavailable","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate","abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"navigatorTitle":[{"text":"DeviceScannerState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","type":"topic","title":"DeviceScannerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DeviceScannerState"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DeviceScannerState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceScannerState"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/COLD","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_DISABLED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_PERMISSIONS","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_UNAVAILABLE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INTERNAL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_INVALID_HARDWARE_ID","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/IDLE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/SCANNING"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScannerState","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"value":"DeviceScannerStateCOLD","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1COLD\/title"},{"value":[{"kind":"identifier","text":"DeviceScannerStateCOLD"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1COLD\/fragments"},{"value":"DeviceScannerStateERROR_INTERNAL","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_INTERNAL\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_INTERNAL\/fragments","value":[{"text":"DeviceScannerStateERROR_INTERNAL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1SCANNING\/title","value":"DeviceScannerStateSCANNING"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1SCANNING\/fragments","value":[{"text":"DeviceScannerStateSCANNING","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","op":"replace","value":"IDeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IDeviceScanner"}]},{"value":"DeviceScannerStateERROR_BLUETOOTH_DISABLED","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_DISABLED\/title","op":"replace"},{"op":"replace","value":[{"text":"DeviceScannerStateERROR_BLUETOOTH_DISABLED","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_DISABLED\/fragments"},{"op":"replace","value":"DeviceScannerStateERROR_LICENSE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_LICENSE\/title"},{"op":"replace","value":[{"text":"DeviceScannerStateERROR_LICENSE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_LICENSE\/fragments"},{"op":"replace","value":"DeviceScannerStateIDLE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1IDLE\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScannerStateIDLE"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1IDLE\/fragments"},{"op":"replace","value":"state","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/title"},{"op":"replace","value":[{"text":"state","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/fragments"},{"op":"replace","value":"LicenseManager","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title"},{"op":"replace","value":[{"text":"LicenseManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseManager"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle"},{"op":"replace","value":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_INVALID_HARDWARE_ID\/title"},{"op":"replace","value":[{"text":"DeviceScannerStateERROR_INVALID_HARDWARE_ID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_INVALID_HARDWARE_ID\/fragments"},{"op":"replace","value":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_PERMISSIONS\/title"},{"op":"replace","value":[{"text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_PERMISSIONS\/fragments"},{"value":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_UNAVAILABLE\/title"},{"value":[{"text":"DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_UNAVAILABLE\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner"},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"text":"DeviceScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title","value":"DeviceScannerState"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","value":[{"kind":"identifier","text":"DeviceScannerState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceScannerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}