{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"abstract":[{"type":"text","text":"Definition for a callback from an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance on a connection state change, battery state change, or external power state change."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStateDelegate","kind":"identifier"}]}]},{"kind":"mentions","mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting"]}],"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)DeviceStateDelegate","symbolKind":"protocol","title":"DeviceStateDelegate","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceStateDelegate"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestatedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestatedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onBatteryStateChanged(_:newState:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onConnected(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onExtPowerStateChanged(_:newState:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onExtPowerStateChanged(_:newState:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onExtPowerStateChanged(_:newState:)","url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/onextpowerstatechanged(_:newstate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onExtPowerStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"newState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onExtPowerStateChanged(_:newState:)","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"onExtPowerStateChanged:newState:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Called when the Nix device has been connected or disconnected from an external power source.","type":"text"}],"kind":"symbol","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"title":"IDeviceCompat","type":"topic","navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"kind":"article","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","title":"Discovering and Connecting to Nix Devices","role":"article","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","abstract":[{"type":"text","text":"Use the device scanner to discover Nix devices and open a connection"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"abstract":[{"text":"Definition for a callback from an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DeviceStateDelegate","kind":"identifier"}],"title":"DeviceStateDelegate","type":"topic","navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onConnected(_:)":{"abstract":[{"text":"Called when the Nix device has completed the connection process and is now idle.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onConnected(_:)","url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/onconnected(_:)","required":true,"title":"onConnected(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnected","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","kind":"typeIdentifier","text":"IDeviceCompat"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"text":"onConnected:","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onBatteryStateChanged(_:newState:)":{"role":"symbol","title":"onBatteryStateChanged(_:newState:)","abstract":[{"text":"Called when the Nix device has updated its battery level measurement.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onBatteryStateChanged(_:newState:)","url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/onbatterystatechanged(_:newstate:)","required":true,"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBatteryStateChanged:newState:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onBatteryStateChanged"},{"text":"(","kind":"text"},{"text":"IDeviceCompat","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":")"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onDisconnected(_:status:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)","title":"onDisconnected(_:status:)","abstract":[{"type":"text","text":"Called when the Nix device has disconnected from the host."}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"onDisconnected:status:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onDisconnected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IDeviceCompat","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DeviceStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/ondisconnected(_:status:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DeviceStateDelegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onBatteryStateChanged(_:newState:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onConnected(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onExtPowerStateChanged(_:newState:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceStateDelegate"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onExtPowerStateChanged:newState:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onExtPowerStateChanged(_:newState:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onExtPowerStateChanged(_:newState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtPowerStateChanged:newState:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"value":"DeviceStateDelegate","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title"},{"value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","op":"replace","value":"DeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onConnected(_:)\/title","value":"onConnected:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onConnected(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConnected:"}],"op":"replace"},{"value":"onBatteryStateChanged:newState:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onBatteryStateChanged(_:newState:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onBatteryStateChanged:newState:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onBatteryStateChanged(_:newState:)\/fragments"},{"value":"onDisconnected:status:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onDisconnected(_:status:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDisconnected:status:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onDisconnected(_:status:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}