{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/A_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/A_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D55_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D55_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_2"],"generated":true,"anchor":"Enumeration-Cases"},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/init(rawValue:)"]},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fullName","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/illuminant","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/intValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/numberValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/observer","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/shortName","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/xyz"],"anchor":"Instance-Properties"},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromFullName(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromInt(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromNumber(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromShortName(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/select(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/unwrapSet(_:)"]},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/referencewhite"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"metadata":{"roleHeading":"Enumeration","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"title":"ReferenceWhite","symbolKind":"enum","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F7_2":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteF7_2"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/f7_2","abstract":[{"type":"text","text":"White point using Illuminant F7 and 2 degree observer."}],"title":"ReferenceWhite.F7_2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F7_2"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_2","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/xyz":{"url":"\/documentation\/nixuniversalsdk\/referencewhite\/xyz","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/xyz","type":"topic","kind":"symbol","role":"symbol","title":"xyz","abstract":[{"type":"text","text":"CIEXYZ value for the selected reference white point"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xyz"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"type":"topic","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"role":"symbol","kind":"symbol","title":"Illuminant","url":"\/documentation\/nixuniversalsdk\/illuminant"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/intValue":{"title":"intValue","abstract":[{"type":"text","text":"Integer raw value for this "},{"type":"codeVoice","code":"ReferenceWhite"}],"kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/intvalue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"intValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/intValue"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/C_10":{"abstract":[{"text":"White point using Illuminant C and 10 degree observer.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/c_10","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_10","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"C_10","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteC_10"}],"title":"ReferenceWhite.C_10"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/A_10":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteA_10"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/a_10","kind":"symbol","title":"ReferenceWhite.A_10","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"A_10","kind":"identifier"}],"abstract":[{"text":"White point using Illuminant A and 10 degree observer.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/A_10"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/numberValue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/numberValue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"numberValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/numbervalue","type":"topic","title":"numberValue","role":"symbol","abstract":[{"type":"text","text":"Wraps this enum in a "},{"type":"codeVoice","code":"NSNumber"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/init(rawValue:)":{"type":"topic","role":"symbol","title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/referencewhite\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt16","preciseIdentifier":"s:s6UInt16V"},{"text":")","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D75_2":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"D75_2"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d75_2","type":"topic","title":"ReferenceWhite.D75_2","role":"symbol","abstract":[{"type":"text","text":"White point using Illuminant D75 and 2 degree observer."}],"navigatorTitle":[{"text":"ReferenceWhiteD75_2","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/RawRepresentable-Implementations","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D65_2":{"abstract":[{"text":"White point using Illuminant D65 and 2 degree observer.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d65_2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_2","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"D65_2"}],"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD65_2"}],"title":"ReferenceWhite.D65_2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/select(illuminant:observer:)":{"url":"\/documentation\/nixuniversalsdk\/referencewhite\/select(illuminant:observer:)","type":"topic","role":"symbol","title":"select(illuminant:observer:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/select(illuminant:observer:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"}],"abstract":[{"type":"text","text":"Helper to provide the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"},{"type":"text","text":" enum for a combination of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"},{"text":".","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F11_10":{"abstract":[{"text":"White point using Illuminant F11 and 10 degree observer.","type":"text"}],"title":"ReferenceWhite.F11_10","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_10","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/f11_10","navigatorTitle":[{"text":"ReferenceWhiteF11_10","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F11_10"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/A_2":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/A_2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"A_2","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/a_2","type":"topic","title":"ReferenceWhite.A_2","role":"symbol","abstract":[{"type":"text","text":"White point using Illuminant A and 2 degree observer."}],"navigatorTitle":[{"text":"ReferenceWhiteA_2","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D75_10":{"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d75_10","title":"ReferenceWhite.D75_10","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_10","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD75_10"}],"abstract":[{"text":"White point using Illuminant D75 and 10 degree observer.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"D75_10","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/C_2":{"type":"topic","abstract":[{"text":"White point using Illuminant C and 2 degree observer.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/c_2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_2","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"C_2"}],"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteC_2"}],"title":"ReferenceWhite.C_2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/shortName":{"kind":"symbol","abstract":[{"text":"Short name (e.g. - ","type":"text"},{"type":"codeVoice","code":"D50_2"},{"type":"text","text":" for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2"},{"type":"text","text":")"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"shortName","url":"\/documentation\/nixuniversalsdk\/referencewhite\/shortname","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/shortName"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/observer":{"abstract":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","isActive":true,"type":"reference"},{"text":" for the selected reference white","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"observer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/observer","title":"observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/observer","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F7_10":{"role":"symbol","abstract":[{"text":"White point using Illuminant F7 and 10 degree observer.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteF7_10"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_10","url":"\/documentation\/nixuniversalsdk\/referencewhite\/f7_10","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"F7_10","kind":"identifier"}],"title":"ReferenceWhite.F7_10","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F2_10":{"title":"ReferenceWhite.F2_10","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F2_10"}],"navigatorTitle":[{"text":"ReferenceWhiteF2_10","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_10","abstract":[{"text":"White point using Illuminant F2 and 10 degree observer.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/f2_10"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/fromShortName(_:)":{"title":"fromShortName(_:)","role":"symbol","abstract":[{"type":"text","text":"Helper to provide the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","isActive":true,"type":"reference"},{"text":" enum for a particular reference white short name. If an invalid name is provided, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","isActive":true},{"text":" is returned.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromShortName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromShortName(_:)","url":"\/documentation\/nixuniversalsdk\/referencewhite\/fromshortname(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"title":"ReferenceWhite","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/EMPTY":{"url":"\/documentation\/nixuniversalsdk\/referencewhite\/empty","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"EMPTY","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","title":"ReferenceWhite.EMPTY","type":"topic","role":"symbol","navigatorTitle":[{"text":"ReferenceWhiteEMPTY","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Unknown \/ other reference white point"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","role":"collection","title":"NixUniversalSDK","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/fromFullName(_:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromFullName","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"}],"title":"fromFullName(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromFullName(_:)","type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/fromfullname(_:)","role":"symbol","abstract":[{"text":"Helper to provide the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","isActive":true,"type":"reference"},{"type":"text","text":" enum for a particular reference white name. If an invalid name is provided, "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","isActive":true},{"type":"text","text":" is returned."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D55_2":{"navigatorTitle":[{"text":"ReferenceWhiteD55_2","kind":"identifier"}],"abstract":[{"type":"text","text":"White point using Illuminant D55 and 2 degree observer."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D55_2","role":"symbol","kind":"symbol","type":"topic","title":"ReferenceWhite.D55_2","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d55_2","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D55_2","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_10":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_10","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50_10"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_10","type":"topic","title":"ReferenceWhite.D50_10","role":"symbol","abstract":[{"type":"text","text":"White point using Illuminant D50 and 10 degree observer."}],"navigatorTitle":[{"text":"ReferenceWhiteD50_10","kind":"identifier"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D65_10":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_10","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d65_10","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD65_10"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"D65_10","kind":"identifier"}],"title":"ReferenceWhite.D65_10","abstract":[{"text":"White point using Illuminant D65 and 10 degree observer.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/unwrapSet(_:)":{"abstract":[],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/unwrapset(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/unwrapSet(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unwrapSet"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":">?) -> ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"text":">","kind":"text"}],"title":"unwrapSet(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/illuminant":{"role":"symbol","abstract":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","isActive":true,"type":"reference"},{"text":" for the selected reference white","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/illuminant","url":"\/documentation\/nixuniversalsdk\/referencewhite\/illuminant","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"illuminant","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"}],"kind":"symbol","title":"illuminant","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F2_2":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"F2_2"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/f2_2","abstract":[{"text":"White point using Illuminant F2 and 2 degree observer.","type":"text"}],"title":"ReferenceWhite.F2_2","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_2","navigatorTitle":[{"text":"ReferenceWhiteF2_2","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D55_10":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD55_10"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d55_10","title":"ReferenceWhite.D55_10","abstract":[{"type":"text","text":"White point using Illuminant D55 and 10 degree observer."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D55_10","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"D55_10","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/fullName":{"type":"topic","title":"fullName","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fullName","kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/fullname","abstract":[{"type":"text","text":"Full name for display in UI (e.g. - ‘D50\/2°’ for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2"},{"type":"text","text":")"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"title":"Swift.CaseIterable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/fromNumber(_:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromNumber","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/fromnumber(_:)","type":"topic","title":"fromNumber(_:)","role":"symbol","abstract":[{"type":"text","text":"Unwraps from a "},{"code":"NSNumber","type":"codeVoice"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromNumber(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/Equatable-Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/nixuniversalsdk\/referencewhite\/equatable-implementations","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_2":{"abstract":[{"text":"White point using Illuminant D50 and 2 degree observer.","type":"text"}],"title":"ReferenceWhite.D50_2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_2","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50_2"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"url":"\/documentation\/nixuniversalsdk\/observer","type":"topic","role":"symbol","title":"Observer","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"navigatorTitle":[{"text":"Observer","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]},"doc://com.nixsensor.universalsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/fromInt(_:)":{"type":"topic","title":"fromInt(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/fromInt(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite\/fromint(_:)","abstract":[{"text":"Helper to provide the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","isActive":true,"type":"reference"},{"type":"text","text":" enum for a particular reference ID. If an invalid ID is provided, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY"},{"type":"text","text":" is returned."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromInt"},{"kind":"text","text":"("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F11_2":{"url":"\/documentation\/nixuniversalsdk\/referencewhite\/f11_2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"F11_2","kind":"identifier"}],"navigatorTitle":[{"text":"ReferenceWhiteF11_2","kind":"identifier"}],"title":"ReferenceWhite.F11_2","abstract":[{"type":"text","text":"White point using Illuminant F11 and 2 degree observer."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_2"},"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"ReferenceWhite","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"text":"ReferenceWhite","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ReferenceWhite","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/A_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/A_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/C_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D55_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D55_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/EMPTY","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F11_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_2","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_10","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_2"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReferenceWhite","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint16_t","text":"uint16_t"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_2\/title","op":"replace","value":"ReferenceWhiteF7_2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_2\/fragments","value":[{"text":"ReferenceWhiteF7_2","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","value":"Illuminant"},{"op":"replace","value":[{"text":"Illuminant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace"},{"value":"ReferenceWhiteC_10","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1C_10\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1C_10\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteC_10"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1A_10\/title","value":"ReferenceWhiteA_10"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1A_10\/fragments","op":"replace","value":[{"text":"ReferenceWhiteA_10","kind":"identifier"}]},{"value":"ReferenceWhiteD75_2","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D75_2\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D75_2\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteD75_2"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D65_2\/title","value":"ReferenceWhiteD65_2","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D65_2\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteD65_2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F11_10\/title","value":"ReferenceWhiteF11_10"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F11_10\/fragments","op":"replace","value":[{"text":"ReferenceWhiteF11_10","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1A_2\/title","value":"ReferenceWhiteA_2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1A_2\/fragments","value":[{"text":"ReferenceWhiteA_2","kind":"identifier"}],"op":"replace"},{"value":"ReferenceWhiteD75_10","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D75_10\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D75_10\/fragments","op":"replace","value":[{"text":"ReferenceWhiteD75_10","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1C_2\/title","op":"replace","value":"ReferenceWhiteC_2"},{"value":[{"kind":"identifier","text":"ReferenceWhiteC_2"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1C_2\/fragments"},{"op":"replace","value":"ReferenceWhiteF7_10","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_10\/title"},{"op":"replace","value":[{"text":"ReferenceWhiteF7_10","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_10\/fragments"},{"value":"ReferenceWhiteF2_10","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F2_10\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhiteF2_10"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F2_10\/fragments"},{"value":"ReferenceWhite","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title"},{"value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1EMPTY\/title","op":"replace","value":"ReferenceWhiteEMPTY"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1EMPTY\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteEMPTY"}]},{"op":"replace","value":"ReferenceWhiteD55_2","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D55_2\/title"},{"value":[{"kind":"identifier","text":"ReferenceWhiteD55_2"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D55_2\/fragments"},{"value":"ReferenceWhiteD50_10","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_10\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_10\/fragments","op":"replace","value":[{"text":"ReferenceWhiteD50_10","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D65_10\/title","value":"ReferenceWhiteD65_10"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D65_10\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteD65_10"}]},{"value":"ReferenceWhiteF2_2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F2_2\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F2_2\/fragments","value":[{"text":"ReferenceWhiteF2_2","kind":"identifier"}],"op":"replace"},{"value":"ReferenceWhiteD55_10","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D55_10\/title","op":"replace"},{"value":[{"text":"ReferenceWhiteD55_10","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D55_10\/fragments"},{"value":"ReferenceWhiteD50_2","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/fragments","op":"replace","value":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}]},{"value":"Observer","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","op":"replace"},{"value":[{"text":"Observer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","value":[{"kind":"identifier","text":"Observer"}]},{"value":"ReferenceWhiteF11_2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F11_2\/title"},{"value":[{"text":"ReferenceWhiteF11_2","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F11_2\/fragments"}]}]}