{"abstract":[{"type":"text","text":"Nullable instance of an "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","type":"reference"},{"type":"text","text":" object"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)ISpectralData","text":"id<ISpectralData>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpectralDataNullable"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNullable","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"SpectralDataNullable","kind":"identifier"}],"symbolKind":"typealias","fragments":[{"kind":"identifier","text":"SpectralDataNullable"}],"externalID":"c:TypeAliases.h@T@SpectralDataNullable","roleHeading":"Type Alias","modules":[{"name":"NixUniversalSDK"}],"title":"SpectralDataNullable"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldatanullable"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralDataNullable":{"abstract":[{"text":"Nullable instance of an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","type":"reference"},{"type":"text","text":" object"}],"fragments":[{"kind":"identifier","text":"SpectralDataNullable"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNullable","title":"SpectralDataNullable","url":"\/documentation\/nixuniversalsdk\/spectraldatanullable","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","title":"ISpectralData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"kind":"symbol","title":"NixUniversalSDK","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","op":"replace","value":"ISpectralData"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle","value":[{"kind":"identifier","text":"ISpectralData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}