{"abstract":[{"type":"text","text":"Status A (ISO 5-3:2009)"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"A"}],"languages":["swift"]}]}],"sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","title":"DensityStatus.A","externalID":"c:@M@NixUniversalSDK@E@DensityStatus@DensityStatusA","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DensityStatusA"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"A","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/A"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/densitystatus\/a"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/densitystatus\/a"]}],"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"kind":"symbol","role":"collection","title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/A":{"title":"DensityStatus.A","kind":"symbol","navigatorTitle":[{"text":"DensityStatusA","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/A","role":"symbol","url":"\/documentation\/nixuniversalsdk\/densitystatus\/a","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"A","kind":"identifier"}],"abstract":[{"type":"text","text":"Status A (ISO 5-3:2009)"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DensityStatus"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/densitystatus","navigatorTitle":[{"kind":"identifier","text":"DensityStatus"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","abstract":[{"text":"Enum to describe the available options for density status","type":"text"}],"type":"topic","title":"DensityStatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DensityStatusA"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DensityStatusA","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DensityStatusA"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DensityStatusA","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1A\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DensityStatusA"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1A\/fragments"},{"value":"DensityStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments","value":[{"kind":"identifier","text":"DensityStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","value":[{"kind":"identifier","text":"DensityStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}