{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/observer\/fromfov(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromFov"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fov"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Observer","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"}]}]}],"abstract":[{"type":"text","text":"Helper to provide the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"reference"},{"text":" enum for a particular observer field-of-view (FOV). Valid options are 2 and 10; if an invalid value is provided, ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"},{"text":" is returned.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"]]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFov(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"fromFov(_:)","roleHeading":"Type Method","externalID":"s:15NixUniversalSDK8ObserverO7fromFovyACSiFZ","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromFov","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier","text":"Observer"}],"modules":[{"name":"NixUniversalSDK"}]},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/fromFov(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fromFov","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/fromFov(_:)","kind":"symbol","title":"fromFov(_:)","abstract":[{"type":"text","text":"Helper to provide the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","isActive":true,"type":"reference"},{"text":" enum for a particular observer field-of-view (FOV). Valid options are 2 and 10; if an invalid value is provided, ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE"},{"type":"text","text":" is returned."}],"url":"\/documentation\/nixuniversalsdk\/observer\/fromfov(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/NONE":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NONE","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverNONE"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/NONE","title":"Observer.NONE","url":"\/documentation\/nixuniversalsdk\/observer\/none","abstract":[{"type":"text","text":"Observer defined by CIE1964 (10 degree)"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"role":"collection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"navigatorTitle":[{"text":"Observer","kind":"identifier"}],"title":"Observer","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/observer","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1NONE\/title","value":"ObserverNONE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1NONE\/fragments","op":"replace","value":[{"text":"ObserverNONE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"text":"Observer","kind":"identifier"}],"op":"replace"},{"value":[{"text":"Observer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}